ensure consistent casing of names
github/codeql pull request #10312
Opened 2022-09-06 09:19 UTC by erik-krogh

[I recently added a QL-for-QL query to detect when two names only differ in casing inside a single language](https://github.com/github/codeql/pull/10209).  

E.g. Python used both `Multidict` and `MultiDict`.  
This can cause confusion, so I'm fixing it. 

I did the following renamings: 
- `SSA` -> `Ssa`
- `LDAP` -> `Ldap`
- `HTTP` -> `Http`
- `Multidict` -> `MultiDict`
- `URL` -> `Url`
- `Newobj` -> `NewObj`
- `Rethrow` -> `ReThrow`

TODO: Wait for https://github.com/github/codeql/pull/8604

2022-09-09 11:17 UTC, tausbn submitted a review, later dismissed
Python :+1:

2022-09-09 12:05 UTC, michaelnebel approved these changes
C# 👍

2022-09-09 13:02 UTC, geoffw0 submitted a review, later dismissed
C++ :+1:

2022-09-09 13:19 UTC, RasmusWL requested changes
I recently looked at changing the casing to `Http` in Concepts.qll, but ran into the same problems as you have with the `Http` modules in Django/Stdlib and so on. I guess renaming them is fine, since they're inside `Private...` modules that are intended for only internal use.

I was a little surprised about the naming `StdHttp`, and I think it would more consistent to use `StdlibHttp`.

2022-09-09 13:19 UTC, RasmusWL commented on python/ql/lib/semmle/python/frameworks/Multidict.qll
> +module MultiDict {
This naming was intentional (to match the PyPI package name), so lets keep it!

```suggestion
module Multidict {
```

2022-09-09 13:19 UTC, RasmusWL commented on python/ql/lib/semmle/python/frameworks/Multidict.qll
> +deprecated module Multidict = MultiDict;
```suggestion
```

2022-09-09 13:19 UTC, RasmusWL commented on python/ql/lib/semmle/python/frameworks/Yarl.qll
> +    class YarlUrlMultiDictProxyInstance extends MultiDict::MultiDictProxy::InstanceSource {
```suggestion
    class YarlUrlMultiDictProxyInstance extends Multidict::MultiDictProxy::InstanceSource {
```

2022-09-09 13:19 UTC, RasmusWL commented on python/ql/lib/semmle/python/frameworks/Stdlib.qll
> +  module StdHttp {
```suggestion
  module StdlibHttp {
```

2022-09-12 10:03 UTC, MathiasVP submitted a review, later dismissed

2022-09-12 10:10 UTC, asgerf submitted a review, later dismissed
JS 👍

2022-09-12 10:11 UTC, MathiasVP approved these changes

2022-09-12 16:40 UTC, aibaars submitted a review, later dismissed
Ruby changes look good to me.

2022-09-13 07:51 UTC, RasmusWL submitted a review, later dismissed
Python :+1:

2022-09-19 08:29 UTC, RasmusWL approved these changes
Python still :+1: (sorry for the late review, thought this might have been waiting for someone else)

2022-09-19 08:43 UTC, merged