Ruby: Model ActionView
github/codeql pull request #10316
Opened 2022-09-06 11:40 UTC by hmac

Model ActionView.

2022-09-27 13:51 UTC, nickrolfe reviewed
Just a few qldoc nitpicks, but otherwise looks like a nice improvement.

2022-09-27 13:51 UTC, nickrolfe commented on ruby/ql/lib/codeql/ruby/frameworks/ActionView.qll
> +       * Get an argument which is rendered without escaping.
The [style guide](https://github.com/github/codeql/blob/main/docs/qldoc-style-guide.md#predicates-with-result) suggests:
```suggestion
       * Gets an argument which is rendered without escaping.
```

2022-09-27 13:51 UTC, nickrolfe commented on ruby/ql/lib/codeql/ruby/frameworks/ActionView.qll
> +     * A call to ActionView helpers which renders its argument without escaping.
Do you think this reads better?
```suggestion
     * A call to an ActionView helper which renders its argument without escaping.
```

2022-09-27 13:51 UTC, nickrolfe commented on ruby/ql/lib/codeql/ruby/frameworks/ActionView.qll
> +     * `truncate(x, y, sanitize: false)`.
```suggestion
     * `highlight(x, y, sanitize: false)`.
```

2022-09-28 20:44 UTC, alexrford requested changes
Just a couple of minor points, otherwise looks good.

2022-09-28 20:44 UTC, alexrford commented on ruby/ql/lib/codeql/ruby/frameworks/ActionView.qll
> +      override Expr getRawArgument() { result = this.getArgument(0) }
It seems like the `false` argument to `escape` disables escaping of attribute values, so this should maybe find keyword argument values instead? I used the `Legacy syntax` section of https://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/TagHelper.html#method-i-tag as reference.

2022-10-03 08:21 UTC, alexrford commented on ruby/ql/lib/codeql/ruby/frameworks/ActionView.qll
> +      override Expr getRawArgument() { result = this.getArgument(0) }
Interesting, thanks for testing that.

2022-10-03 08:23 UTC, alexrford approved these changes
👍

2022-10-03 14:02 UTC, nickrolfe commented on ruby/ql/lib/codeql/ruby/frameworks/ActionView.qll
> +    abstract class RawHelperCall extends MethodCall {
We should avoid introducing public abstract classes when we don't want/expect users to provide their own implementations. However, I'm already working on a branch to remove the other abstract classes in our framework libraries, so I suggest merging this PR as-is, and then I can fix this one as well.

2022-10-03 19:16 UTC, merged