Docs: Use `instanceof` in `::Range` pattern description
github/codeql pull request #10404
Opened 2022-09-13 13:22 UTC by RasmusWL

Had to change the example away from Go, since their libs have not been
updated to use `instanceof` yet (but I'll make a PR from them shortly)

2022-09-14 13:39 UTC, RasmusWL commented on docs/ql-design-patterns.md
> +`Escaping`, as the name suggests, models various APIs that escape meta-characters. It has a member-predicate `getKind()` that tells you what sort of escaping the modelled function does. For example,
true, thanks :+1:

2022-09-15 07:09 UTC, yoff requested changes
I know it is beyond the current edit, but I feel there is an opportunity to clarify a bit, so I made suggestions to that effect.

2022-09-15 07:09 UTC, yoff commented on docs/ql-design-patterns.md
> +`Escaping::Range` is subclassed to model various APIs, and `kind()` is implemented accordingly.
```suggestion
`Escaping::Range` is subclassed to model various APIs, and `kind()` is implemented accordingly. This typically happens in library models.
```

2022-09-15 07:09 UTC, yoff commented on docs/ql-design-patterns.md
> +But we can also subclass `Escaping` to, as in the above example, talk about all HTML-escaping functions.
```suggestion
But we can also subclass `Escaping`, as in the above example, where `HtmlEscaping` represents all HTML-escaping functions.
```

2022-09-15 13:13 UTC, RasmusWL commented on docs/ql-design-patterns.md
> +`Escaping::Range` is subclassed to model various APIs, and `kind()` is implemented accordingly.
```suggestion
`Escaping::Range` is subclassed to model various APIs, and `kind()` is implemented accordingly (this typically happens in library models).
```

2022-09-16 13:18 UTC, merged