Ruby: add RbiInstantiatedType
github/codeql pull request #10588
Opened 2022-09-27 12:15 UTC by asgerf

2022-09-27 13:53 UTC, alexrford requested changes
Just the flagged suggestion

2022-09-27 13:53 UTC, alexrford commented on ruby/ql/lib/codeql/ruby/experimental/Rbi.qll
> +      RbiInstantiatedType() { getReceiver() instanceof RbiType }
```suggestion
      RbiInstantiatedType() { this.getReceiver() instanceof RbiType }
```

2022-09-28 09:49 UTC, asgerf commented
@alexrford can I get another approval?

2022-09-28 09:49 UTC, alexrford approved these changes

2022-09-28 09:51 UTC, merged