QL: fix some more style-guide violations in the alert-messages
github/codeql pull request #10730
Opened 2022-10-07 09:24 UTC by erik-krogh

2022-10-07 12:28 UTC, tausbn requested changes
A few comments here and there, but otherwise this looks good to me. 👍

2022-10-07 12:28 UTC, tausbn commented on ql/ql/src/queries/performance/TransitiveStep.ql
> +  "is transively closed"
```suggestion
select tc, "This recursive delta is $@, which may be a performance problem.", reason,
  "transitively closed"
```
Typo (and moved the "is" outside of the link).

2022-10-07 12:28 UTC, tausbn commented on ql/ql/src/queries/performance/UnusedField.ql
> +  field, "field " + field.getName(), implClz, implClz.getName()
```suggestion
select clz, "This class declares the $@ but does not bind it in the characteristic predicate" + extraMsg,
  field, "field " + field.getName(), implClz, implClz.getName()
```
Reformulated to read a bit better (to me at least).

2022-10-07 12:28 UTC, tausbn commented on ql/ql/src/queries/style/AlertMessage.ql
> +  result.getValue().regexpMatch("(a|an) .*")
😱

2022-10-07 12:28 UTC, tausbn commented on ql/ql/src/queries/style/DeadCode.ql
> +select node, "Code is dead."
While I appreciate the nihilism expressed by this statement, perhaps "This code is never used." would be more in line with our other alert messages.

2022-10-07 12:30 UTC, erik-krogh commented on ql/ql/src/queries/style/AlertMessage.ql
> +  result.getValue().regexpMatch("(a|an) .*")
Agreed.

2022-10-11 11:32 UTC, tausbn approved these changes

2022-10-11 11:43 UTC, merged