Type tracking: Split up `levelStep` into `levelStepNoCall` and `levelStepNoCall`
github/codeql pull request #10758
Opened 2022-10-10 17:52 UTC by hvitved

To reduce non-linear recursion during call graph construction, like we already have `flowStepCall` and `flowStepNoCall`.

2022-10-10 19:56 UTC, tausbn requested changes
Looks good to me. One minor suggestion.

2022-10-10 19:56 UTC, tausbn commented on python/ql/lib/semmle/python/dataflow/new/internal/TypeTrackerSpecific.qll
> +predicate levelStepCall(Node pred, Node succ) { none() }
```suggestion
predicate levelStepCall(Node nodeFrom, Node nodeTo) { none() }
```
For consistency.

2022-10-11 11:59 UTC, hvitved commented
Rebased to resolve merge conflict.

2022-10-12 08:40 UTC, asgerf approved these changes
Also LGTM

2022-10-12 08:42 UTC, merged