qlpacks: libraryPathDependencies -> dependencies
github/codeql pull request #10964
Opened 2022-10-25 09:33 UTC by smowton

This is an initial stab at just removing all references to the deprecated key. I note though that a bunch of these files are named `legacy-xyz` -- I don't know what these are doing or if they have a reason to use the deprecated key (compatibility with an old `codeql`?)

2022-10-25 09:36 UTC, RasmusWL approved these changes
awesome, thanks :muscle:

2022-10-25 10:17 UTC, erik-krogh commented
QL-for-QL fails to build because the version of the shared `typos` pack was bumped, but the version specified in `ql/ql/src/qlpack.yml` wasn't bumped.   
We should somehow ensure that those are kept in sync, but for now you can manually bump the version.

2022-10-28 15:20 UTC, aeisenberg reviewed
Certainly all new packs and tests should be using the new syntax. 

I'm hesitant to change any of the `legacy-support` packs (until I learn more about what they are). I would also like to retain at least one test for legacy syntax.

2022-10-28 15:35 UTC, dbartol requested changes
Please revert all of the changes to the `legacy-support` packs as discussed in Slack.

Also, I'm assuming that the rest of these dependencies are all to packs in the same repo? If so, then all of the `'*'` version ranges should be replaced with `${workspace}`, which means "whatever version is currently in the same repo". It's not particularly important for query packs, but for library packs that we might eventually publish, it ensures that other consumers of that library pack actually get a compatible version of that dependency.

2022-10-28 15:51 UTC, smowton commented
Legacy packs reverted; left `*` alone for now since this is also in use all over the repo, so I'd suggest following up with a different PR rather than broaden this one's scope

2022-10-28 15:58 UTC, dbartol approved these changes
LGTM

2022-10-28 16:12 UTC, aeisenberg approved these changes
Nice.

2022-10-28 20:44 UTC, merged