Python: Add failing ESSA use-use test
github/codeql pull request #10998
Opened 2022-10-26 15:51 UTC by RasmusWL

I initially created this as a dataflow test, but then realized it could just be an ESSA test. I couldn't find any existing ESSA tests though :| so created a new dir for it.

@yoff let me know if you think this should actually be under our dataflow tests, since the adjacent use-use was only added to serve the new dataflow lib.

2022-10-26 16:05 UTC, tausbn submitted a review, later dismissed
I think this looks reasonable (but I'll hold off on merging so yoff can have a gander). 👍

2022-10-28 13:30 UTC, yoff requested changes
Super nice to have this test! 👍 
Only reason I mention changes is that it looks different from the code in data flow and I had to remind myself that it does the same thing.

I think it is fine to keep the test here by the predicates they test.

2022-10-28 13:30 UTC, yoff commented on python/ql/test/library-tests/essa/ssa-compute/UseUse.ql
> +            prevLoc = var.getDefinition().getLocation() and
There is a convenience predicate for this (and also: `getDefinition()` simply returns `this`)
```suggestion
            prevLoc = var.getLocation() and
```

2022-10-28 13:30 UTC, yoff commented on python/ql/test/library-tests/essa/ssa-compute/UseUse.ql
> +        location = var.getDefinition().getLocation() and
```suggestion
        location = var.getLocation() and
```
same as above

2022-10-28 13:33 UTC, yoff approved these changes
LGTM

2022-10-31 09:38 UTC, merged