Use `any()` to stub getCallbackParameter/ReturnType
github/codeql pull request #11125
Opened 2022-11-04 13:20 UTC by smowton

This is used in all other languages not currently using dataflow type pruning.

2022-11-04 13:25 UTC, aschackmull approved these changes
I assume `DataFlowType` is singleton? If so, this LGTM.

2022-11-04 13:36 UTC, smowton commented
It is not: `class DataFlowType = Type;` -- whereas I note other languages use a singleton that don't do type pruning.

2022-11-07 09:15 UTC, aschackmull requested changes
Then this change won't work - you're introducing huge cartesian products by assigning _all_ types to synthesised nodes related to callbacks.

2022-11-07 10:05 UTC, smowton commented
ok, I hadn't looked in detail -- assumed because other languages were stubbing using `any()` it must be e.g. a type-pruning filter. I'll take a look at whether we should use a singleton `DataFlowType` if we're not providing type pruning at all.

2022-12-19 19:34 UTC, smowton commented
Replaced by https://github.com/github/codeql/pull/11706

2022-12-19 19:34 UTC, closed without merging