python: port `py/comparison-using-is`
github/codeql pull request #11515
Opened 2022-12-01 08:57 UTC by yoff

see triage [here](https://github.com/github/codeql-python-team/issues/628#issuecomment-1328933001)
- no longer try to interpret the class of operands
- simply alert in clear bad cases of uninterned literals
- surprisingly(?), all tests still pass

2022-12-01 21:18 UTC, yoff commented
One comment is that the query is now quite linter-like:
```bash
>>> def ts(x='same'):
...   if x is 'same':
...     return True
...   else:
...     return False
... 
<stdin>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
```
Perhaps we could add some local data flow...

2022-12-07 12:20 UTC, tausbn requested changes
I'm a bit... uneasy about the large difference in modelling between the old and new version of this query. Though if the old query wasn't finding anything useful with that modelling anyway, then I say we can just get rid of it.

In that case, I wonder if we should just go whole hog and deprecate `IsComparisons.qll` (assuming it doesn't benefit any of the other queries in this directory.

2023-01-16 10:08 UTC, calumgrant commented
Could benefit waiting for new call graph.

2023-03-13 10:18 UTC, calumgrant commented
We discussed this and it's fine to merge as is without spending too much time on it.

2023-03-28 07:42 UTC, merged