Python: Clean up version handling
github/codeql pull request #12029
Opened 2023-01-30 17:12 UTC by tausbn

Depends on an internal PR.

---

Probably needs a change note. 🙂

2023-02-10 21:58 UTC, yoff approved these changes
LGTM

2023-02-14 09:43 UTC, RasmusWL submitted a review, later dismissed

2023-02-14 13:33 UTC, RasmusWL requested changes
Seems like we need to move 

```
python/ql/lib/change-notes/released/2023-02-14-python-2-no-longer-supported.md
==>
python/ql/lib/change-notes/2023-02-14-python-2-no-longer-supported.md

`

2023-02-14 13:55 UTC, RasmusWL approved these changes

2023-02-14 15:40 UTC, merged