Add ZipSlip and TarSlip query to ruby
github/codeql pull request #12208
Opened 2023-02-16 11:43 UTC by gregxsunday

This query detects previously undetected RCE in Discourse by uploading malicious ZIP/Tar archives. 

[CVE-2022-36066](https://github.com/discourse/discourse/security/advisories/GHSA-grvh-qcpg-hfmv)

Similarly as with Python's TarSlip query, I consider unarchiving a file as a source and file creation as a sink. I've modelled all 3 libraries used by Discourse (`Gem::Package::TarReader`, `Zip::File` and `Zlib::GzipReader`).

There are two things are I think should be improved here but I simply don't know how to do them as I'm new to CodeQL.

### Flaw 1: Flow in blocks
The flow is followed correctly when the zipfile is returned from a function with a `yield` keyword but when it's inline like this, the flow breaks. I've tried debugging it with partial flow queries but I don't know how to model that.
```rb

Zip::File.open('example.zip') do |zip_file|
  zip_file.each do |entry|
    # Do something with each entry in the zip file
    puts entry.name
  end
end
```

### Flaw 2: Sanitizer
The way the bug was [fixed](https://github.com/discourse/discourse/commit/4302097b3be0d84c5664bd1eb11e680d9aedaebd) in Discourse is by adding a function
```rb
   def is_safe_path_for_extraction?(path, dest_directory)
       File.expand_path(path).start_with?(dest_directory)
     end
```
And calling it with the untrusted path as the first argument. While my predicate `isSanitizer` can detect inline `File.expand_path(path)`, it doesn't catch this case. I probably need to look at more than one node in `isSanitizer` but I don't quite know how to do it.

2023-02-17 10:46 UTC, aibaars commented on ruby/ql/src/queries/security/cwe-022/ZipSlip.qhelp
> +<sample src="examples/zip_slip_bad.py" />
```suggestion
<sample src="examples/zip_slip_bad.rb" />
```

2023-02-17 10:47 UTC, aibaars commented on ruby/ql/src/queries/security/cwe-022/ZipSlip.qhelp
> +<sample src="examples/zip_slip_good.py" />
```suggestion
<sample src="examples/zip_slip_good.rb" />
```

2023-02-17 10:47 UTC, aibaars commented on ruby/ql/src/queries/security/cwe-022/ZipSlip.qhelp
> +</li>
Let's replace this with Ruby references.

2023-02-17 10:56 UTC, aibaars reviewed
Thanks for this pull request. I see you used the Python version of this query as inspiration. There are a couple of Python related bits left in the documentation, let's fix that.

2023-02-17 12:10 UTC, alexrford requested changes
Just some nitpicks, generally LGTM.

Since this is a new query for Ruby, our CI will want a change note. This can be added as a `ruby/ql/src/change-notes/2023-02-17-zipslip-query.md` with contents like:
```md
---
category: newQuery
---
* Added a new query, `rb/zip-slip`, to detect arbitrary file writes during extraction of zip/tar archives.
```

2023-02-17 12:10 UTC, alexrford commented on ruby/ql/lib/codeql/ruby/security/ZipSlipCustomizations.qll
> +module ZipSlip {
Nitpick: I'd prefer if all the non-abstract classes in this module (i.e. anything that `extends Sink/Source/Sanitizer`) were `private` to make it easier to change the implementation without changing the public interface.

2023-02-17 12:51 UTC, gregxsunday commented
Thanks for those suggestions @alexrford and sorry @aibaars for leaving out python references. I think it's better now

2023-02-17 13:08 UTC, aibaars commented
From https://github.com/github/codeql/actions/runs/4203950763/jobs/7293988883
```
...
Formatting ruby/ql/lib/codeql/ruby/security/ZipSlipCustomizations.qll.
ruby/ql/lib/codeql/ruby/security/ZipSlipCustomizations.qll would change by autoformatting.
Formatting ruby/ql/lib/codeql/ruby/security/OverlyLargeRangeQuery.qll.
Formatting ruby/ql/lib/codeql/ruby/security/ServerSideRequestForgeryQuery.qll.
Formatting ruby/ql/lib/codeql/ruby/security/ZipSlipQuery.qll.
ruby/ql/lib/codeql/ruby/security/ZipSlipQuery.qll would change by autoformatting.
...
```

Could you auto-format the files. You can run: `find ruby/ql -type f \( -name "*.qll" -o -name "*.ql" \) -print0 | xargs -0 codeql query format -i` or use "format document" in VScode if you are using the IDE for query development . I recommend enabling "format document on save" in VSCode.

2023-02-20 15:29 UTC, aibaars requested changes

2023-02-20 15:29 UTC, aibaars commented on ruby/ql/lib/codeql/ruby/security/ZipSlipCustomizations.qll
> +  private class ZipFileOpen extends Source {
The following project resulted in some strange looking results:
https://gist.github.com/aibaars/9f25acb1dcc81b4731d9781b955d3ddd

I think you need to model the case where the `Zip::File.open` method is called with a block differently from the case where it is called without block;  `Zip::File.open(path) do |file| ... end` and `file = Zip::File.open(path)` are different.

2023-02-20 15:32 UTC, aibaars commented
@gregxsunday Could you also move the query and its support files to the `experimental` folder? The query is pretty good as-is, but for new queries we like to do some fine-tuning.

2023-02-20 15:44 UTC, aibaars commented
@gregxsunday These are the results of the query on the latest version of discourse: https://gist.github.com/aibaars/b1456bbab6c13ed6e3192819ad95632d

The results look sensible, but I think the query is not picking up checks like the one in https://github.com/discourse/discourse/blob/1a653d2ce931b76b3b217d9e4f571bcef124d2a9/lib/compression/strategy.rb#LL21C35-L21C35 . If you can teach the query to handle this type of sanitizer that would be great. However, this is not a requirement for the query being accepted.

2023-02-20 16:05 UTC, gregxsunday commented
Hi @aibaars,

I will move it to `experimental` and I will take a look at the results you've sent. 

Regarding handling blocks and the sanitizer, as I wrote in the original PR message, I am aware of those limitations and I had tried to solve them but I simply don't know how to. I'm happy to improve the query if you hint me into the good direction.

2023-02-21 10:43 UTC, aibaars commented
> Regarding handling blocks and the sanitizer, as I wrote in the original PR message, I am aware of those limitations and I had tried to solve them but I simply don't know how to. I'm happy to improve the query if you hint me into the good direction.

Sorry about that, I had forgotten you already mentioned those in the description. Let's add handling blocks, but leave the sanitizer as future work.

I think something like the following should work. We treat the return value as a source if there is no block, and if there is a block then we treat the block's first parameter as a source:

```ql
    ZipFileOpen() {
      exists(API::MethodAccessNode zipOpen |
        zipOpen = API::getTopLevelMember("Zip").getMember("File").getMethod("open") and
        // If argument refers to a string object, then it's a hardcoded path and
        // this file is safe.
        not zipOpen.getParameter(0).asSource().getConstantValue().isStringlikeValue(_)
      |
        not exists(zipOpen.getBlock()) and this = zipOpen.getReturn().asSource()
        or
        this = zipOpen.getBlock().getParameter(0).asSource()
      )
    }
```

2023-02-23 12:21 UTC, gregxsunday commented
- [x] moved to experimental
- [x] added handling blocks to `TarReader` and `Zip` classes. Haven't found `Gzip` to be usable as the block
- [ ] I took a look at the [results](https://gist.github.com/aibaars/9f25acb1dcc81b4731d9781b955d3ddd#file-result-1-roo-rb-roo-md) and it indeed looks strange when the source and the sink are in the same place. The reason for it is that `Zip::File.open` is defined as one of the `FileSystemAccess` sinks in `Archive.qll`. The files in the `roo` repo are responsible for handling ZIP-like excel and office files and I think it's not impossible that there's an archive inside the archive inside those files. It might be hard to exploit but I don't see any obvious error in the query here.

2023-02-28 09:47 UTC, aibaars approved these changes
This looks good to me, thanks!

2023-03-01 09:59 UTC, aibaars commented
> * I took a look at the [results](https://gist.github.com/aibaars/9f25acb1dcc81b4731d9781b955d3ddd#file-result-1-roo-rb-roo-md) and it indeed looks strange when the source and the sink are in the same place. The reason for it is that `Zip::File.open` is defined as one of the `FileSystemAccess` sinks in `Archive.qll`. The files in the `roo` repo are responsible for handling ZIP-like excel and office files and I think it's not impossible that there's an archive inside the archive inside those files. It might be hard to exploit but I don't see any obvious error in the query here.

You're right that there is a potential zip-slip issue in roo-rb/roo. The previous version sort of found the problem, but for the wrong reason. To find the result properly we need a model for `zip.dir.foreach { | filename | ... }` , so the query does not know that there should be taint flow from `zip` to `filename`:

https://github.com/roo-rb/roo/blob/3fecab545b943962213cdf5f0cbe2cdb142940b7/lib/roo/base.rb#L603

If we add a model for the `dir` and `foreach` methods the query finds results with much more sensible flow paths.

@hmac Shall we add modelling the `Zip::File` class and friends to our list of things to model, or is it simple enough to add to this PR?

2023-03-06 09:29 UTC, alexrford approved these changes

2023-03-06 09:40 UTC, aibaars commented
@gregxsunday Thanks a lot for this contribution!

2023-03-06 09:40 UTC, merged