Ruby: Add Server Side Template Injection query
github/codeql pull request #12311
Opened 2023-02-25 14:46 UTC by maikypedia

This pull request adds a query for Server Side Template Injection covering ERB and Slim. 

Looking forward to your suggestions.

2023-02-27 13:08 UTC, intrigus-lgtm commented on ruby/ql/src/queries/security/cwe-094/TemplateInjection.qhelp
> +        <p>Consider the example given below, an untrusted HTTP parameter `name` is used to generate a template string. This can lead to remote code execution. </p>
```suggestion
        <p>Consider the example given below, an untrusted HTTP parameter <code>name</code> is used to generate a template string. This can lead to remote code execution. </p>
```

Qhelp files don't use backticks (`) but instead use \<code>\</code>.

2023-02-27 13:08 UTC, intrigus-lgtm commented on ruby/ql/src/queries/security/cwe-094/TemplateInjection.qhelp
> +Portswigger : [Server Side Template Injection](https://portswigger.net/web-security/server-side-template-injection)
```suggestion
Portswigger : <a href="https://portswigger.net/web-security/server-side-template-injection">Server Side Template Injection</a>.
```

Pretty sure qhelp does not support the markdown syntax for links.

2023-03-07 17:14 UTC, alexrford requested changes
Thanks for your contribution! I'm generally happy with the structure of this and appreciate the use of `Concepts.qll`.

We generally request that new queries are added to the `experimental` directory first (https://github.com/github/codeql/blob/main/CONTRIBUTING.md#submitting-a-new-experimental-query) - would you mind moving this query to `ruby/ql/src/experimental/`?

Otherwise I just have some stylistic and naming suggestions.

2023-03-07 17:14 UTC, alexrford commented on ruby/ql/lib/codeql/ruby/frameworks/Erb.qll
> +    DataFlow::Node template;
```suggestion
    private DataFlow::Node template;
```

2023-03-15 17:03 UTC, alexrford requested changes
I'm happy with this, just needs a couple of minor changes before we can merge it:
- There's a merge conflict in `Frameworks.qll` - probably because another import was added to the file
- We need a change note to document the new query. This can be added by creating a new file `ruby/ql/src/change-notes/2023-03-15-ssti-query`, e.g:
```md
---
category: newQuery
---
* Added a new experimental query, `rb/server-side-template-injection`, to detect cases where user input may be embedded into a template's code in an unsafe manner.
```
(feel free to change the wording in this note if you'd like).

2023-03-17 11:32 UTC, alexrford submitted a review, later dismissed

2023-03-20 09:55 UTC, alexrford approved these changes
Thanks for your contribution! Merging now.

2023-03-20 15:26 UTC, merged