Polish diagnostic messages
github/codeql pull request #12523
Opened 2023-03-14 21:57 UTC by henrymercer

This PR makes some improvements to the diagnostic messages for C#, Java, JavaScript, and Ruby to improve clarity, consistency, and fix some diagnostics that weren't parsing.

Review is particularly encouraged on the parts of the autobuilders that I have modified — feel free to pull out particular issues into separate PRs if it's easier to fix it yourself than suggest changes.  There will almost certainly also be things that I've missed — please make further updates either directly to this PR or separately.

Checks on this PR will fail until the corresponding internal PR has been merged.

2023-03-14 22:32 UTC, aibaars commented on ruby/extractor/src/diagnostics.rs
> +                id: format!("rb/{}", id),
The Ruby extractor is actually language agnostic, so having `rb` in this file is not great. I'll refactor this later.

2023-03-14 22:33 UTC, aibaars approved these changes
👍 for Ruby

2023-03-14 22:34 UTC, erik-krogh submitted a review, later dismissed
JS 👍

2023-03-14 22:45 UTC, smowton submitted a review, later dismissed
Java 👍

2023-03-15 00:05 UTC, mbg approved these changes

2023-03-15 08:03 UTC, aibaars requested changes
C# has test failures .

2023-03-15 12:36 UTC, aibaars submitted a review, later dismissed

2023-03-15 12:43 UTC, aibaars reviewed
Some formatting issues need fixing.

2023-03-15 12:43 UTC, aibaars commented on ruby/extractor/src/extractor.rs
>              .diagnostics_writer
```suggestion
        let mut mesg = self.diagnostics_writer.new_entry(
```

2023-03-15 12:43 UTC, aibaars commented on ruby/extractor/src/extractor.rs
> +            .new_entry("parse-error", "Could not process some files due to syntax errors");
```suggestion
            "parse-error",
            "Could not process some files due to syntax errors",
        );
```

2023-03-15 12:43 UTC, aibaars commented on ruby/extractor/src/extractor.rs
> +                        .new_entry("parse-error", "Could not process some files due to syntax errors")
```suggestion
                        .new_entry(
                            "parse-error",
                            "Could not process some files due to syntax errors",
                        )
```

2023-03-15 13:23 UTC, aibaars approved these changes

2023-03-15 15:06 UTC, merged