Javascript: Add new queries for Javascript actions
github/codeql pull request #12781
Opened 2023-04-06 14:06 UTC by R3x

Added 3 Queries, that track flows from - 

1. Action Input to Sinks
2. Action Github Context to Sinks
3. Action Environment to Sinks

2023-04-06 14:14 UTC, R3x commented
@kevinbackhouse @JarLob - I have added the sinks that are of higher priority here. During the analysis - we also marked some lower-priority sinks (things such as `fs.write` etc). Which basically provides primitives such as an arbitrary file write - but not as severe as the ones here. Do you prefer that I add them as well?

2023-04-06 14:21 UTC, kevinbackhouse commented
> @kevinbackhouse @JarLob - I have added the sinks that are of higher priority here. During the analysis - we also marked some lower-priority sinks (things such as `fs.write` etc). Which basically provides primitives such as an arbitrary file write - but not as severe as the ones here. Do you prefer that I add them as well?

I think it's better to start with just the high-priority ones, so that you have a lower false-positive rate.

2023-04-21 16:56 UTC, JarLob requested changes
Reformatting of the added lines may be needed.

2023-04-21 16:56 UTC, JarLob commented on javascript/ql/src/experimental/Security/CWE-094/ActionsContextToSink.ql
> +  result = payloadObject("review_comment", "body")
```suggestion
  result = payloadObject("comment", "body")
```
I think the correct payload is `github.event.comment.body`

2023-04-21 16:56 UTC, JarLob commented on javascript/ql/src/experimental/Security/CWE-094/ActionsContextToSink.ql
> +  result = payloadObject("pull_request", "head").getAPropertyRead("label") or
```suggestion
  result = payloadObject("pull_request", "head").getAPropertyRead("label") or
  result = payloadObject("pull_request", "head").getAPropertyRead("repo").getAPropertyRead("default_branch") or
  result = payloadObject("pull_request", "head").getAPropertyRead("repo").getAPropertyRead("description") or
  result = payloadObject("pull_request", "head").getAPropertyRead("repo").getAPropertyRead("homepage") or
```

2023-04-21 16:56 UTC, JarLob commented on javascript/ql/src/experimental/Security/CWE-094/ActionsContextToSink.ql
> +    payloadEvent("commits").getAPropertyRead().getAPropertyRead("author").getAPropertyRead("email")
```suggestion
  result =
    payloadEvent("commits").getAPropertyRead().getAPropertyRead("author").getAPropertyRead("name") or
  result =
    payloadEvent("commits").getAPropertyRead().getAPropertyRead("author").getAPropertyRead("email") or
   result = payloadEvent("commits").getAPropertyRead().getAPropertyRead("committer").getAPropertyRead("name") or
  result = payloadEvent("commits").getAPropertyRead().getAPropertyRead("committer").getAPropertyRead("email")
```

2023-04-21 16:56 UTC, JarLob commented on javascript/ql/src/experimental/Security/CWE-094/ActionsContextToSink.ql
> +  result = payloadObject("head_commit", "author").getAPropertyRead("email") or
```suggestion
  result = payloadObject("head_commit", "author").getAPropertyRead("name") or
  result = payloadObject("head_commit", "author").getAPropertyRead("email") or
  result = payloadObject("head_commit", "committer").getAPropertyRead("name") or
  result = payloadObject("head_commit", "committer").getAPropertyRead("email") or
```

2023-04-21 16:56 UTC, JarLob commented on javascript/ql/src/experimental/Security/CWE-094/ActionsContextToSink.ql
> +        .getAPropertyRead("email") or
```suggestion
  result =
    payloadObject("workflow_run", "head_commit")
        .getAPropertyRead("author")
        .getAPropertyRead("email") or
    result =
    payloadObject("workflow_run", "head_commit")
        .getAPropertyRead("committer")
        .getAPropertyRead("email") or
```

2023-04-21 16:56 UTC, JarLob commented on javascript/ql/src/experimental/Security/CWE-094/ActionsContextToSink.ql
> +    payloadObject("workflow_run", "head_commit").getAPropertyRead("author").getAPropertyRead("name") or
```suggestion
  result =
    payloadObject("workflow_run", "head_commit").getAPropertyRead("author").getAPropertyRead("name") or
    result =
    payloadObject("workflow_run", "head_commit").getAPropertyRead("committer").getAPropertyRead("name") or
```

2023-04-21 16:56 UTC, JarLob commented on javascript/ql/src/experimental/Security/CWE-094/ActionsContextToSink.ql
> +  result = payloadObject("workflow_run", "head_branch") or
```suggestion
  result = payloadObject("workflow_run", "head_branch") or
  result = payloadObject("workflow_run", "display_title") or
  result = payloadObject("workflow_run", "head_repository").getAPropertyRead("description") or
```

2023-04-21 21:48 UTC, JarLob commented on javascript/ql/src/experimental/Security/CWE-094/ActionsContextToSink.ql
> +  result = payloadObject("comment", "body")
```suggestion
  result = payloadObject("review", "body")
```
Sorry, my previous suggestion actually introduced the duplicate.

2023-05-01 09:37 UTC, asgerf commented
Hi @R3x and @JarLob 👋 

First of all, sorry for the long radio silence.

These models seem very valuable, and I'd like to get them into the mainline outside experimental. However, I foresee some issues with code duplication, since this PR adds new variants of existing queries containing sinks we already have models for. It's difficult for us to maintain code with such duplication. Rather than merging to experimental and then do a round of clean-up afterwards, I've opened a PR adding the new sources as well as `@actions/exec` to mainline.

I haven't ported the "Actions Environment to Sink" query as I'm still not quite sure what the threat model is, but I'm thinking it could be part of `js/shell-command-injection-from-environment`

2023-05-03 18:25 UTC, R3x commented
Closing this. since we have #12978

2023-05-03 18:25 UTC, closed without merging