Ruby: port `py/weak-sensitive-data-hashing`
github/codeql pull request #12782
Opened 2023-04-06 15:40 UTC by alexrford

2023-04-11 10:55 UTC, hvitved requested changes

2023-04-11 10:55 UTC, hvitved commented on ruby/ql/lib/codeql/ruby/security/WeakSensitiveDataHashingQuery.qll
> +  class Configuration extends TaintTracking::Configuration {
May as well use the new API for this.

2023-04-11 10:55 UTC, hvitved commented on ruby/ql/lib/codeql/ruby/security/WeakSensitiveDataHashingQuery.qll
> +  class Configuration extends TaintTracking::Configuration {
Same.

2023-04-13 19:12 UTC, hvitved commented on ruby/ql/lib/codeql/ruby/security/WeakSensitiveDataHashingQuery.qll
> +    DataFlow::MergePathGraph<NormalHashFunction::PathNode, ComputationallyExpensiveHashFunction::PathNode, NormalHashFunction::PathGraph, ComputationallyExpensiveHashFunction::PathGraph>;
Nice!

2023-04-24 08:42 UTC, alexrford commented
Performance is a bit borderline - looking into removing IDs as sources both to reduce FPs and potentially improve performance.

2024-06-19 11:39 UTC, alexrford commented
Replaced by https://github.com/github/codeql/pull/16781

2024-06-19 11:39 UTC, closed without merging