Swift: replace assertions and direct prints with proper logging
github/codeql pull request #12860
Opened 2023-04-18 10:18 UTC by redsun82

2023-04-18 15:09 UTC, AlexDenisov submitted a review, later dismissed
LGTM, could you start DCA?

2023-04-18 15:49 UTC, sashabu requested changes

2023-04-18 16:13 UTC, redsun82 commented on misc/codegen/templates/cpp_classes_h.mustache
> +    {{>cpp_for_each_label_body}}
yes:
* the non const overload is used in the dispatcher (which covers most of the emissions), where we iterate over labels and actually replace undefined ones with proper `@unspecified_element` DB entries, so we need the label fields to be mutable
* the const overload is used to log all other unspecified entry emissions, which happen here and there (location extractor and invocation extractor as far as I can tell). No change to the labels are done there

2023-04-18 16:14 UTC, sashabu approved these changes

2023-04-24 07:35 UTC, AlexDenisov commented on swift/extractor/SwiftExtractor.cpp
> +  CODEQL_ASSERT(!ec, "Cannot create {} directory ({})", label, ec);
This should not be an assertion, in case two processes try to archive the file, one of them fails, which is fine.

2023-04-24 07:36 UTC, AlexDenisov commented on swift/extractor/SwiftExtractor.cpp
> +  CODEQL_ASSERT(!ec, "Cannot archive source file {} -> {} ({})", source, destination, ec);
This should not be an assertion, in case two processes try to archive the file, one of them fails, which is fine.

2023-04-24 10:10 UTC, AlexDenisov commented on swift/extractor/SwiftExtractor.cpp
> +  if (!ec) {
Should be `ec` instead of `!ec` 😄

2023-05-03 11:55 UTC, redsun82 commented on swift/extractor/infra/SwiftDispatcher.h
on line 292 the TODO for an error or warning emission should be solved

2023-05-03 12:43 UTC, redsun82 commented on swift/extractor/SwiftExtractor.cpp
> +  if (!ec) {
d'oh :laughing:

2023-05-04 08:25 UTC, merged