python: Add tests for container steps
github/codeql pull request #13113
Opened 2023-05-10 14:41 UTC by yoff

Will take out of draft once somewhat complete

2023-05-11 14:53 UTC, RasmusWL requested changes
(I should have requested changes before :shrug:)

2023-05-12 10:53 UTC, yoff commented on python/ql/test/experimental/dataflow/coverage/test_builtins.py
> +    SINK(v1) #$ flow="SOURCE, l:-4 -> v1"
Good catch, I meant for this to be -1 like your suggestion below, but making it more explicit by changing the key is a good idea. Also nice to document the spurious flow.

2023-05-12 10:58 UTC, yoff commented on python/ql/test/experimental/dataflow/tainttracking/defaultAdditionalTaintStep/test_collections.py
> +        [tainted_list for _i in [1,2,3]], # $ MISSING: tainted
Perhaps we should have also `[TAINTED_STRING for i in [1]]` as a more direct example.

2023-05-12 10:59 UTC, yoff commented on python/ql/test/experimental/dataflow/tainttracking/defaultAdditionalTaintStep/test_collections.py
> +        [tainted_list for _i in [1,2,3]], # $ MISSING: tainted
```suggestion
        [tainted_list for _i in [1,2,3]], # $ MISSING: tainted
        [TAINTED_STRING for i in [1]], # $ MISSING: tainted
```

2023-05-12 12:30 UTC, yoff commented
Slightly optimistic with the re-request, there 😅 Should be good now 🤞

2023-05-15 09:07 UTC, RasmusWL approved these changes

2023-05-15 09:07 UTC, merged