Ruby: Add LDAP Injection query #12311
github/codeql pull request #13309
Opened 2023-05-28 15:44 UTC by maikypedia

This pull request adds a query for LDAP Injection covering [net-ldap](https://rubygems.org/gems/net-ldap).

Looking forward to your suggestions.

2023-06-21 13:32 UTC, alexrford requested changes
Thanks for the query! I'm overall happy with this, just some minor requests.

2023-06-21 13:32 UTC, alexrford commented on ruby/ql/lib/codeql/ruby/security/LdapInjectionCustomizations.qll
> +        filterCall.getMethodName() = ["[]"]
I guess that this is for the `attributes` keyword arg in a case like: 
```rb 
ldap.search(base: "ou=people,dc=example,dc=com", filter: "cn=George", attributes: [name])
```
where we want to consider that a tainted element taints the whole array?

If so, we should maybe rename this predicate as `attributeArrayTaintStep` and make it such that it propagates flow from any indexed argument (`getArgument(_)`). It's also worth adding a line of documenting why we need this flow step.

2023-06-21 13:32 UTC, alexrford commented on ruby/ql/lib/codeql/ruby/security/LdapInjectionCustomizations.qll
> +    StringConstArrayInclusionCallBarrier { }
Perhaps also add https://www.rubydoc.info/gems/net-ldap/Net/LDAP/Filter#escape-class_method as a sanitizer?

2023-06-21 13:32 UTC, alexrford commented on ruby/ql/lib/codeql/ruby/security/LdapInjectionQuery.qll
> +class Configuration extends TaintTracking::Configuration {
Would you mind converting this to a `DataFlow::ConfigSig` as in https://github.com/github/codeql/pull/13130/files#diff-cb35acf3aed06823bd9b005af3d73697a4cb92867d123eb7b868f9b6143c4082 (using `isBarrier` and `isAdditionalFlowStep` in place of `isSanitizer` and `isAdditionalTaintStep` respectively).

2023-07-11 10:58 UTC, alexrford requested changes
These changes should fix the deprecation warnings.

2023-07-11 10:58 UTC, alexrford commented on ruby/ql/lib/codeql/ruby/security/LdapInjectionQuery.qll
> +  import TaintTracking::Make<Config>
```suggestion
  import TaintTracking::Global<Config>
```

2023-07-11 10:58 UTC, alexrford commented on ruby/ql/src/experimental/ldap-injection/LdapInjection.ql
> +where LdapInjection::hasFlowPath(source, sink)
```suggestion
where LdapInjection::flowPath(source, sink)
```

2023-07-24 13:53 UTC, alexrford commented
Hey @maikypedia, sorry for the delay on this PR. I had another look through this PR and there are a few comments from my initial review that got lost in the changes. Would you mind looking through the comments in that review again?

2023-07-27 21:42 UTC, maikypedia commented
> Hey @maikypedia, sorry for the delay on this PR. I had another look through this PR and there are a few comments from my initial review that got lost in the changes. Would you mind looking through the comments in that review again?

Sorry, I completely overlooked it 😅. I think with this, everything should be ready now. Is there anything I might be missing?

2023-08-01 09:44 UTC, alexrford approved these changes

2023-08-01 09:44 UTC, merged