Go: Add Improper LDAP Authentication query (CWE-287)
github/codeql pull request #13366
Opened 2023-06-04 23:32 UTC by maikypedia

This pull request adds a query for Improper LDAP Authentication to prevent attackers use an empty password. I am not very familiar with CodeQL Go, and I have been struggling to generate correct expected files 🙃.

Looking forward to your suggestions.

2023-06-21 09:24 UTC, mbg commented
Hi @maikypedia, thank you for opening this pull request!

Looking at [the documentation for `Bind`](https://pkg.go.dev/github.com/go-ldap/ldap/v3#Conn.Bind), it seems that an empty password is not accepted by that method. Would it be correct in saying that this vulnerability cannot be exploited if that is the case?

2023-07-05 14:17 UTC, maikypedia commented
> Hi @maikypedia, thank you for opening this pull request!
> 
> Looking at [the documentation for `Bind`](https://pkg.go.dev/github.com/go-ldap/ldap/v3#Conn.Bind), it seems that an empty password is not accepted by that method. Would it be correct in saying that this vulnerability cannot be exploited if that is the case?

Hi @mbg , I didn't realize that in v3 empty password option with Bind is disabled, sorry for the inconvenience 😅

2023-07-05 18:44 UTC, maikypedia commented
Would it be worth adding `Bind` as sink for v2 and `UnauthenticatedBind` for v3? As a warning query.

2023-08-25 19:42 UTC, maikypedia commented
ping @mbg

2023-08-25 20:40 UTC, mbg commented
Hi @maikypedia, sorry, I must have missed your question. Thank you for pinging me to bring this to my attention.

For `Bind` in v2, the query does make sense so it could be worth adding and I would be happy to review that.

For `UnauthenticatedBind`, I am not sure it makes sense to add a query to detect its use. The name of the method already notes that it is unauthenticated so using it would have to be deliberate and intentional.

2023-10-11 11:10 UTC, owen-mc requested changes
Your test isn't giving any results - it should be finding the bad cases. You may need to make sure that the test file builds correctly (try running `go build` in the directory that it is in to see what the errors are).

2023-10-11 11:10 UTC, owen-mc commented on go/ql/test/experimental/CWE-287/ImproperLdapAuth.go
> +	bad2(nil, nil)
```suggestion
	bad2(nil)
```

2023-10-11 11:10 UTC, owen-mc commented on go/ql/test/experimental/CWE-287/ImproperLdapAuth.go
> +func bad(w http.ResponseWriter, req *http.Request) (interface{}, error) {
This function is missing a return statement. And the next two functions.

2023-10-11 11:10 UTC, owen-mc commented on go/ql/src/experimental/CWE-287/ImproperLdapAuth.qll
> +      base = ["Bind"] and m = base
```suggestion
    exists(Method meth |
      meth.hasQualifiedName("gopkg.in/ldap.v2", "Conn", "Bind") and
      this = meth.getACall().getArgument(1)
```

2023-10-17 09:01 UTC, owen-mc commented
> The following files need to be reformatted using gofmt or have compilation errors:
> Error: ./ql/src/experimental/CWE-287/examples/LdapAuthGood.go:1:1: expected 'package', found 'func'
> Error: make: *** [Makefile:35: check-formatting] Error 1
> Error: ./ql/src/experimental/CWE-287/examples/LdapAuthBad.go:1:1: expected 'package', found 'func'

2023-10-25 19:47 UTC, owen-mc requested changes
Well done for generating stubs. You've actually put them in two places by mistake - you can remove all changes to `go/vendor` and keep the ones in the test folder. Your tests now generate the right results now, but they will also generate some build errors because of missing return statements. Please address that and the rest of my previous review comments.

2023-10-25 23:18 UTC, maikypedia commented
I don't know if I've forgotten something, I think that's all for now. 😗

2023-10-26 13:31 UTC, owen-mc requested changes
Please don't make any changes to `go/vendor/modules.txt`. Please add a package declaration and imports to make `LdapAuthBad.go` and `LdapAuthGood.go` valid go files.

2023-11-09 22:39 UTC, maikypedia commented
Hi @owen-mc ! Sorry for the delay, I had some exams these weeks 😅 In the example files of other experimental queries they do not include the imports of libraries that are not builtin, should I leave it like that?

2023-11-09 23:43 UTC, owen-mc commented
@maikypedia The reason for making these valid go files is so that `gofmt` can parse them, because it can highlight some syntax errors. It seems to have passed. I see now that imports aren't actually needed, just the package directive. I would leave it as it is.

Your test is failing. It couldn't build the go file. I think there is a missing `go.mod` file.

2023-11-10 00:00 UTC, maikypedia commented
> @maikypedia The reason for making these valid go files is so that `gofmt` can parse them, because it can highlight some syntax errors. It seems to have passed. I see now that imports aren't actually needed, just the package directive. I would leave it as it is.
> 
> Your test is failing. It couldn't build the go file. I think there is a missing `go.mod` file.

Done :), thanks

2023-11-10 13:34 UTC, owen-mc requested changes

2023-11-10 13:34 UTC, owen-mc commented on go/ql/src/experimental/CWE-287/ImproperLdapAuth.qll
> +}
`TaintTracking::Configuration` is deprecated. Please convert this to use the new API for the dataflow library. See [this PR](https://github.com/github/codeql/pull/13820) for lots of examples. It should be a straightforward change, so let me know if you have any problems. The main thing that might trip you up is that you have to use `DataFlow::ConfigSig` and then `TaintTracking::Global`. (And no need to leave a deprecated class extending `TaintTracking::Configuration` around.)

2023-11-12 17:22 UTC, maikypedia commented
Done 😃 👍

2023-11-13 04:41 UTC, owen-mc approved these changes

2023-11-13 14:48 UTC, merged