Ruby: Decompression Bombs
github/codeql pull request #13556
Opened 2023-06-24 15:23 UTC by am0o0

This is part of All for one, one for all query submission, I'm going to submit an issue in github/securitylab for this pull request too.
I wrote two versions which V2 is using recursion by use of API graphs to find zip file sinks. I added V1 because I think it maybe have some advantage in your opinion but I prefer V2. the predicates in V2 can used in ZipSlip query too I can work on this too if you agree.( I couldn't write the recursion predicate without the initial help of @asgerf in #13431)
I added the only sanitizer that I think is available which is checking the size of each zip entry.
Also I added some instance of some really popular additional taint steps which I think it is good to be added as global steps.

2023-06-24 17:52 UTC, smowton commented
Anyone not watching the repo in general, note this is part of a family of submissions:

https://github.com/github/codeql/pull/13553
https://github.com/github/codeql/pull/13554
https://github.com/github/codeql/pull/13555
https://github.com/github/codeql/pull/13556
https://github.com/github/codeql/pull/13557
https://github.com/github/codeql/pull/13558

2023-07-11 12:18 UTC, calumgrant commented
Hey @amammad, would you be able to submit these to the [Security Lab bug bounty program](https://securitylab.github.com/bounties/) using [this template](https://github.com/github/securitylab/issues/new?template=all-for-one.yml) as this will help us prioritise this work, and it would also be really helpful to test the CVEs found as well.

Thank you for your submission!

2023-11-06 13:15 UTC, alexrford requested changes
Hi, I've run an initial review of this. Some of the feedback here may overlap with comments on the versions of this query for other languages.

2024-05-16 12:52 UTC, alexrford approved these changes
Sorry for the delay, approved.

2024-05-16 13:10 UTC, alexrford requested changes
Just a couple of suggestions to make CI pass.

2024-05-16 13:10 UTC, alexrford commented on ruby/ql/src/experimental/CWE-522-DecompressionBombs/DecompressionBombs.qhelp
> +<p>Please read official RubyZip Documentation <a href="https://github.com/rubyzip/rubyzip/#size-validation">here</a></p>
```suggestion
<p>Please read official RubyZip Documentation <a href="https://github.com/rubyzip/rubyzip/#size-validation">here</a></p>
</recommendation>

```

This should fix the qhelp check error.

2024-05-16 13:10 UTC, alexrford commented on ruby/ql/src/experimental/CWE-522-DecompressionBombs/DecompressionBombs.ql
> + * @id rb/user-controlled-file-decompression
```suggestion
 * @id rb/user-controlled-data-decompression
```

For consistency with JS and to address the duplicate query ID check.

2024-05-16 13:10 UTC, alexrford commented on ruby/ql/test/query-tests/experimental/CWE-522-DecompressionBombs/DecompressionBombs.expected
> +edges
This `.expected` file looks like it needs to be regenerated to account for a change in the `edges` relation format.

2024-05-16 15:22 UTC, alexrford approved these changes

2024-05-16 15:23 UTC, merged