JS: decoding JWT without signature verification
github/codeql pull request #14088
Opened 2023-08-29 11:24 UTC by am0o0

2023-10-19 07:39 UTC, JarLob commented
No-verification query should be under CWE-347.

2023-11-06 18:43 UTC, JarLob commented on javascript/ql/src/Security/CWE-347-noVerification/JsonWebToken.ql
Hello @amammad, the current query doesn't detect CVE-2023-22893. You wrote `IDK why this issue so I decided to create a PR and ask help from codeql engineers.` Do you mean this, #14088, PR?

From what I see there is no flow from the remote source to the sink, i.e. simple query like below returns nothing:
```ql
 class Configuration extends TaintTracking::Configuration {
   Configuration() { this = "jsonwebtoken constant secret key" }
 
   override predicate isSource(DataFlow::Node source) { source instanceof RemoteFlowSource }
 
   override predicate isSink(DataFlow::Node sink) {
     sink = unverifiedDecode()
   }
 }

from Configuration cfg, DataFlow::PathNode source, DataFlow::PathNode sink
where cfg.hasFlowPath(source, sink)
select source.getNode(), source, sink, "Decoding JWT $@.", sink.getNode(),
   "without signature verification"
```

My first thought was the taint path breaks at some point, so I run this config which finds all possible paths:
```ql
   override predicate isSource(DataFlow::Node source) { source instanceof RemoteFlowSource }
 
   override predicate isSink(DataFlow::Node sink) {
     any()
   }
```

However this is not the case. Manually recreating the call stack of the decode function is this:
[handler: 'auth.callback',](https://github.com/strapi/strapi/blob/d36609ff26fb4e00a41a7e2b657f16c7466203fe/packages/plugins/users-permissions/server/routes/content-api/auth.js#L34)
[const user = await getService('providers').connect(provider, ctx.query);](https://github.com/strapi/strapi/blob/d36609ff26fb4e00a41a7e2b657f16c7466203fe/packages/plugins/users-permissions/server/controllers/auth.js#L97)
[const profile = await getProfile(provider, query);](https://github.com/strapi/strapi/blob/d36609ff26fb4e00a41a7e2b657f16c7466203fe/packages/plugins/users-permissions/server/services/providers.js#L54)
[return getService('providers-registry').run](https://github.com/strapi/strapi/blob/d36609ff26fb4e00a41a7e2b657f16c7466203fe/packages/plugins/users-permissions/server/services/providers.js#L28)
[async run({ provider, accessToken, query, providers }) ](https://github.com/strapi/strapi/blob/d36609ff26fb4e00a41a7e2b657f16c7466203fe/packages/plugins/users-permissions/server/services/providers-registry.js#L282)
[const tokenPayload = jwt.decode(idToken);](https://github.com/strapi/strapi/blob/d36609ff26fb4e00a41a7e2b657f16c7466203fe/packages/plugins/users-permissions/server/services/providers-registry.js#L26)

As you can see the flow starts in `server/routes/content-api/auth.js` but a query below shows that this remote source is unknown for codeql:
```ql
from RemoteFlowSource source
select source, source.getFile().getBaseName()
```

One option is to model these routes as remote sources, but since there is a dynamic registration and call by string in the stack it still may require few more tweaks to correctly track the taint until the sink. This path though is more interesting if you would like to search for other vulnerabilities in strapi, because once you have sources correctly modeled all existing javascript queries may found something.
The other option is to stick to the first version of your query, but track the decoded payload if it is actually used.

2023-11-06 19:14 UTC, JarLob commented on javascript/ql/src/Security/CWE-347-noVerification/JsonWebToken.ql
There should no issues using several configs like below. If you can provide an example of query that doesn't work maybe somebody can point what is wrong with it.
```
from ConfigA cfg1, ConfigB cfg2, Node src1, Node src2, Node sink1, Node sink2
where cfg1.HasPath(src1, sink1) and cfg2.HasPath(src2, sink2) and sink1=src2
select ...
```

2023-11-07 12:11 UTC, JarLob commented on javascript/ql/src/Security/CWE-347-noVerification/JsonWebToken.ql
You don't use `cfgSafe` in the example above. Are you sure it is a valid example?

2023-11-07 12:54 UTC, JarLob commented on javascript/ql/src/Security/CWE-347-noVerification/JsonWebToken.ql
So is there an issue using multiple taint configs or not?

2023-11-08 13:32 UTC, JarLob commented on javascript/ql/src/Security/CWE-347-noVerification/JsonWebToken.ql
Could you please copy/paste the config query that @asgerf said JS doesn't support? I think @asgerf knows CodeQL better than me 😄 but I would like to understand the problem better. Also documenting it here makes sense I think.

2023-11-08 13:34 UTC, JarLob commented on javascript/ql/src/Security/CWE-347-noVerification/JsonWebToken.ql
> Do you agree if I use RemoteFlowSource as Source?

I'll discuss it with the team.

2023-11-08 14:07 UTC, JarLob commented on javascript/ql/src/Security/CWE-347-noVerification/JsonWebToken.ql
I mean when I asked for example of two configs that doesn't work and which was acknowledge by @asgerf as not supported by CodeQL for JS you provided https://github.com/github/codeql/pull/14088#discussion_r1384429989 I have noticed that you only declare, but do not use `ConfigurationSafe cfgSafe`. You have replied that you just forgot to delete it.
Could you please provide the example what exactly doesn't work with two taint configs in CodeQL for JS for the reference?

2024-05-13 15:06 UTC, JarLob requested changes

2024-05-13 15:06 UTC, JarLob commented on javascript/ql/src/Security/CWE-347-noVerification/JsonWebTokenNotWorking.ql
Imho this also can be deleted in favor of JsonWebTokenLocalSource.ql. But I'll let someone JavaScript CodeQL team to take a look if it can be fixed.

2024-05-13 15:06 UTC, JarLob commented on javascript/ql/test/query-tests/Security/CWE-347-noVerification/JsonWebTokenNotWorking.expected
As I understand JsonWebToken.ql and JsonWebTokenNotWorking.ql can be deleted in favor of JsonWebTokenLocalSource.ql. These tests need to be properly renamed/deleted.

2024-05-13 15:08 UTC, JarLob commented
@am0o0 Could you please change the pull request from draft to ready for review, so someone from JavaScript CodeQL team can take a look?

2024-05-21 17:10 UTC, erik-krogh commented
First you need to move everything into the `experimental/` folders.   

I'll do a review after you've done that.

2024-05-23 05:35 UTC, erik-krogh reviewed
A first review round.  

Primarily: you shouldn't add one new query for each library you're adding a model for, you should just have one query that models all the libraries.

2024-05-23 05:35 UTC, erik-krogh commented on javascript/ql/src/experimental/Security/CWE-347-noVerification/jwtNoVerification.qhelp
> +<!DOCTYPE qhelp PUBLIC "-//Semmle//qhelp//EN" "qhelp.dtd">
`.qhelp` files are supposed to have the same basename as a `.ql`.  
So for this `.qhelp` file we would expect to find a corresponding `jwtNoVerification.ql` file. 

You need one `.qhelp` file pr. `.ql` fille, but you can use `.inc.qhelp` files to make reusable snippets.

2024-05-23 05:35 UTC, erik-krogh commented on javascript/ql/src/experimental/Security/CWE-347-noVerification/JsonWebToken.ql
> + * @id js/jwt-missing-verification-jsonwebtoken
You're using `js/jwt-missing-verification-jsonwebtoken` in 3 different `.ql` files. 
Each `.ql` file should have a unique `@id`.

2024-05-23 05:35 UTC, erik-krogh commented on javascript/ql/src/experimental/Security/CWE-347-noVerification/JsonWebToken.ql
> +DataFlow::Node unverifiedDecode() {
You've copy-pasted some of this code throughout multiple files.  
You can move those predicates to a `.qll` file that you then import from multiple `.ql` files.

2024-05-23 05:35 UTC, erik-krogh commented on javascript/ql/src/experimental/Security/CWE-347-noVerification/JsonWebTokenLocalSource.ql
> +          .getALocalSource()
I don't see any examples or tests for this source, so I'm a bit confused what code that this query flags looks like?

2024-05-23 05:35 UTC, erik-krogh commented on javascript/ql/src/experimental/Security/CWE-347-noVerification/JsonWebTokenNotWorking.ql
> + * @name This query is for seeing if we can have two taint config within on query file
This does not look like a file you meant to include? 
This look like code you used for testing.

2024-05-23 05:35 UTC, erik-krogh commented on javascript/ql/src/experimental/Security/CWE-347-noVerification/jose.ql
> +}
Is this just a second source/sink pair describing the same thing that is happening in `JsonWebToken.ql`.  
Why not combine the two into one `.ql` file?

2024-05-23 05:35 UTC, erik-krogh commented on javascript/ql/src/experimental/Security/CWE-347-noVerification/jwtDecode.ql
> +  result = API::moduleImport("jwt-decode").getParameter(0).asSink()
You're flagging all instances where `jwt-decode` is called, independently of whether any verification happens.  
But your query-message specifically says that there is no verification?  

Also, shouldn't this just be another source in your `JsonWebToken.ql` query?

2024-05-23 05:35 UTC, erik-krogh commented on javascript/ql/src/experimental/Security/CWE-347-noVerification/jwtSimple.ql
> + * @name JWT missing secret or public key verification
Again, it would be better to combine this with your existing `JsonWebToken.ql` query, instead of having one query pr. library.

2024-06-04 12:59 UTC, erik-krogh commented on javascript/ql/src/experimental/Security/CWE-347-noVerification/JsonWebTokenNotWorking.ql
> + * @name This query is for seeing if we can have two taint config within on query file
Oh, I think I know why.  
The `DataFlow::PathNode` includes which `DataFlow::Configuration` it came from. 
So you need to check that the `DataFlow::Node` that you get from calling `.getNode()` on the source is the same between the two "sources", you can't use the `DataFlow::PathNode` from one configuration directly in another.

2024-06-04 13:01 UTC, erik-krogh commented
The `decodeJwtWithoutVerification.qlref` and `decodeJwtWithoutVerificationLocalSource.qlref` tests are failing.  
Could you rerun those and update the expected outputs.

2024-06-06 18:31 UTC, erik-krogh commented
> I forgot to update this branch, the tests are still OK. are you sure about failing?

Yeah, they're passing now 🤷 

The `decodeJwtWithoutVerificationDoesNotWork.ql` file still needs to be deleted though.  

I think changing the from-where-select to the below might fix your issue (it's the fix I described further up): 
```CodeQL
from ConfigurationUnverifiedDecode cfg, DataFlow::PathNode source, DataFlow::PathNode sink
where
  cfg.hasFlowPath(source, sink) and
  not exists(ConfigurationVerifiedDecode cfg2 |
    cfg2.hasFlowPath(any(DataFlow::PathNode p | p.getNode() = source.getNode()), _)
  )
select source.getNode(), source, sink, "Decoding JWT $@.", sink.getNode(),
  "without signature verification"
```

If that works you can use the new approach in your queries.

2024-06-20 18:13 UTC, erik-krogh approved these changes

2024-06-20 18:13 UTC, merged

2024-06-20 18:14 UTC, erik-krogh commented
Thanks. Everything looks good for a merge into `experimental/` now 👍 

Thanks again for the contribution.