Java: Automodel App Mode Extraction: Source Candidates
github/codeql pull request #14162
Opened 2023-09-07 13:31 UTC by kaeluka

This adds source candidates to application mode extraction.

I kept the PR as small as I could, but in order for it to be a meaningful step forward - it's certainly not tiny.
The commits are quite small individually, this may help the reviewer.

 - There's two kinds of source candidates that this adds support for:
   - the `ReturnValue` of a call,
   - a parameter of an overridden method.

 - There's test cases that should illustrate the expected behaviour.

 - In order for the change to make sense, I had to refactor the interface of the endpoint class a bit. For instance, the `isArgOf` predicate does not makes sense for the new endpoints.

 - One additional change that was requested is to export the type of model the candidate is for as meta data. The metadata property is `"extensibleKind"` and the value can be either `sinkModel` or `sourceModel` (see test expectations)

2023-09-07 13:50 UTC, kaeluka commented on java/ql/automodel/src/AutomodelApplicationModeCharacteristics.qll
> +      else none() // if both exist, it would be a summaryModel (not yet supported)
I think this is clearer because it's an intentional location for future extension.

2023-09-08 07:28 UTC, kaeluka commented on java/ql/automodel/src/AutomodelFrameworkModeCharacteristics.qll
> +    none() // TODO: implement
todo in a follow-up PR

2023-09-08 09:52 UTC, tausbn requested changes
A few comments, but otherwise I think this looks really good! ❤️

2023-09-08 11:54 UTC, kaeluka commented on java/ql/automodel/src/AutomodelApplicationModeCharacteristics.qll
> +    // XXX consider source candidate endpoints
thank you! :)

2023-09-08 11:57 UTC, kaeluka commented on java/ql/automodel/src/AutomodelApplicationModeCharacteristics.qll
> +  TMethodCall(Call call) { not call instanceof ConstructorCall } or
that's a good idea! [bbedd72](https://github.com/github/codeql/pull/14162/commits/bbedd72260a654deb715163d2acf6726d0609fec)

2023-09-08 11:59 UTC, kaeluka commented
Thank you for the review! I have accepted your comments :-)

2023-09-08 12:12 UTC, tausbn approved these changes
:shipit:

2023-09-08 13:43 UTC, merged