C#: Quoting hotfix.
github/codeql pull request #14177
Opened 2023-09-11 06:43 UTC by michaelnebel

2023-09-11 07:13 UTC, tamasvajk submitted a review, later dismissed

2023-09-11 14:30 UTC, dbartol requested changes
Before we merge this into a hotfix for 2.14.4, I'd like answers to two questions:

1. What is the customer impact of waiting until 2.14.5 for this fix?
2. Since this fix does not fully implement the quoting rules for Windows command lines, I could use some convincing that this fix is strictly better than the original code that completely ignores quoting. I _think_ it's strictly better, because any argument with a space would definitely be broken before.

2023-09-11 14:53 UTC, michaelnebel commented
> Before we merge this into a hotfix for 2.14.4, I'd like answers to two questions:
> 
> 1. What is the customer impact of waiting until 2.14.5 for this fix?
> 2. Since this fix does not fully implement the quoting rules for Windows command lines, I could use some convincing that this fix is strictly better than the original code that completely ignores quoting. I _think_ it's strictly better, because any argument with a space would definitely be broken before.

Thank you for the questions @dbartol !
1. They might have over 2k repos with this issue and just the primitive quoting might fix many of these, which sounds to be blocking issue. However, you have a valid point that this is NOT a regression, which argues against doing this as a hotfix (we haven't broken anything that worked before).
2. That is my understanding as well. We don't change anything, if an argument doesn't contain a whitespace. That is, we don't break anything that currently works. However, since the primitive quoting is not *ideal* we might still produce garbage is some cases, but then it will be garbage in and garbage out.

2023-09-12 08:31 UTC, closed without merging

2023-09-12 08:38 UTC, michaelnebel commented
Sorry for the mass ping...