C#: Minor improvements to the ExternalApi implementation.
github/codeql pull request #14272
Opened 2023-09-20 12:34 UTC by michaelnebel

2023-09-21 07:40 UTC, michaelnebel commented
DCA looks good.

2023-09-25 09:26 UTC, hvitved requested changes

2023-09-25 09:26 UTC, hvitved commented on csharp/ql/src/Telemetry/ExternalApi.qll
> -      Call c, DataFlowDispatch::NonDelegateDataFlowCall dc, DataFlowImplCommon::ReturnKindExt ret
Looks like the `DataFlowImplCommon` import can be removed now.

2023-09-25 13:02 UTC, hvitved approved these changes

2023-09-25 14:35 UTC, merged