Minor fixes for dataflow queries
github/codeql pull request #14274
Opened 2023-09-20 14:31 UTC by alexrford

Follow up to https://github.com/github/codeql/pull/14124 to address some issues:
 - `rb/improper-ldap-auth` was not converted due to being merged around the same time - this is done here
 - We have a single (unused) import of `DataFlow2`. Ideally we would just be able to remove `DataFlow2`, but it's available for external queries so I think we need to deprecate it first.

2023-09-20 18:10 UTC, hvitved submitted a review, later dismissed
Can we get rid of `DataFlowImplForHttpClientLibraries.qll` and `DataFlowImplForPathname.qll` on this PR as well?

2023-09-21 07:24 UTC, aschackmull requested changes
We shouldn't deprecate DataFlow2 just yet. It's part of the old configuration-class API, which we will bulk-deprecate in December, cf. https://github.blog/changelog/2023-08-14-new-dataflow-api-for-writing-custom-codeql-queries/

2023-09-21 11:32 UTC, aschackmull approved these changes

2023-09-21 13:25 UTC, alexrford commented
> Can we get rid of `DataFlowImplForHttpClientLibraries.qll` and `DataFlowImplForPathname.qll` on this PR as well?

Not sure how I missed these - deleted.

2023-09-21 13:29 UTC, hvitved approved these changes

2023-09-21 15:33 UTC, merged