Ruby: Add Insecure Randomness Query
github/codeql pull request #14554
Opened 2023-10-21 15:28 UTC by maikypedia

This pull request adds a query for Insecure Randomness.

Looking forward to your suggestions.

2023-12-08 09:55 UTC, hmac requested changes
This looks good! I have some minor comments, and I've kicked off a variant analysis run to see what results we get.

2023-12-08 09:55 UTC, hmac commented on ruby/ql/lib/codeql/ruby/security/InsecureRandomnessCustomizations.qll
> + * sensitive action guards, as well as extension points for adding your own.
`about random values that are not cryptographically secure`?

2023-12-08 09:55 UTC, hmac commented on ruby/ql/lib/codeql/ruby/security/InsecureRandomnessCustomizations.qll
> + * sensitive action guards, as well as extension points for adding your own.
ditto

2023-12-08 09:55 UTC, hmac commented on ruby/ql/lib/codeql/ruby/security/InsecureRandomnessCustomizations.qll
> +      this.asExpr().getExpr() instanceof UnknownMethodCall and
If you `import codeql.ruby.frameworks.core.Kernel` then you can just do
```ql
or this.(Kernel::KernelMethodCall).getMethodName() = "rand"
```

2023-12-08 09:55 UTC, hmac commented on ruby/ql/lib/codeql/ruby/security/InsecureRandomnessQuery.qll
> +deprecated class Configuration extends TaintTracking::Configuration {
I don't think there's any need to add a deprecated class. We should remove this.

2024-01-02 13:43 UTC, hmac commented
There are also two code scanning warnings that should be fixed up.

2024-01-09 15:36 UTC, hmac commented
It looks like `ruby/ql/lib/codeql/ruby/security/InsecureRandomnessCustomizations.qll` is not formatted correctly - run `codeql query format` on it to resolve that.

2024-01-09 20:53 UTC, intrigus-lgtm commented on ruby/ql/src/experimental/insecure-randomness/InsecureRandomness.qhelp
> +For Ruby, `SecureRandom` provides a cryptographically secure pseudo-random number generator.
```suggestion
For Ruby, <code>SecureRandom</code> provides a cryptographically secure pseudo-random number generator. 
```

2024-01-09 20:53 UTC, intrigus-lgtm commented on ruby/ql/src/experimental/insecure-randomness/InsecureRandomness.qhelp
> +`rand` is not cryptographically secure, and should be avoided in security contexts.
```suggestion
<code>rand</code> is not cryptographically secure, and should be avoided in security contexts. 
```

2024-01-09 20:53 UTC, intrigus-lgtm commented on ruby/ql/src/experimental/insecure-randomness/InsecureRandomness.qhelp
> +For contexts which are not security sensitive, Random may be preferable as it has a more convenient
```suggestion
For contexts which are not security sensitive, <code>Random</code> may be preferable as it has a more convenient 
```

2024-01-09 20:53 UTC, intrigus-lgtm commented on ruby/ql/src/experimental/insecure-randomness/InsecureRandomness.qhelp
> +<p>The first example uses `Random.rand()` which is not for security purposes</p>
```suggestion
<p>The first example uses <code>Random.rand()</code> which is not for security purposes</p>
```

2024-01-09 20:53 UTC, intrigus-lgtm commented on ruby/ql/src/experimental/insecure-randomness/InsecureRandomness.qhelp
> +<p>In the second example, the password is generated using `SecureRandom.random_bytes` which is a
```suggestion
<p>In the second example, the password is generated using <code>SecureRandom.random_bytes</code> which is a 
```
```suggestion
<p>In the second example, the password is generated using <code>SecureRandom.random_bytes()</code> which is a 
```

2024-01-09 20:53 UTC, intrigus-lgtm commented on ruby/ql/src/experimental/insecure-randomness/InsecureRandomness.qhelp
> +<li>Common Weakness Enumeration: <a href="https://cwe.mitre.org/data/definitions/338.html">CWE-338</a>.</li>
This should be added automatically based on the tags in the `.ql` file I think.

2024-01-31 17:16 UTC, hmac approved these changes

2024-01-31 17:16 UTC, merged