GoFiber: Web Cache Deception Vulnerability
github/codeql pull request #15057
Opened 2023-12-09 16:51 UTC by aydinnyunus

### Pull Request: Add Web Cache Deception Query on GoFiber for CodeQL

#### Overview
This pull request introduces a new CodeQL query to detect potential Web Cache Deception vulnerabilities in web applications. Web Cache Deception is a security vulnerability where attackers trick a server into caching sensitive information, which they can later access. This query aims to identify code patterns that might make an application susceptible to this type of attack.

#### Changes Introduced
- **New Query Added**: `WebCacheDeceptionFiber.ql` - Detects patterns where web applications might cache sensitive information inadvertently.
- **Experimental Code Samples**: Included in the `/examples` directory, demonstrating both vulnerable (bad) and secure (good) coding practices related to caching.
- **Documentation**: Added documentation explaining the query's purpose, usage, and the nature of the vulnerability.

#### Implementation Details
- The query looks for server configurations or code patterns where URLs can be manipulated to cache sensitive information.
- Focuses on common web languages and frameworks where this vulnerability might occur.

#### Testing and Validation
- Query tested against a range of synthetic code samples (included in the PR).
- Validated for false positive rates and performance impact on large codebases.

#### Future Work
- Plan to extend support to additional languages and frameworks.
- Open to community feedback for further refinement and optimization.

#### References
- Link to the OWASP page on Web Cache Deception: [OWASP Web Cache Deception Attack](https://owasp.org/www-community/attacks/Web_Cache_Deception).

2023-12-09 16:58 UTC, aydinnyunus commented
Probably I should not push the "vendor" directory. If you approve it I can remove it.

2023-12-09 21:03 UTC, owen-mc commented
Please use [depstubber](https://github.com/github/depstubber) to create just the stubs that are needed and put those in the vendor directory.

2023-12-09 22:25 UTC, aydinnyunus commented
Updated @owen-mc

2023-12-10 19:19 UTC, aydinnyunus commented on go/ql/src/experimental/CWE-525/WebCacheDeceptionFiber.ql
> +  httpHandleFuncCall.getCall().getArgument(0).toString().matches("%/*%") and
`getStringValue` does not works for me, so I use `toString`

2023-12-10 19:20 UTC, aydinnyunus commented on go/ql/src/experimental/CWE-525/WebCacheDeceptionFiber.ql
> +  not httpHandleFuncCall.getCall().getArgument(0).toString().matches("%$%") and
`getStringValue` does not works for me, so I use `toString`

2023-12-10 19:21 UTC, aydinnyunus commented
fixed the qhelp issue and tests.

2023-12-10 19:23 UTC, aydinnyunus commented on go/ql/src/experimental/CWE-525/WebCacheDeceptionGoChi.ql
> +  httpHandleFuncCall.getCall().getArgument(0).toString().matches("%/*%") and
`getStringValue` does not works for me, so I use `toString`

2023-12-10 19:23 UTC, aydinnyunus commented on go/ql/src/experimental/CWE-525/WebCacheDeceptionGoChi.ql
> +  not httpHandleFuncCall.getCall().getArgument(0).toString().matches("%$%") and
`getStringValue` does not works for me, so I use `toString`

2023-12-10 20:54 UTC, owen-mc commented on go/ql/src/experimental/CWE-525/WebCacheDeceptionFiber.ql
> +  not httpHandleFuncCall.getCall().getArgument(0).toString().matches("%$%") and
What string does `getStringValue` give you? Or does it not have a value in a case that you care about? Queries cannot use `toString`.

2023-12-10 21:03 UTC, aydinnyunus commented on go/ql/src/experimental/CWE-525/WebCacheDeceptionFiber.ql
> +  not httpHandleFuncCall.getCall().getArgument(0).toString().matches("%$%") and
I don't know why but I did not get the endpoint which is` "/*"`. I use `type()` for getting type but it is not string for CodeQL.

**Code Sample:** 

```
r.Get("/*", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("welcome"))
	})
```

When I use `getStringValue` it did not get this argument.

2023-12-11 21:18 UTC, owen-mc commented
We already have a query for web cache deception (which you contributed). You shouldn't introduce a new query for each framework - we would end up with too many queries. Instead, you should adapt the existing query to be able to cover all of the frameworks. A common way to do this is to use an abstract class and for each framework you have a class extending it containing the framework-specific logic. The query can then use the abstract class.

2023-12-11 21:54 UTC, aydinnyunus commented
> We already have a query for web cache deception (which you contributed). You shouldn't introduce a new query for each framework - we would end up with too many queries. Instead, you should adapt the existing query to be able to cover all of the frameworks. A common way to do this is to use an abstract class and for each framework you have a class extending it containing the framework-specific logic. The query can then use the abstract class.

I don't think that one rule can cover all of the frameworks because it depends on the framework behaviour. I need to create different checks for different frameworks.

## For Example

My Previous Rule checks for endpoint ends with "%/" character. But in this frameworks I need to check "%*". 

I did not find a solution to do it. How can I do it on one rule ?

2023-12-12 12:12 UTC, owen-mc commented
There are various methods in the CodeQL language to deal with this kind of problem. The one that is most applicable here is abstract classes. If you aren't familiar with them you can read [the documentation here](https://codeql.github.com/docs/ql-language-reference/types/#abstract-classes). It may also be helpful to look at examples of them being used. They are used in almost every query, but I have tried to find a simple case that is similar to this PR. [Here](https://github.com/github/codeql/blob/main/go/ql/src/experimental/CWE-321/HardcodedKeysLib.qll#L24) is the definition of an abstract class called `Sink`. It is used in two places, [here](https://github.com/github/codeql/blob/main/go/ql/src/experimental/CWE-321/HardcodedKeysLib.qll#L374) and [here](https://github.com/github/codeql/blob/main/go/ql/src/experimental/CWE-321/HardcodedKeysLib.qll#L382). The only other mention of it is in a number of (non-abstract) classes which extend `Sink`, and which contain the logic for a sink for that query from a particular library, like [GolangJwtSign](https://github.com/github/codeql/blob/main/go/ql/src/experimental/CWE-321/HardcodedKeysLib.qll#L53), [KatarasJwt](https://github.com/github/codeql/blob/main/go/ql/src/experimental/CWE-321/HardcodedKeysLib.qll#L81), [IrisJwt](https://github.com/github/codeql/blob/main/go/ql/src/experimental/CWE-321/HardcodedKeysLib.qll#L110), and many more. So those two uses of `Sink` refer to any element of any of the classes extending `Sink`.

2023-12-12 18:48 UTC, aydinnyunus commented
Thank you so much @owen-mc. You are the best. Should I need to close this request or continue on this ?

2023-12-12 21:24 UTC, owen-mc commented
I would keep this PR open. It is linked with the bug bounty application.

2023-12-12 22:55 UTC, aydinnyunus commented
Okay. I create abstract classes but did not get any match. What am I missing ?

Also I tried with extends CallNode and basic queries without checking endpoints but none of them matched.

`abstract class Sink extends DataFlow::CallNode`

2023-12-13 10:49 UTC, owen-mc requested changes
You don't need all the data-flow stuff, because you aren't looking for a flow path in this query.

2023-12-13 10:49 UTC, owen-mc commented on go/ql/src/experimental/CWE-525/WebCacheDeceptionLib.qll
> +  module Flow = TaintTracking::Global<Config>;
```suggestion
  abstract class Sink extends DataFlow::Node { }

  private class GoNetHTTP extends Sink {
    GoNetHTTP() {
      exists(
        DataFlow::CallNode m, DataFlow::ReadNode rn, Http::HeaderWrite::Range hw, DeclaredFunction f
      |
        m.getTarget().hasQualifiedName("net/http", "HandleFunc") and
        m.getArgument(0).getStringValue().matches("%/") and
        m.getArgument(1) = rn and
        rn.reads(f) and
        f.getParameter(0) = hw.getResponseWriter() and
        hw.getHeaderName() = "cache-control" and
        this = m.getArgument(0)
      )
    }
  }

  private class GoFiber extends Sink {
    GoFiber() {
      exists(ImportSpec i |
        i.getPath() = "github.com/gofiber/fiber" or
        i.getPath() = "github.com/gofiber/fiber/v2"
      |
        exists(DataFlow::MethodCallNode m |
          m.getCall().getArgument(0).toString().matches("%/*%") and
          this = m.getArgument(0)
        )
      )
    }
  }

  private class GoChi extends Sink {
    GoChi() {
      exists(ImportSpec i |
        i.getPath() = "github.com/go-chi/chi/v5" or
        i.getPath() = "github.com/go-chi/chi/v5/middleware"
      |
        exists(DataFlow::MethodCallNode m |
          m.getCall().getArgument(0).toString().matches("%/*%") and
          this = m.getArgument(0)
        )
      )
    }
  }
```

2023-12-13 10:49 UTC, owen-mc commented on go/ql/src/experimental/CWE-525/WebCacheDeception.ql
> + * @description A caching system has been detected on the application and is vulnerable to web cache deception on Gofiber. By manipulating the URL it is possible to force the application to cache pag
```suggestion
 * @description A caching system has been detected on the application and is vulnerable to web cache deception. By manipulating the URL it is possible to force the application to cache pages that are only accessible by an authenticated user. Once cached, these pages can be accessed by an unauthenticated user.
```

2023-12-13 10:49 UTC, owen-mc commented on go/ql/src/experimental/CWE-525/WebCacheDeception.ql
> +import WebCacheDeception::Flow::PathGraph
```suggestion
```

2023-12-13 10:49 UTC, owen-mc commented on go/ql/src/experimental/CWE-525/WebCacheDeception.ql
> +  "Web Cache Deception"
```suggestion
from WebCacheDeception::Sink httpHandleFuncCall
select httpHandleFuncCall, "$@ is used as wildcard endpoint.", httpHandleFuncCall.getNode(),
  "Web Cache Deception"
```

2023-12-14 21:36 UTC, owen-mc commented
One of your tests is failing.

2023-12-14 21:55 UTC, aydinnyunus commented
I think it is okay now. Can you restart the tests ?

2023-12-18 08:16 UTC, aydinnyunus commented
I think it is passed the pipeline but the toString problems still exists.

2023-12-18 21:08 UTC, owen-mc commented
Every time you merge main in I can no longer see the results of the tests. Please do not do it so often, unless it is needed because of a merge conflict.

2023-12-19 05:50 UTC, aydinnyunus commented
Okay 🙏

2024-03-04 14:36 UTC, owen-mc approved these changes

2024-03-04 14:36 UTC, merged