Ruby: Add additional sinks for connection methods
github/codeql pull request #15619
Opened 2024-02-14 22:43 UTC by joefarebrother

Part of https://github.com/github/codeql-team/issues/2616 and https://github.com/github/codeql-team/issues/2559

2024-02-15 15:00 UTC, sidshank commented on ruby/ql/lib/change-notes/2024-02-15-activerecord_connection_sql_sinks
> +---
This file seems to have been mistakenly committed in addition to the change-note markdown file.

2024-02-21 17:21 UTC, alexrford requested changes
Sorry for the delay in reviewing this! One minor comment, otherwise looks great.

2024-02-21 17:21 UTC, alexrford commented on ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll
> +        .getAMethodCall([
We can add [`create`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/DatabaseStatements.html#method-i-create) (an alias for `insert`) to this.

I think we can also remove `select_update`? I can't find this as a query execution method.

2024-02-22 11:15 UTC, hmac approved these changes

2024-02-22 11:16 UTC, hmac commented
Ah it looks like you need an explicit re-approval from @alexrford to merge this - I thought my approval would be enough. Sorry!

2024-02-22 13:53 UTC, alexrford approved these changes

2024-02-22 14:02 UTC, merged