Python: Promote Header Injection query from experimental
github/codeql pull request #16105
Opened 2024-04-02 20:39 UTC by joefarebrother

Promotes https://github.com/github/codeql/pull/5463

2024-04-22 10:06 UTC, RasmusWL requested changes
Overall LGTM, I think you did really a really good job promoting this query, thinking about many of the corner cases that could be encountered.

To align better with the [Java query](https://codeql.github.com/codeql-query-help/java/java-http-response-splitting/), I would suggest we rename this query into `HTTP response splitting`. Although I don't find anything wrong with the Header Injection name, I feel better alignment wins in this scenario. (but do let me know if you disagree).

Nitpicking a bit, I would recommend merging `Tests1` and `Tests2` folders for query testing. Navigating the two folders is a bit annoying, and when the only difference is showing that using a validator for `wsgiref` mitigates this attack, I think you can just include that in the other test file (test_app3/4).

### ConceptsTests

In terms of testing the new concepts, we've traditionally added these to a shared [ConceptsTest](https://github.com/github/codeql/blob/991d5cc54b27338cfcd9e1cd685c425e8e7aa11a/python/ql/test/experimental/meta/ConceptsTest.qll). This test is run on all our library modeling test folders. The core idea being that we test our library modeling inside the `library-tests/frameworks/<library>` folder, and then only have the bare essentials in the query test folder. For example, instead of testing all ways of setting a cookie in the `ql/test/query-tests/Security/CWE-113-HeaderInjection/Tests1/wsgiref_tests.py` file, we would do so in `ql/test/library-tests/frameworks/stdlib/wsgiref_simple_server_test.py`. This way, if another query wants to utilize the header write modeling, we don't need to replicate all the different ways to write to a header in the query test files, but can just rely on the library test files.

So while there's not anything wrong with the test you have done, I would be violating our test principle if I didn't ask you to add a new case to ConceptsTests :blush: 

(see examples of cookie handling by following the links in the section below)

### optional followup work:

A bit of followup work that we could do, is to rewrite the library modeling that handles setting cookie values, as some of them look for writes to the `Set-Cookie` headers. Example [modeling](https://github.com/github/codeql/blob/937af906fd6a1a6a6d5237f8f1ad9b1ce3a4f7ea/python/ql/lib/semmle/python/frameworks/FastApi.qll#L367-L386) + [tests](https://github.com/github/codeql/blob/d493cfdf3a118b277fad18541d348abfc227e58e/python/ql/test/library-tests/frameworks/fastapi/response_test.py#L14-L15).

---

I also noted that we _could_ restore django header writes by reverting [this specific change](https://github.com/github/codeql/pull/16105/commits/2590d57b0a16fe23d0daea92643624a4c89931f5#diff-7cbf166da1fec37a36d342fb500f780b1ef87b1d94a828f06e1d0dc616ddfaad).

2024-04-23 13:36 UTC, joefarebrother commented
The reason for the tests being split into `Test1` and `Test2` folders is that the models only check for the presence of a validator anywhere in the database, so a separate DB is needed to test for the case in which it isn't used.

2024-04-29 10:14 UTC, joefarebrother commented
@RasmusWL Tests have been added to ConceptTests

2024-05-02 11:19 UTC, RasmusWL requested changes
Thanks for the updates to the tests, I think you did a good job following the general way our other ConceptTests have been structured :+1:

---

> The reason for the tests being split into `Test1` and `Test2` folders is that the models only check for the presence of a validator anywhere in the database, so a separate DB is needed to test for the case in which it isn't used.

Makes sense :+1: would be great if we can highlight that in the top of the file, so it's obvious why we need it. I would probably name the tests something like this, so make it clear:

* python/ql/test/query-tests/Security/CWE-113-HeaderInjection/
* python/ql/test/query-tests/Security/CWE-113-HeaderInjection-wsgi-validator/

Actually, looking through the code a bit more, we _could_ extend the `startResponse` type-tracker to keep track of what `WsgirefSimpleServerApplication` it was initiated from (so we can know whether a validator is applied or not). NOTE: this will only solve the validated/unvalidated problem for the start response call and not any of the other ways to set headers... I think that's OK :+1: (but that's just my gut feeling, I don't have any actual data to back it up)

2024-05-07 08:48 UTC, joefarebrother commented
I have now renamed one of the test folders and added an explanatory comment. 

I considered tracking validation status to the `startResponse` calls; however other sinks (such as the `Headers` class) would still have to rely on the validator existence check, so it doesn't really make the test structure that much more convenient; and in terms of actual results it could make a difference just in a case where there are multiple wsgi apps, only some of which are validated. But my intuition says that this doesn't seem like a very likely situation outside of tests.

2024-05-14 09:57 UTC, RasmusWL approved these changes
Nice :+1:

2024-05-14 12:23 UTC, merged