C#: Exclude properties with both a getter and setter as candidates for modelling.
github/codeql pull request #16121
Opened 2024-04-04 11:27 UTC by michaelnebel

2024-04-10 13:53 UTC, michaelnebel commented
@hvitved : This might be of interest to you. The last DCA execution shows that we loose a couple of true positive alerts (but which could might as well have been false positives - as some of the paths that lead to the alerts are actually false positives). It all boils down to the generated models for `ProcessStartInfo` (you have recently excluded some of these by a manual neutral override). Where "any" constructor argument taints the entire object, which turns out to be a bad assumption for this particular class as it exposes many properties.

I still be believe that the changes in this PR is the way forward, but I will do some manual modelling of this class as it is pretty widely used.

2024-04-11 07:35 UTC, michaelnebel commented
DCA looks good.

2024-04-12 10:35 UTC, hvitved requested changes

2024-04-12 11:29 UTC, michaelnebel commented on csharp/ql/src/Telemetry/ExternalApi.qll
> +  )
I will modify this slightly as it is important that the declaration is a property and not eg. an indexer.

2024-04-16 12:27 UTC, hvitved approved these changes

2024-04-16 12:49 UTC, merged