Python : Arbitrary code execution due to Js2Py
github/codeql pull request #16771
Opened 2024-06-15 15:23 UTC by porcupineyhairs

Js2Py is a Javascript to Python translation library written in Python. It allows users to invoke JavaScript code directly from Python. The Js2Py interpreter by default exposes the entire standard library to it's users. This can lead to security issues if a malicious input were directly.

This PR includes a CodeQL query along with a qhelp and testcases to detect cases where an untrusted input flows to an Js2Py eval call.

This query successfully detects CVE-2023-0297 in `pyload/pyload`along with it's fix. The databases can be downloaded from the links bellow.
```
https://file.io/qrMEjSJJoTq1
https://filetransfer.io/data-package/a02eab7V#link
```

2024-06-15 16:02 UTC, ghsecuritylab commented
Hello porcupineyhairs 👋
You have submitted this pull request as a bug bounty report in the [github/securitylab](https://github.com/github/securitylab) repository and therefore this pull request has been put into draft state to give time for the GitHub Security Lab to assess the PR. When GitHub Security Lab has finished assessing your pull request, it will be marked automatically as `Ready for review`. Until then, please don't change the draft state.

In the meantime, feel free to make changes to the pull request. If you'd like to maximize payout for your this and future submissions, here are a few general guidelines, that we might take into consideration when reviewing a submission.

- the submission models widely-used frameworks/libraries
- the vulnerability modeled in the submission is impactful
- the submission finds new true positive vulnerabilities
- the submission finds very few false positives
- code in the submission is easy to read and will be easy to maintain
- documentation is written clearly, highlighting the impact of the issue it finds and is written without grammatical or other errors. The code samples clearly show the vulnerability
- the submission includes tests, change note etc.

Please note that these are guidelines, not rules. Since we have a lot of different types of submissions, the guidelines might vary for each submission.

Happy hacking!

2024-07-01 11:22 UTC, sylwia-budzynska commented
@github/codeql-python 👋 This submission is ready for review.

2024-07-02 08:59 UTC, RasmusWL requested changes
Thanks for your contribution :muscle: 

I've made a few suggestions. If you accept the one for the alert message, you will also need to update the .expected files.

I had a brief look to understand what `js2py.disable_pyimport()` actually does ([src](https://github.com/PiotrDabkowski/pyjsparser/blob/cbd1e05e8227782bcca6ea71313793e2de737f0f/pyjsparser/parser.py#L2127)), and found an interesting comment highlighting that even when using this, you should still consider using the library with untrusted input as insecure. I think this is important to highlight in the qhelp.

2024-07-02 08:59 UTC, RasmusWL commented on python/ql/src/experimental/Security/CWE-094/Js2Py.qhelp
> +        <p> This vulnerability can be prevented either by preventing an untrusted user input to lfow
```suggestion
        <p> This vulnerability can be prevented either by preventing an untrusted user input to flow
```

2024-07-02 08:59 UTC, RasmusWL commented on python/ql/src/experimental/Security/CWE-094/Js2Py.qhelp
> +            to an <code>eval_js</code> call. Or, thee impact of this vulnerability can be
```suggestion
            to an <code>eval_js</code> call. Or, the impact of this vulnerability can be
```

2024-07-02 08:59 UTC, RasmusWL commented on python/ql/src/experimental/Security/CWE-094/Js2Py.ql
> + * @id python/js2py-rce
convention is to use `py/` as the prefix

```suggestion
 * @id py/js2py-rce
```

2024-07-02 08:59 UTC, RasmusWL commented on python/ql/src/experimental/Security/CWE-094/Js2Py.ql
> +  not exists(DisablePyImportCall c)
I think the following looks cleaner, although it does the same.

NOTE: I've also added support for `EvalJs` method call.

```suggestion
module Js2PyFlowConfiguration implements DataFlow::ConfigSig {
  predicate isSource(DataFlow::Node node) { node instanceof RemoteFlowSource }

  predicate isSink(DataFlow::Node node) {
    API::moduleImport("js2py").getMember(["eval_js", "eval_js6", "EvalJs"]).getACall().getArg(_) = node
  }
}

module Js2PyFlow = TaintTracking::Global<Js2PyFlowConfiguration>;

import Js2PyFlow::PathGraph

from Js2PyFlow::PathNode source, Js2PyFlow::PathNode sink
where
  Js2PyFlow::flowPath(source, sink) and
  not exists(API::moduleImport("js2py").getMember("disable_pyimport").getACall())
```

2024-07-02 08:59 UTC, RasmusWL commented on python/ql/src/experimental/Security/CWE-094/Js2Py.ql
> +select sink, source, sink, "This can lead to arbitrary code execution"
This alert message is more in-line with our other alert messages

```suggestion
select sink, source, sink, "This input to Js2Py depends on a $@.", source.getNode(),
  "user-provided value"
```

2024-07-02 08:59 UTC, RasmusWL commented on python/ql/src/experimental/Security/CWE-094/Js2Py.qhelp
> +            significantly reduced by disabling imports from the interepreted code. </p>
```suggestion
            significantly reduced by disabling imports from the interepreted code (note that in a <a href="https://github.com/PiotrDabkowski/Js2Py/issues/45#issuecomment-258724406">comment</a> the author of the library highlights that Js2Py is still insecure with this option).</p>
```

2024-07-11 13:31 UTC, RasmusWL approved these changes
Thanks :+1:

Before promoting this, I think we should expand tests a bit to also include `js2py.disable_pyimport()`

2024-07-11 13:31 UTC, merged