Go: Convert Beego sources to MaD
github/codeql pull request #16809
Opened 2024-06-21 14:43 UTC by owen-mc

Convert Beego sources to MaD. Also add in some missing summary models (with a different module path) that I spotted at the same time.

This should be merged after https://github.com/github/codeql/pull/16799.

2024-07-01 15:09 UTC, egregius313 commented
Do we think this needs a change note? (cf [Java: Convert implementations of `LocalUserInput` to Models-as-Data](https://github.com/github/codeql/pull/14127/files#diff-90478b2775b33e5b5418e5630c4896d2d097dc9c6ffad6080b343d0c1ab081bb))

Since the existing QL classes are `private` I think it's fine to exclude one for this PR.

2024-07-01 15:11 UTC, egregius313 requested changes
LGTM. But should probably rebase and re-run tests to re-check provenance numbers

2024-07-01 15:55 UTC, owen-mc commented
@egregius313 I rebased and CI passed.

2024-07-02 08:35 UTC, egregius313 approved these changes
LGTM

2024-07-02 08:36 UTC, merged