Python: Pycurl SSL Disabled
github/codeql pull request #16812
Opened 2024-06-23 12:37 UTC by porcupineyhairs

Pycurl is a library which provides curl binding in python. The original library is partially modelled in codeql. This PR adds support to test for SSL certificate validation when using pycurl.

2024-06-24 00:10 UTC, ghsecuritylab commented
Hello porcupineyhairs 👋
You have submitted this pull request as a bug bounty report in the [github/securitylab](https://github.com/github/securitylab) repository and therefore this pull request has been put into draft state to give time for the GitHub Security Lab to assess the PR. When GitHub Security Lab has finished assessing your pull request, it will be marked automatically as `Ready for review`. Until then, please don't change the draft state.

In the meantime, feel free to make changes to the pull request. If you'd like to maximize payout for your this and future submissions, here are a few general guidelines, that we might take into consideration when reviewing a submission.

- the submission models widely-used frameworks/libraries
- the vulnerability modeled in the submission is impactful
- the submission finds new true positive vulnerabilities
- the submission finds very few false positives
- code in the submission is easy to read and will be easy to maintain
- documentation is written clearly, highlighting the impact of the issue it finds and is written without grammatical or other errors. The code samples clearly show the vulnerability
- the submission includes tests, change note etc.

Please note that these are guidelines, not rules. Since we have a lot of different types of submissions, the guidelines might vary for each submission.

Happy hacking!

2024-07-29 08:21 UTC, yoff requested changes
Nice to get this TODO addressed. I do think, though, that it ought to be done slightly differently.

2024-07-29 08:21 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Pycurl.qll
>      }
This class is representing calls to `setopt` where the first argument is specifically `"PyCurl.URL"`. For these calls, the current implementation of `disablesCertificateValidation` as `none()` is correct. What you have done is expressing that this call disables certificate validation if there is _another_ call with arguments `(PyCurl.SSL_VERIFYPEER, 0)`.

What you would need to do is likely to create a new class extending `Http::Client::Request::Range` representing calls to `setopt` where the first argument is specifically `"PyCurl.SSL_VERIFYPEER"` and then you can implement `disablesCertificateValidation` by comparing the second argument with `0` (and also with `False`, please).

2024-07-29 08:21 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Pycurl.qll
> +    }
This can also come from an instance, see http://pycurl.io/docs/latest/curlobject.html#pycurl.Curl.setopt.

2024-07-29 08:24 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Pycurl.qll
> +          exists(IntegerLiteral i | i.getN() = "0" and c.getArg(1).asExpr() = i)
It is possible to just compare the integer values
```suggestion
          exists(IntegerLiteral i | i.getValue() = 0 and c.getArg(1).asExpr() = i)
```

2024-09-02 13:23 UTC, sylwia-budzynska commented
Hi @porcupineyhairs - we would like to close the last remaining bug bounty PRs soon. Do you think you will keep on working on this PR?

2024-10-14 06:39 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Pycurl.qll
>      }
Closer, but you are still looking at another call (`c = setopt().getACall()`). You have to look at the argument for the call represented by the class; something like `c = this.getACall()`. Also, the boolean has to come from the call; you are now just checking if they wrote `false` anywhere in the code.

2024-10-21 06:54 UTC, yoff requested changes
Just a small semantic error now, I think :-)

2024-10-21 06:54 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Pycurl.qll
>      }
Yes, much better :-) I think the boolean would also have to go into arg(1)?

2024-10-21 06:54 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Pycurl.qll
> +          exists(BooleanLiteral b | b.booleanValue() = false and this.getArg(_).asExpr() = b)
```suggestion
          this.getArg(1).asExpr().(IntegerLiteral).getValue() = 0
          or
          this.getArg(1).asExpr().(BooleanLiteral).booleanValue() = false
```

2024-10-24 09:44 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Pycurl.qll
> +    /** Gets a reference to an instance of `pycurl.Curl.SSL_VERIFYPEER`. */
We use "instance" to refer to class instances.
```suggestion
    /** Gets a reference to `pycurl.Curl.setopt`. */
    private API::Node setopt() { result = instance().getMember("setopt") }

    /** Gets a reference to the constant `pycurl.Curl.SSL_VERIFYPEER`. */
```

2024-10-24 09:44 UTC, yoff approved these changes
LGTM

2024-10-25 14:23 UTC, merged