Go: Convert log-injection, path-injection and command-injection sinks to use models-as-data
github/codeql pull request #17162
Opened 2024-08-06 16:03 UTC by owen-mc

Convert log-injection, path-injection and command-injection sinks to use models-as-data

2024-08-09 03:53 UTC, egregius313 commented on go/ql/lib/ext/github.com.sirupsen.logrus.model.yml
> +      - ["logrus", "ggithub.com/Sirupsen/logrus"]
Typo in package path
```suggestion
      - ["logrus", "github.com/Sirupsen/logrus"]
```

2024-08-09 03:57 UTC, egregius313 requested changes
LGTM other than typo in logrus package path

2024-08-09 21:42 UTC, owen-mc commented
@egregius313 Thanks for spotting that! I accepted your suggested change. Please re-review.

2024-08-10 18:05 UTC, egregius313 approved these changes
LGTM

2024-08-10 23:20 UTC, merged