Go: convert regex-use, url-redirection sinks to use models-as-data
github/codeql pull request #17177
Opened 2024-08-07 20:31 UTC by owen-mc

Convert regex-use, url-redirection sinks to use models-as-data. Follows on from https://github.com/github/codeql/pull/17162.

2024-08-09 04:18 UTC, egregius313 commented on go/ql/lib/semmle/go/frameworks/stdlib/Regexp.qll
> +    )
Does this need to add handling of `-1` corresponding to `receiver` like done in the http concepts library?

2024-08-09 04:22 UTC, egregius313 requested changes
Other than my comment about the regex kind, this pretty much LGTM.

However, since this modifies several of the same framework libraries as #17162, I am going to hold off on approving the PR until after the rebasing has happened.

2024-08-10 23:38 UTC, owen-mc commented
I hadn't realised that the two PRs conflicted. Now that https://github.com/github/codeql/pull/17162 is merged I have rebased (resolving conflicts) and added a commit addressing your review comment.

2024-08-12 14:25 UTC, egregius313 approved these changes
LGTM provided tests pass

2024-08-12 15:21 UTC, merged