Add support for vulnerable CORS middlewares - FastAPI & Starlette
github/codeql pull request #17305
Opened 2024-08-27 04:31 UTC by Kwstubbs

2024-09-12 13:59 UTC, tausbn requested changes
Good stuff! 

I have made some comments and suggestions for improvement here and there. (Note: I have not commented on _everything_ that needs to be fixed -- for instance usage of `toString` or style guide violations -- so please exercise your judgement in applying these comments more broadly.)

Also, I guess the QHelp could do with a review from the docs team.

2024-09-12 23:49 UTC, Kwstubbs commented on python/ql/lib/semmle/python/frameworks/FastApi.qll
> +    override DataFlow::Node allowed_origins() { result = this.getArgByName("allow_origins") }
They are passed by argument only.

2024-09-13 07:20 UTC, Kwstubbs commented on python/ql/lib/semmle/python/frameworks/Starlette.qll
> +  }
Yup, seems I overcooked here. 🆘  😄

2024-09-17 15:36 UTC, tausbn requested changes
Your changes look really good. Thanks!

Now there's just one thing missing: some tests for the concepts you're introducing.

For this, you'll need to extend the [ConceptsTest.qll](https://github.com/github/codeql/blob/main/python/ql/test/experimental/meta/ConceptsTest.qll) file, and add to the existing tests for [`fastapi`](https://github.com/github/codeql/tree/main/python/ql/test/library-tests/frameworks/fastapi) and [`starlette`](https://github.com/github/codeql/tree/main/python/ql/test/library-tests/frameworks/starlette).

2024-09-23 23:52 UTC, Kwstubbs commented
@tausbn let me know if theres any other tests needed 🎈

2024-09-24 12:01 UTC, tausbn approved these changes
Thank you for the tests. This looks good to me! 🙂

2024-09-24 12:02 UTC, tausbn commented
Oh, we should run a performance test before merging. I'll kick that off.

2024-09-24 13:51 UTC, merged