Add change-note for Java buildless packaging its required Maven plugin
github/codeql pull request #17811
Opened 2024-10-18 16:43 UTC by smowton

2024-10-19 06:18 UTC, owen-mc approved these changes

2024-10-19 06:19 UTC, owen-mc requested changes
The change note validation is failing. I think it's because the file name doesn't start with a date in the right format.

2024-10-21 08:36 UTC, smowton commented
@owen-mc fixed

2024-10-21 20:44 UTC, owen-mc approved these changes

2024-10-22 13:23 UTC, merged