Rust: Add support for MaD sources and sinks with access paths
github/codeql pull request #18298
Opened 2024-12-16 15:31 UTC by hvitved

2025-01-07 09:59 UTC, geoffw0 reviewed
I'm looking forward to this PR being merged.  I want to use this functionality in several places already, the tests look like exactly what I need, and I'm experimenting with this branch locally.

I don't feel very confident reviewing the code changes in this PR though - if there are any specific parts you'd like me to look at or discuss please say so.

2025-01-07 10:09 UTC, aibaars commented on rust/ql/test/library-tests/dataflow/models/models.ext.yml
> +      - ["repo::test", "<crate::MyFieldEnum>::source", "ReturnValue.Variant[crate::MyFieldEnum::C::field_c]", "test-source", "manual"]
What does the `repo` prefix mean, and why do we need the `crate::` prefix?

2025-01-07 12:37 UTC, aibaars commented on rust/ql/test/library-tests/dataflow/models/models.ext.yml
> +      - ["repo::test", "<crate::MyFieldEnum>::source", "ReturnValue.Variant[crate::MyFieldEnum::C::field_c]", "test-source", "manual"]
How would this work if there are items from multiple crates involved?

2025-01-08 08:26 UTC, hvitved commented on rust/ql/test/library-tests/dataflow/models/models.ext.yml
> +      - ["repo::test", "<crate::MyFieldEnum>::source", "ReturnValue.Variant[crate::MyFieldEnum::C::field_c]", "test-source", "manual"]
Ah, right. I decided to not include the crate origins in the `Variant` arguments, since that would bloat things. But you are right that this can potentially give rise to some ambiguity, if two crates define variants with the same canonical paths.

2025-01-08 08:39 UTC, hvitved commented
@aschackmull : Are you able to review the shared bits in `FlowSummaryImpl.qll`?

2025-01-08 09:51 UTC, aschackmull requested changes

2025-01-08 09:51 UTC, aschackmull commented on shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll
> +        state.isSinkInputState(sink, _, kind, model)
I think something needs to change here. We worked very hard to untangle and stratify `DataFlow::Node` vs. `SummaryNode` such that `FlowSummaryImpl` wasn't dependent on `DataFlow::Node`. But now they've been made mutually recursive. We need to fix that, i.e. we should not embed `DataFlow::Node`s into `SummaryNode`s.

2025-01-08 10:01 UTC, hvitved commented on shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll
> +        state.isSinkInputState(sink, _, kind, model)
`SinkNode` is not a subset of `DataFlow::Node`, rather it is a subset of the parameterized type `SinkBase`, which for Rust is subset of `AstNode`.

2025-01-08 12:08 UTC, aschackmull commented on shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll
> +        state.isSinkInputState(sink, _, kind, model)
Ah! Right.
So I guess the only new connection to `DataFlow::Node` is in `sourceLocalStep` via `StepsInput::getSourceNode`?

2025-01-08 12:12 UTC, aschackmull commented on shared/dataflow/codeql/dataflow/internal/FlowSummaryImpl.qll
> +        state.isSinkInputState(sink, _, kind, model)
Maybe `SourceNode` and `SinkNode` ought to be called something different, because it's perhaps somewhat unclear what kind of "nodes" they are supposed to be - at least I got confused. They're not `DataFlow::Node`s and they are not `SummaryNode`s. Maybe simply use `SourceElement`/`SinkElement` instead? And likely elaborate related qldoc a bit.

2025-01-09 10:33 UTC, aschackmull submitted a review, later dismissed
Shared code LGTM.

2025-01-09 12:21 UTC, aschackmull approved these changes

2025-01-10 10:49 UTC, merged