Python: Add support for magic methods
github/codeql pull request #4077
Opened 2020-08-14 12:22 UTC by yoff

This PR labels certain control flow nodes as corresponding to method calls to magic methods. This is then picked up by the data flow library to resolve flow between subexpressions and parameters.

Currently only binary operators are supported and only the standard form (not the r-variant).

2020-08-14 12:34 UTC, yoff commented
Ah, I forgot to annotate the test file with the newly obtained results..

2020-08-14 12:50 UTC, yoff commented
There were no annotations present, so I did it in two steps to make the diff clear. The first commit marks all calls as not found, the second one unmarks the ones found by the new magic feature.

2020-08-17 14:27 UTC, intrigus-lgtm commented on python/ql/src/experimental/dataflow/internal/DataFlowPrivate.qll
> +  /** Get the specified arguemnt to this call. */
```suggestion
  /** Get the specified argument to this call. */
```

2020-08-17 14:28 UTC, intrigus-lgtm commented on python/ql/src/experimental/dataflow/internal/DataFlowPrivate.qll
> +/** Represents a call to a callable */
```suggestion
/** Represents a call to a callable. */
```

2020-08-17 14:28 UTC, intrigus-lgtm commented on python/ql/src/experimental/dataflow/internal/DataFlowPrivate.qll
> +class MagicCall extends DataFlowCall, TMagicCall {
Missing QlDoc?

2020-08-17 14:28 UTC, intrigus-lgtm commented on python/ql/src/semmle/python/Magic.qll
> +    /** Gets the name of the method that would be called */
```suggestion
    /** Gets the name of the method that would be called. */
```

2020-08-18 12:38 UTC, yoff commented on python/ql/src/semmle/python/Magic.qll
> +module MagicMethod {
It has been remedied :-)

2020-08-18 12:38 UTC, yoff commented on python/ql/src/semmle/python/Magic.qll
> +        pot.getSelf().pointsTo().getClass().lookup(pot.getMagicMethodName()) = resolvedMagicMethod
I have adopted the above structure.

2020-08-18 12:38 UTC, yoff commented on python/ql/src/experimental/dataflow/internal/DataFlowPrivate.qll
> +class MagicCall extends DataFlowCall, TMagicCall {
Yes, added.

2020-08-24 11:04 UTC, tausbn requested changes
Found a few typos. Otherwise looks good to me. :+1:

2020-08-24 11:04 UTC, tausbn commented on python/ql/src/semmle/python/SpecialMethods.qll
> +/** A control flow node which might correpsond to a special method call. */
```suggestion
/** A control flow node which might correspond to a special method call. */
```

2020-08-24 11:04 UTC, tausbn commented on python/ql/src/semmle/python/SpecialMethods.qll
> +  /** A control flow node which might correpsond to a special method call. */
```suggestion
  /** A control flow node which might correspond to a special method call. */
```

2020-08-24 11:04 UTC, tausbn commented on python/ql/src/semmle/python/SpecialMethods.qll
> +    /** Gets the controlflow node that would be passed as the specified argument. */
```suggestion
    /** Gets the control flow node that would be passed as the specified argument. */
```

2020-08-26 13:52 UTC, tausbn approved these changes

2020-08-26 13:53 UTC, tausbn commented
I think this looks good to go, once the merge conflicts have been ironed out.

2020-08-26 15:45 UTC, yoff commented
"dismissed"?! I Specifically merged main to iron out those conflicts...

2020-08-26 16:22 UTC, RasmusWL commented
Errors on jenkins `ERROR: The cast type DataFlowCall is incompatible with the expression type ControlFlowNode. (argumentRouting1.ql:12,23-45)`

2020-08-27 11:20 UTC, tausbn approved these changes

2020-08-27 11:20 UTC, merged