C#: Implement support for path transformers
github/codeql pull request #4212
Opened 2020-09-04 13:18 UTC by hvitved

2020-09-07 15:37 UTC, tamasvajk requested changes

2020-09-07 15:37 UTC, tamasvajk commented on csharp/extractor/Semmle.Extraction/PathTransformer.cs
> +            name = lines[i++].Substring(1);
I had to think a bit what we're skipping here. A comment saying it's `#` would help if we have to come back to it later.

2020-09-07 15:37 UTC, tamasvajk commented on csharp/extractor/Semmle.Extraction/PathTransformer.cs
> +                if (string.IsNullOrEmpty(lines[i]))
Shouldn't we filter lines with whitespaces too?

2020-09-07 15:37 UTC, tamasvajk commented on csharp/extractor/Semmle.Extraction/PathTransformer.cs
> +        {
There are 3 `i++` increments in this method. I think changing the `while` to `while (++i < lines.Length ...)` would work instead of them.

2020-09-08 11:00 UTC, tamasvajk submitted a review, later dismissed

2020-09-11 18:37 UTC, hvitved commented on csharp/extractor/Semmle.Extraction/Entities/File.cs
> +            TransformedPath = Context.Extractor.PathTransformer.Transform(OriginalPath);
Looks like we need to guard against the empty string here (as passed from `GeneratedLocation`).

2020-09-14 13:22 UTC, tamasvajk approved these changes

2020-09-16 06:38 UTC, hvitved commented
@dave-bartolomeo : Let me know when you have tested these changes, and whether the PR can be merged.

2020-09-21 19:40 UTC, dbartol approved these changes
I've verified that the 1.24-based version of this seems to work for Microsoft, so this is ready for 1.25.1.

2020-09-22 07:20 UTC, merged