JS: Add source and sink for DVSA
github/codeql pull request #4329
Opened 2020-09-23 12:29 UTC by erik-krogh

The first commit is a cherry-pick from [the reexports PR](https://github.com/github/codeql/pull/4247), so this PR will be in draft mode for a while. 

A [Damn Vulnerable Serverless Application](https://github.com/OWASP/DVSA) uses serverless handlers, and we didn't have any support for those previously.
It doesn't [look like Serverless applications are common](https://github.com/search?q=filename%3Atemplate.yml+Handler+nodejs&type=Code&ref=advsearch&l=&l=), but it is a nice addition to have none the less. 
A serverless handler is specified using a `.yml` configuration, which we now recognize.   

I've added the `event` parameter of any serverless handler as a `RemoteFlowSource`.   

I've also added `require("node-serialize").unserialize(..)` as a `js/code-injection` sink.  
This library is used in the Damn Vulnerable Serverless Application (and also in [Damn Vulnerable NodeJS Application](https://github.com/appsecco/dvna)).

2020-10-07 09:01 UTC, esbena requested changes
This is a nice conceptual addition. It seems to generalize to a framework that lets configuration files promote certain functions to receivers of remote input.

You mention `AWS serverless` in the code. Did you check if the big cloud alternatives, such as https://azure.microsoft.com/en-us/solutions/serverless/ and https://cloud.google.com/serverless fits into this model as well? They simply popped up when googling a bit.

Implementation LGTM, but I would like some more documentation, and a change note. I think simply supporting "serverless" as a concept is a bit too broad of a change-note entry though.

2020-10-08 19:28 UTC, erik-krogh commented
> You mention AWS serverless in the code. Did you check if the big cloud alternatives.  

No I did not.   
I used GitHub search to find projects that had a similar `.yml` file. AWS and Alibaba serverless appeared in that search.   
That was also how I build up the test cases. 

> Implementation LGTM, but I would like some more documentation, and a change note. I think simply supporting "serverless" as a concept is a bit too broad of a change-note entry though.

I'll try to think up some change-note.

2020-10-08 19:38 UTC, erik-krogh commented on javascript/ql/src/semmle/javascript/frameworks/ServerLess.qll
> +      if folder.regexpMatch(".*\\..+") then result = folder else result = folder + file + ".js"
It seems that I didn't cleanup this predicate sufficiently when looking through the code, sorry about that.  
The `if folder ...` was from back when the predicates were structured a bit differently.   

With that cleaned up the predicate looks like: 
```CodeQL
  bindingset[codeURI, file]
  private string getPathFromHandlerProperties(string codeURI, string file) {
    exists(string folder | folder = removeLeadingDotSlash(removeTrailingDot(codeURI)) |
      result = folder + file + ".js"
    )
  }
```

I'll still add an example.

2020-10-08 19:50 UTC, erik-krogh commented on javascript/ql/src/semmle/javascript/frameworks/ServerLess.qll
> +        ymlFile.getParentContainer().getAbsolutePath() + "/" +
> Stray thought: would this work on windows with backslash separators?

Probably not.  

> Is that a non-problem for serverless in practice?

I think so. It seems the Serverless providers are running Linux behind the scenes.   

> Is that a general problem for us in practice?

I think we are both equally qualified to answer that question.   
But I think its not a general problem. Basically every server (and Serverless) runs on Linux anyway.

2020-10-09 06:56 UTC, esbena reviewed
Thanks. A few minor things.

2020-10-09 06:56 UTC, esbena commented on javascript/ql/src/semmle/javascript/frameworks/ServerLess.qll
>        fileName = handler.regexpCapture("([^.]+).*", 1)
Could we unify the two regexps here? Adding another capture group to the first pattern should suffice.

I am not sure if the first capture group should be greedy, but I have just reused the current greediness. Intuitively, I would expect it to be lazy such that `index.foo.bar` would produce `index` and `foo.bar`.

```ql
exists(string pattern | pattern = "(.*)\\.(.*)" | 
  func = handler.regexpCapture(pattern, 1) and 
  fileName = handler.regexpCapture(pattern, 2)
)
```

2020-10-09 06:56 UTC, esbena commented on javascript/ql/src/semmle/javascript/frameworks/ServerLess.qll
> +   * ```
```suggestion
   * ```yaml
```
(since there's a `javascript` type on the block below.)

2020-10-09 20:32 UTC, esbena approved these changes

2020-10-12 12:23 UTC, merged