JS: In progress refactorization of NoSQL.qll to use API-graphs
github/codeql pull request #4363
Opened 2020-09-29 13:44 UTC by erik-krogh

2020-10-02 09:03 UTC, max-schaefer commented on javascript/ql/src/semmle/javascript/frameworks/NoSQL.qll
> +    result = getAMongoDbCallback().getParameter(1)
Can't you use the newly introduced `getAnImmediateUse` to rule this out? The immediate use would be the `DataFlow::Parameter` itself, so you can check its name.

2020-10-03 20:09 UTC, erik-krogh commented
An evaluation came back bad because of a bad join-order (see below tuple counts). 

I changed the predicate a bit such that the performance should be good now. 

```
[2020-10-03 18:44:59] (458s) Tuple counts for NoSQL::Mongoose::Document::getAMongooseDocument#f#join_rhs#1:
1         ~0%     {4} r1 = CONSTANT(unique string, unique string, unique string, unique int)["then","0","parameter 0",0]
1         ~0%     {4} r2 = SELECT r1 ON r1.<3> >= -1
1         ~0%     {4} r3 = SELECT r2 ON 0 >= -1
1         ~0%     {2} r4 = SCAN r3 OUTPUT r3.<2>, ("member " ++ r3.<0>)
1         ~0%     {4} r5 = CONSTANT(unique string, unique string, unique string, unique int)["exec","1","parameter 1",1]
1         ~0%     {4} r6 = SELECT r5 ON r5.<3> >= -1
1         ~0%     {4} r7 = SELECT r6 ON 0 >= -1
1         ~0%     {2} r8 = SCAN r7 OUTPUT r7.<2>, ("member " ++ r7.<0>)
2         ~0%     {2} r9 = r4 \/ r8
272334    ~4%     {3} r10 = JOIN r9 WITH ApiGraphs::API::Impl::edge#2#fff_102#join_rhs AS R ON FIRST 1 OUTPUT r9.<1>, R.<1>, R.<2>
548812365 ~0%     {4} r11 = JOIN r10 WITH ApiGraphs::API::Impl::edge#2#fff_102#join_rhs AS R ON FIRST 1 OUTPUT R.<1>, r10.<1>, r10.<2>, R.<2>
                  return r11
```

2020-10-04 20:46 UTC, erik-krogh commented
[A new evaluation](https://git.semmle.com/erik/dist-compare-reports/tree/profiling-erik-krogh.northeurope.cloudapp.azure.com_1601818775641) came back, and it's looking good. 

I think it might actually be a performance improvement.  
(And no changes to `--metric TaintSinks.ql`, which is a good).

2020-10-05 08:02 UTC, max-schaefer requested changes
Fantastic work, thanks! I have a few suggestions for improving terminological consistency, and one TypeScript-related question. I'm fine with addressing the latter in a follow-up PR to avoid upsetting the performance apple cart.

2020-10-05 08:02 UTC, max-schaefer commented on javascript/ql/src/semmle/javascript/frameworks/NoSQL.qll
> +    override DataFlow::SourceNode getAUse() { result.hasUnderlyingType("mongodb", "Collection") }
To expand on the above: you are meant to be able to do `root().getMember("mongodb").getMember("Collection").getInstance()` (cf [this test](https://github.com/github/codeql/blob/d38121f54a5f6e9144a99b6beebf9562a5969cdd/javascript/ql/test/ApiGraphs/typed/index.ts#L14)). If that doesn't work, I'll fix it.

2020-10-05 08:02 UTC, max-schaefer commented on javascript/ql/src/semmle/javascript/frameworks/NoSQL.qll
> +     * Gets a API node referring to a Mongoose Model object.
```suggestion
     * Gets a API-graph node referring to a Mongoose Model object.
```

2020-10-05 13:52 UTC, erik-krogh commented on javascript/ql/src/semmle/javascript/frameworks/NoSQL.qll
> +    override DataFlow::SourceNode getAUse() { result.hasUnderlyingType("mongodb", "Collection") }
> To expand on the above: you are meant to be able to do `root().getMember("mongodb").getMember("Collection").getInstance()` (cf [this test](https://github.com/github/codeql/blob/d38121f54a5f6e9144a99b6beebf9562a5969cdd/javascript/ql/test/ApiGraphs/typed/index.ts#L14)). If that doesn't work, I'll fix it.

That worked, except it ends up looking like: 
```CodeQL
result = API::root().getASuccessor(API::EdgeLabel::mod("mongodb")).getMember("Collection").getInstance()
```

The `mongodb` type has edge `"mod mongodb"`, but it is not a module-import so using `API::moduleImport("mongodb")` does not work. 

The API could use a cleanup, but lets do that later.

2020-10-05 13:52 UTC, asgerf commented on javascript/ql/src/semmle/javascript/frameworks/NoSQL.qll
> +    override DataFlow::SourceNode getAUse() { result.hasUnderlyingType("mongodb", "Collection") }
FWIW I ran into the same issue with the Angular2 model and held off on using API graphs for this reason.

The snippet you posted leaves more questions than it answers. Is `root().getMember(x)` the same as `API::moduleImport(x)`? If `Collection` is the name of an interface, what exactly does `getInstance` mean?

2020-10-05 13:57 UTC, max-schaefer commented on javascript/ql/src/semmle/javascript/frameworks/NoSQL.qll
> +    override DataFlow::SourceNode getAUse() { result.hasUnderlyingType("mongodb", "Collection") }
> That worked, except it ends up looking like: (...)

:see_no_evil:

> The mongodb type has edge "mod mongodb", but it is not a module-import so using API::moduleImport("mongodb") does not work.

That's an oversight. I'll fix it, then we can see about using it in the NoSQL model.

> If Collection is the name of an interface, what exactly does getInstance mean?

Ah, I had hoped that the concept of being an instance of a type would be natural, but if it's not we can introduce a new kind of edge for it. Any ideas for what to call it?

2020-10-05 14:46 UTC, erik-krogh commented
I think I've found a potential performance improvement. But that can wait for later, this PR is good to merge as is (when it comes to performance). 

@max-schaefer 
Have you considered making a `newtype Label` in API-Graphs? 
Currently the `ApiGraphs::API::Node::getAMember` predicate performs quite badly on `vscode`, and the reason looks to be the `string` labels ([tuple counts and clause timings](https://gist.github.com/erik-krogh/d5c35a0c692401f24b3feeeac8141245)). 

I did a quick-and-dirty experiment trying to make a `newtype Label`, and `vscode` became significantly faster.    
([See clause timings in notes](https://gist.github.com/erik-krogh/d5c35a0c692401f24b3feeeac8141245)).

2020-10-05 14:51 UTC, erik-krogh commented on javascript/ql/src/semmle/javascript/frameworks/NoSQL.qll
> +    override DataFlow::SourceNode getAUse() { result.hasUnderlyingType("mongodb", "Collection") }
> Ah, I had hoped that the concept of being an instance of a type would be natural, but if it's not we can introduce a new kind of edge for it. Any ideas for what to call it?

I think `getInstance()` is natural. We just need some utility-predicate to work with `CanonicalName`s.

2020-10-05 14:56 UTC, max-schaefer commented
> Have you considered making a newtype Label in API-Graphs?

Yes. It's something I've gone back and forth about a couple of times. The problem with the `newtype` approach is that it requires us to specify at the definition site which labels we want, which is a little error-prone. With the `bindingset` annotation we can get away with doing that at the use site, which is more convenient. I experimented with having an abstract class of label names that is used in the definition and extended at the use sites, but that became so verbose that I went back to `bindingset`s.

Definitely worth revisiting that decision if it benefits performance.

2020-10-05 15:14 UTC, asgerf commented on javascript/ql/src/semmle/javascript/frameworks/NoSQL.qll
> +    override DataFlow::SourceNode getAUse() { result.hasUnderlyingType("mongodb", "Collection") }
I'd be in favor of a classless predicate that's a direct replacement for `hasUnderlyingType`:
```codeql
API::nodeOfType("mongodb", "Collection")
```

I think representing values, type names, and type-namespaces as the same kind of node will lead to confusion, as most of the `API::Node` predicates are meaningless for type names and type-namespaces. Going straight to the "value" space means you can never mix up the two kinds of nodes.

I don't think we need to change the underlying encoding.

2020-10-05 15:20 UTC, erik-krogh commented
> Definitely worth revisiting that decision if it benefits performance.

This is the implementation I used in my small experiment:  https://github.com/erik-krogh/ql/commit/0ec5e0e3428d3bb57ced431a6addae66242ff952 

(I forgot to add the link in the previous comment).

2020-10-05 15:35 UTC, max-schaefer commented
Thanks for sharing. I think that implementation nicely highlights the duplication you get with that approach.

2020-10-05 15:43 UTC, max-schaefer commented on javascript/ql/src/semmle/javascript/frameworks/NoSQL.qll
> +    override DataFlow::SourceNode getAUse() { result.hasUnderlyingType("mongodb", "Collection") }
Something like [this](https://github.com/max-schaefer/ql/tree/js/api-graphs-type-handling-improvements)?

2020-10-05 15:52 UTC, max-schaefer commented
I'd prefer to remove the last commit. Then we have something that's identical (modulo comments) to the version that was evaluated. I'll fix the TypeScript API in a separate PR.

2020-10-05 17:07 UTC, erik-krogh commented
> I'd prefer to remove the last commit. Then we have something that's identical (modulo comments) to the version that was evaluated. I'll fix the TypeScript API in a separate PR.

I've reverted the last commit.

2020-10-05 18:38 UTC, max-schaefer approved these changes

2020-10-05 19:01 UTC, merged