C#: Refactor flow-summary interpretation
github/codeql pull request #4371
Opened 2020-09-30 15:34 UTC by hvitved

2020-10-13 10:44 UTC, tamasvajk requested changes

2020-10-13 10:44 UTC, tamasvajk commented on csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
> +      SummaryInternalNodeState predState, AccessPath ap
as discuessed, `predAp` would probably be a better name for `ap`.

2020-10-13 10:44 UTC, tamasvajk commented on csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
> +      SummaryInternalNodeState succState, AccessPath ap
`succAp` instead of `ap`.

2020-10-14 07:21 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
> +    or
We didn't have a test for this, I discovered it during an initial run of CSharp-Differences.

2020-10-14 07:26 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowPrivate.qll
> +    or
I'll add a test.

2020-10-14 07:31 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/dataflow/internal/DataFlowDispatch.qll
> +          .getSourceDeclaration()
Yes, a bug fix, but should only happen in rare cases.

2020-10-14 07:35 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/dataflow/internal/DelegateDataFlow.qll
> +    ParameterNode mid, CallContext prevLastCall, DelegateCall call, Callable c, Parameter p, int i
The reason why they are structured differently is to get a good join-order: the "flow into delegate" case is actually non-linear recursion (a conjunction with two recursive calls to `flowsFrom`).

2020-10-14 09:02 UTC, tamasvajk submitted a review, later dismissed

2020-10-14 11:54 UTC, hvitved commented
I was unable to reproduce the failing `library-tests/dataflow/collections/CollectionFlow.ql` test locally, so I have tried to rebase this PR to see if it makes a difference.

2020-10-15 09:32 UTC, tamasvajk approved these changes

2020-10-15 09:56 UTC, merged