WIP: C#: Add support for custom assert methods ([DoesNotReturnIf(true/false)])
github/codeql pull request #4484
Opened 2020-10-15 14:40 UTC by tamasvajk

2020-10-20 14:34 UTC, tamasvajk commented
todo: add change notes.

2020-10-28 10:19 UTC, hvitved requested changes

2020-10-28 10:19 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/commons/Assertions.qll
> +  abstract int getAnAssertionIndex();
We should add deprecated `getAssertionIndex()`, `getAssertedParameter()`, and `getExpr()` predicates for backwards compatibility.

2020-10-28 10:19 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/commons/Assertions.qll
> +    a.getType() = any(SystemDiagnosticsCodeAnalysisDoesNotReturnIfAttributeClass c) and
```suggestion
    a.getType() instanceof SystemDiagnosticsCodeAnalysisDoesNotReturnIfAttributeClass and
```

2020-10-28 10:19 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/commons/Assertions.qll
> +  }
```suggestion
  private int i;

  SystemDiagnosticsCodeAnalysisDoesNotReturnIfAnnotatedAssertTrueMethod() {
    isDoesNotReturnIfAttributeParameter(this.getParameter(i), false)
  }

  override int getAnAssertionIndex() { result = i }
```

2020-10-28 10:19 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/commons/Assertions.qll
> +    any()
This creates a large Cartesian product, so better to return the `System.Exception` base class.

2020-10-28 10:19 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/commons/Assertions.qll
> +class SystemDiagnosticsCodeAnalysisDoesNotReturnIfAnnotatedAssertFalseMethod extends AssertFalseMethod {
Same comments as for `SystemDiagnosticsCodeAnalysisDoesNotReturnIfAnnotatedAssertTrueMethod`.

2020-10-28 10:19 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/controlflow/internal/Splitting.qll
> +        pred = last(a.getAnExpr(), c) and
The CFG splitting logic will not work for assertions with multiple assertion arguments; I will address in a follow-up PR.

2020-10-28 14:16 UTC, tamasvajk commented
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/568/

2020-10-29 07:50 UTC, tamasvajk commented
> https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/568/

There are some nice fixes in the results, for example, we're not reporting on the following that it can be null: https://github.com/dotnet/runtime/blob/45833cb6e43b481cdb1dabe2ce29fca48ee7bf6a/src/libraries/System.Linq.Expressions/src/System/Dynamic/DynamicObject.cs#L465

2020-10-29 07:52 UTC, hvitved commented
> There are some nice fixes in the results, for example, we're not reporting on the following that it can be null: https://github.com/dotnet/runtime/blob/45833cb6e43b481cdb1dabe2ce29fca48ee7bf6a/src/libraries/System.Linq.Expressions/src/System/Dynamic/DynamicObject.cs#L465

That's excellent!

2020-10-29 07:52 UTC, hvitved approved these changes

2020-10-29 08:10 UTC, merged