C#: Add flow summary for 'Task.ConfigureAwait()'
github/codeql pull request #4543
Opened 2020-10-23 11:55 UTC by tamasvajk

2020-10-23 12:08 UTC, tamasvajk reviewed
Let's suppose the `AccessPath::cons` is working. How would I verify that the added flow summaries are working for the following two cases?
```
var i = new Task<int>(() => 42).ConfigureAwait(false).GetAwaiter().GetResult();
var j = await new Task<int>(() => 42).ConfigureAwait(false);
```
This question is actually not specific to `.ConfigureAwait()`. Which checks rely on flow summaries on `.GetAwaiter().GetResult()`?

2020-10-23 12:08 UTC, tamasvajk commented on csharp/ql/src/semmle/code/csharp/dataflow/LibraryTypeDataFlow.qll
> +  }
@hvitved This is missing from the test expected file.
When I try to debug this on a `codeql database create` DB with the following:
```
private predicate test(
  SystemRuntimeCompilerServicesConfiguredTaskAwaitableTConfiguredTaskAwaiterStruct a, Field f
) {
  a.getAField() = f
}
```
I only get two fields: `_dummy` and `_dummyPrimitive`, and therefore I get no fields in `.getUnderlyingTaskField()`. It looks to me that Roslyn reports these field names.

* What is the difference between the test and a `codeql database create` extraction? 
* How do I extract the correct field names with `codeql database create`? 
* Why doesn't this `AccessPath::cons` work?

2020-10-26 21:06 UTC, tamasvajk commented on csharp/ql/src/semmle/code/csharp/dataflow/LibraryTypeDataFlow.qll
> +    sourceAp =
hmm, I don't know how I messed this up with the explicitly added comment above it. Thanks.

2020-10-27 09:25 UTC, tamasvajk commented
@hvitved The only change I did since your fix is that I've squashed the first two commits.

2020-10-27 09:52 UTC, hvitved requested changes

2020-10-27 09:52 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/frameworks/system/runtime/CompilerServices.qll
> +/** An unbound generic struct in the `System.Runtime.CompilerServices` namespace. */
This comment is not correct. I think this class is so special that there is no need to have it, instead inline the logic where it is used below.

2020-10-28 07:50 UTC, hvitved approved these changes

2020-10-28 09:42 UTC, merged