C#: Restrict post-dominance to normal execution
github/codeql pull request #4575
Opened 2020-10-29 13:28 UTC by hvitved

### Overview

As discussed several times with @aschackmull, post-dominance makes more sense when restricted to paths that leave the callable normally, that is, without throwing an exception or halting.

For example, in

```csharp
void M3(string s)
{
    if (s is null)
        throw new ArgumentNullException(nameof(s));
    Console.WriteLine(s);
}
```

the call `Console.WriteLine(s)` will happen on all normal paths through `M3`, so we want it to post-dominate the entry point.

### Implementation

Before this PR, the CFG for `M3` was
<img width="735" alt="Screenshot 2020-10-29 at 14 12 57" src="https://user-images.githubusercontent.com/3667920/97578501-298f4500-19f1-11eb-9da1-57d04c4fa736.png">
and post-dominance was defined in terms of the `exit M3` node.

This PR changes the CFG for `M3` to
<img width="661" alt="Screenshot 2020-10-29 at 14 09 39" src="https://user-images.githubusercontent.com/3667920/97578555-3dd34200-19f1-11eb-8735-f2a748a40de6.png">
and redefines post-dominance with respect to the new `exit M3 (normal)` node that represents normal execution (highlighted in red).

Note that each callable will still have a unique exit node, which is reached from the two new normal/abnormal exit nodes: this is so that we can recover the old post-dominance logic, if needed.

2020-11-02 13:45 UTC, tamasvajk requested changes
These CFG diagrams are super useful.

The differences job is red.

2020-11-02 13:45 UTC, tamasvajk commented on csharp/ql/src/semmle/code/csharp/controlflow/ControlFlowGraph.qll
> +     * with a normal normal exit type) from `that` node must go through this node.
typo: Should be `with a normal exit type` instead of `with a normal normal exit type`.

2020-11-02 13:45 UTC, tamasvajk commented on csharp/ql/src/semmle/code/csharp/controlflow/ControlFlowGraph.qll
> +     * with a normal normal exit type) from `that` node must go through this node
typo: `normal normal`

2020-11-03 13:57 UTC, hvitved commented
> The differences job is red.

Yeah, I am not quite sure why that is, as it has run all projects successfully and done the comparison. So I think we can just ignore it.

2020-11-05 14:27 UTC, tamasvajk approved these changes

2020-11-05 14:31 UTC, merged