Python: move configurations out of queries
github/codeql pull request #4632
Opened 2020-11-06 13:30 UTC by RasmusWL

This makes it easy to extend the sources/sinks of the configuration and re-run the query from the query console on LGTM.com.

File location in `semmle.<lang>.security.dataflow.<QueryName>.qll` is matching what we currently do in other languages (JS and C# sampled).

I did not follow the pattern in other languages for wrapping all the code in a module (for example `module CodeInjection`), since I didn't understand the value in doing so -- I would like confirmation from the other teams if we _should_ actually do that, before merging. @hvitved and @asgerf can I hear your opinion on this? (I'd be happy to change our setup to match yours, but I would just like to be convinced it's a good idea first :stuck_out_tongue:)

2020-11-06 13:40 UTC, hvitved commented
> I did not follow the pattern in other languages for wrapping all the code in a module (for example `module CodeInjection`), since I didn't understand the value in doing so -- I would like confirmation from the other teams if we _should_ actually do that, before merging. @hvitved and @asgerf can I hear your opinion on this? (I'd be happy to change our setup to match yours, but I would just like to be convinced it's a good idea first 😛)

AFAIAC there is no need for the extra module layer.

2020-11-06 13:56 UTC, yoff requested changes
Thanks for doing this. I suggested a slight change in wording since "reasoning about" seemed a bit to vague and general to me.

2020-11-06 13:56 UTC, yoff commented on python/ql/src/semmle/python/security/dataflow/CodeInjection.qll
> + * Provides a taint-tracking configuration for reasoning about code injection
```suggestion
 * Provides a taint-tracking configuration for detecting code injection
```

2020-11-06 13:56 UTC, yoff commented on python/ql/src/semmle/python/security/dataflow/CodeInjection.qll
> + * A taint-tracking configuration for reasoning about code injection vulnerabilities.
```suggestion
 * A taint-tracking configuration for detecting code injection vulnerabilities.
```

2020-11-06 13:56 UTC, yoff commented on python/ql/src/semmle/python/security/dataflow/CommandInjection.qll
> + * Provides a taint-tracking configuration for reasoning about command injection
```suggestion
 * Provides a taint-tracking configuration for detecting command injection
```

2020-11-06 13:56 UTC, yoff commented on python/ql/src/semmle/python/security/dataflow/CommandInjection.qll
> + * A taint-tracking configuration for reasoning about command injection vulnerabilities.
```suggestion
 * A taint-tracking configuration for detecting command injection vulnerabilities.
```

2020-11-06 13:56 UTC, yoff commented on python/ql/src/semmle/python/security/dataflow/PathInjection.qll
> + * Provides a taint-tracking configuration for reasoning about path injection
```suggestion
 * Provides a taint-tracking configuration for detecting path injection
```

2020-11-06 13:56 UTC, yoff commented on python/ql/src/semmle/python/security/dataflow/ReflectedXSS.qll
> + * Provides a taint-tracking configuration for reasoning about reflected server-side
```suggestion
 * Provides a taint-tracking configuration for detecting reflected server-side
```

2020-11-06 13:56 UTC, yoff commented on python/ql/src/semmle/python/security/dataflow/ReflectedXSS.qll
> + * A taint-tracking configuration for reasoning about reflected server-side cross-site
```suggestion
 * A taint-tracking configuration for detecting reflected server-side cross-site
```

2020-11-06 13:56 UTC, yoff commented on python/ql/src/semmle/python/security/dataflow/SqlInjection.qll
> + * Provides a taint-tracking configuration for reasoning about SQL injection
```suggestion
 * Provides a taint-tracking configuration for detecting SQL injection
```

2020-11-06 13:56 UTC, yoff commented on python/ql/src/semmle/python/security/dataflow/SqlInjection.qll
> + * A taint-tracking configuration for reasoning about SQL injection vulnerabilities.
```suggestion
 * A taint-tracking configuration for detecting SQL injection vulnerabilities.
```

2020-11-06 13:56 UTC, yoff commented on python/ql/src/semmle/python/security/dataflow/UnsafeDeserialization.qll
> + * Provides a taint-tracking configuration for reasoning about arbitrary code execution
```suggestion
 * Provides a taint-tracking configuration for detecting arbitrary code execution
```

2020-11-06 13:56 UTC, yoff commented on python/ql/src/semmle/python/security/dataflow/UnsafeDeserialization.qll
> + * A taint-tracking configuration for reasoning about arbitrary code execution
```suggestion
 * A taint-tracking configuration for detecting arbitrary code execution
```

2020-11-06 13:57 UTC, RasmusWL commented
> Thanks for doing this. I suggested a slight change in wording since "reasoning about" seemed a bit to vague and general to me.

I not against that suggestion, I simply copied the [QLDoc from JS](https://github.com/github/codeql/blob/051c6ca31f8bf18b9890ad3d453ee4d10d3912f1/javascript/ql/src/semmle/javascript/security/dataflow/CodeInjection.qll#L15-L17).

2020-11-09 12:10 UTC, yoff approved these changes
LGTM

2020-11-09 12:10 UTC, merged