C#: Extract relational patterns
github/codeql pull request #4653
Opened 2020-11-11 12:45 UTC by tamasvajk

2020-11-11 15:03 UTC, tamasvajk commented on csharp/ql/src/semmlecode.csharp.dbscheme
> +| 122 = @lt_pattern
Maybe `lt_pattern_expr` is a better name.

2020-11-25 14:35 UTC, hvitved requested changes
LGTM. Some trivial comments.

2020-11-25 14:35 UTC, hvitved commented on csharp/change-notes/2020-11-19-Relational-pattern.md
> +* The `RelationalPatternExpr` and its 4 subclass have been added to support C# 9
sub classes

2020-11-25 14:35 UTC, hvitved commented on csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/RecursivePattern.cs
> +    internal partial class RecursivePattern : Expression
Why this change?

2020-11-25 14:35 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/exprs/Expr.qll
> +abstract class RelationalPatternExpr extends PatternExpr, @relational_pattern_expr {
Remove `abstract`.

2020-11-25 14:35 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/exprs/Expr.qll
> +  /** Get the operator of this relational pattern. */
`/** Gets the name of the operator in this pattern. */`

2020-11-25 14:35 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/exprs/Expr.qll
> +/** A 'less than' pattern */
``A less-than pattern, for example `< 10` in `x is < 10` .``

2020-11-25 14:35 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/exprs/Expr.qll
> +/** A 'greater than' pattern */
``A greater-than pattern, for example `> 10` in `x is > 10` .``

2020-11-25 14:35 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/exprs/Expr.qll
> +/** A 'less than equal' pattern */
``A less-than or equals pattern, for example `<= 10` in `x is <= 10` .``

2020-11-25 14:35 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/exprs/Expr.qll
> +/** A 'greater than equal' pattern */
``A greater-than or equals pattern, for example `>= 10` in `x is >= 10` .``

2020-11-25 20:38 UTC, tamasvajk commented on csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Patterns/RecursivePattern.cs
> +    internal partial class RecursivePattern : Expression
no reason. I removed it.

2020-11-26 07:49 UTC, hvitved submitted a review, later dismissed

2020-11-27 09:38 UTC, hvitved approved these changes

2020-11-27 10:23 UTC, merged