C#: Add queries to check untrusted data flow to external APIs
github/codeql pull request #4678
Opened 2020-11-17 14:50 UTC by tamasvajk

2020-11-18 08:07 UTC, tamasvajk commented
[Differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/631/)

2020-12-03 13:39 UTC, hvitved requested changes
A few minor comments, otherwise LGTM. Great to have this query in the toolbox.

2020-12-03 13:39 UTC, hvitved commented on csharp/ql/src/Security Features/CWE-020/ExternalAPIsUsedWithUntrustedData.ql
> +import semmle.code.csharp.dataflow.DataFlow
I don't think this import is needed.

2020-12-03 13:39 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/security/dataflow/ExternalAPIs.qll
> + * A `Callable` that is considered a "safe" external API from a security perspective.
`` `Callable` `` -> `callable`

2020-12-03 13:39 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/security/dataflow/ExternalAPIs.qll
> +    not exists(DataFlow::Node next | TaintTracking::localTaintStep(this, next)) and
This won't work in all cases. I suggest we instead add
```ql
private class SummarizedCallableSafe extends SafeExternalAPICallable {
  SummarizedCallableSafe() { this instanceof SummarizedCallable }
}
```

2020-12-03 13:39 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/security/dataflow/ExternalAPIs.qll
> +  /** Gets the called API `Callable`. */
`` `Callable` `` -> `callable`.

2020-12-03 13:39 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/security/dataflow/ExternalAPIs.qll
> +}
```suggestion
class UntrustedExternalAPIDataNode extends ExternalAPIDataNode {
  private UntrustedDataToExternalAPIConfig c;
  UntrustedExternalAPIDataNode() { c.hasFlow(_, this) }

  /** Gets a source of untrusted data which is passed to this external API data node. */
  DataFlow::Node getAnUntrustedSource() { c.hasFlow(result, this) }
}
```

2020-12-04 09:27 UTC, hvitved commented on csharp/ql/test/query-tests/Security Features/CWE-020/ExternalAPIsUsedWithUntrustedData.expected
> +| System.Collections.Specialized.NameValueCollection.get_Item(string) [qualifier] | 1 | 1 |
Interesting; we should model this (like we model dictionaries). (Not on this PR.)

2020-12-04 09:47 UTC, hvitved submitted a review, later dismissed

2020-12-04 12:29 UTC, tamasvajk commented
I rebased and pushed an extra commit to fix the CI check failure.

2020-12-04 13:28 UTC, hvitved approved these changes

2020-12-04 14:03 UTC, merged