Python: Add example of top-level module shadowing stdlib (v2)
github/codeql pull request #4693
Opened 2020-11-19 12:39 UTC by RasmusWL

This PR adds a test-case to show a specific kind of bad module resolution that happens when using `codeql database create`, since a locally defined module doesn't take precedence in module resolution. It turned out that we don't invoke the extractor in the same way when running our qltests, and that the way qltests behaves is more correct (compared with Python interpreter). Obvious fixes didn't work:

- Make extractor better: Hard, since you need to figure out exactly at what paths the Python interpreter is going to be invoked, so you can simulate adding that path as `sys.path[0]`.
- Change qltest extractor to match `codeql database create`: I naively attempted this, but it turned out to be a much bigger tasks than I am ready to take on right now.

So instead I changed the test manually to simulate what the result of `codeql database create` is (and even that was tricky). Reboot of https://github.com/github/codeql/pull/4655, but a bit more clear now that I've figured out what to do.

2020-11-19 13:57 UTC, RasmusWL commented
I accidentally included a change to a file that wasn't supposed to be part of this branch, and force pushed to remove this...

2020-11-26 22:43 UTC, tausbn requested changes
Nice and clear example of the bad behaviour. :+1:

I have made two suggestion with regard to typos, otherwise this looks good to me.

2020-11-26 22:43 UTC, tausbn commented on python/ql/test/library-tests/PointsTo/regressions/wrong/module-imports/conflict-stdlib/README.md
> +This test shows how we handle modules the shadow a module in the standard library.
```suggestion
This test shows how we handle modules that shadow a module in the standard library.
```

2020-11-26 22:43 UTC, tausbn commented on python/ql/test/library-tests/PointsTo/regressions/wrong/module-imports/conflict-stdlib/README.md
> +We manually replicate the behavior of `codeql database create --source-root <src-dir>`, which will use `-R <src-dir>`. By default, the way qltest invokes the extractor will cause different behavior.
```suggestion
We manually replicate the behavior of `codeql database create --source-root <src-dir>`, which will use `-R <src-dir>`. By default, the way qltest invokes the extractor will cause different behavior. Therefore, we also need to move our code outside of the top-level folder, and it lives in `code-invalid-package-name/` -- notice that if we use `code` as the folder name, the extractor will treat it as if there is a package called `code` (note, `codeql database create` would not treat the folder `code` as a package when `code` is used as the `--source-root`).
```
I inserted a missing verb, but I don't know if it was the intended verb.

2020-11-27 10:10 UTC, tausbn approved these changes

2020-11-27 10:32 UTC, merged