C#: Extract enum eunderlying type from IL
github/codeql pull request #4761
Opened 2020-12-01 16:24 UTC by tamasvajk

2020-12-01 16:24 UTC, tamasvajk commented
not to self: missing DB upgrade folder, new stats, tests

2020-12-03 14:24 UTC, tamasvajk commented
@hvitved The new enum test is failing. It looks like we're extracting different versions of CoreLib in CI, than what I have locally. Do you have any idea why that can be?

2020-12-07 21:28 UTC, tamasvajk commented
[Stats job](https://jenkins.internal.semmle.com/job/Stats/job/CSharp/12/)

2020-12-08 07:57 UTC, tamasvajk commented
> [Stats job](https://jenkins.internal.semmle.com/job/Stats/job/CSharp/12/)

[New stats job](https://jenkins.internal.semmle.com/job/Stats/job/CSharp/14/)

2020-12-08 11:06 UTC, hvitved requested changes
Minor comments, otherwise LGTM.

2020-12-08 11:06 UTC, hvitved commented on csharp/extractor/Semmle.Extraction.CIL/Entities/TypeDefinitionType.cs
> +                if ((field.Attributes & FieldAttributes.Static) != 0)
```suggestion
                if (field.Attributes.HasFlag(FieldAttributes.Static))
```

2020-12-08 11:06 UTC, hvitved commented on csharp/ql/src/semmle/code/cil/Types.qll
> +    result = any(IntType i)
```suggestion
    not cil_enum_underlying_type(this, _) and
    result instanceof IntType
```

2020-12-08 13:05 UTC, hvitved submitted a review, later dismissed

2020-12-08 13:05 UTC, hvitved commented
Let's run this past CSharp-Differences before merging.

2020-12-08 15:43 UTC, tamasvajk commented
I've rebased this PR, and pushed two extra commits (DB upgrade folder and change notes)

2020-12-09 07:15 UTC, tamasvajk commented
There are no changes in the diff job.

2020-12-09 08:52 UTC, hvitved approved these changes

2020-12-09 19:55 UTC, merged