Python: Disregard parameters to functions synthesised by the extractor for comprehensions
github/codeql pull request #5007
Opened 2021-01-24 14:40 UTC by yoff

Children of comprehensions were conidered parameters to the synthesised function and hence also `ParameterNode`s.
`ParameterNode` has an override of `GetEnclosingCallable` that becaomes empty, because the synthesised function is
not considered a `DataFlowCallable`. The fix taken is this PR is to not consider those nodes as `ParameterNode`s,
in line with the current approach of ignoring those synthesised functions in the data-flow layer. Alternative ideas
welcome.

It currently drops the number of inconsistency alerts of type `UniqueEnclosingCallable` on saltstack from 4026 to 614.﻿

2021-01-25 16:51 UTC, tausbn requested changes
This seems like a reasonable way of handling the inconsistency. Do we have (failing, non-consistency) tests that cover the parts that will be silently elided by making this fix?

2021-01-26 08:53 UTC, yoff commented
> Do we have (failing, non-consistency) tests that cover the parts that will be silently elided by making this fix?

Yes, for instance arguments after a starred argument [here](https://github.com/github/codeql/blob/main/python/ql/test/experimental/dataflow/coverage/argumentPassing.py#L87-L89).

2021-01-26 10:21 UTC, RasmusWL approved these changes
LGTM :+1:

> parameters appearing after a starred parameter.

also called keyword-only parameters :wink:

2021-01-26 10:22 UTC, RasmusWL commented
Hopefully we'll be able to support them (in some form) soon. Do we actually need to have call-graph resolution without points-to to be able to do this?

2021-01-26 10:31 UTC, yoff commented
> Hopefully we'll be able to support them (in some form) soon. Do we actually need to have call-graph resolution without points-to to be able to do this?

I think we just have to fish them out, ideally make the lower level provide this. But your idea of a ranking on top of the parameter list should work..

2021-01-26 10:53 UTC, tausbn approved these changes
Nice!

2021-01-26 11:53 UTC, merged