C#: Improve CFG to handle 'and' and 'or' patterns
github/codeql pull request #5018
Opened 2021-01-26 14:14 UTC by tamasvajk

Based on https://github.com/github/codeql/pull/4724 and https://github.com/github/codeql/pull/4660.

2021-01-27 12:39 UTC, hvitved requested changes
Looks great!

2021-01-27 12:39 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/exprs/Expr.qll
> +/** A binary or pattern. For example, `1 or 2`. */
`or` -> `` `or` ``

2021-01-27 12:39 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/exprs/Expr.qll
> +/** A binary and pattern. For example, `< 1 and > 2`. */
`and` -> `` `and` ``

2021-01-27 12:39 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/controlflow/internal/ControlFlowGraphImpl.qll
> +  private Element getAChild(Element p) {
Use this in `getAChildInScope`.

2021-01-28 10:43 UTC, hvitved submitted a review, later dismissed

2021-01-30 19:39 UTC, tamasvajk commented
The new pattern matching completion changes result in a lot of noise or false positives in the new constant condition check.

2021-01-31 15:24 UTC, hvitved commented
> The new pattern matching completion changes result in a lot of noise or false positives in the new constant condition check.

That should be fixed by the CFG changes I was working on, so happy to merge this now.

2021-01-31 15:24 UTC, hvitved approved these changes

2021-02-01 08:17 UTC, merged