Upgrade projects to .net 5
github/codeql pull request #5132
Opened 2021-02-10 09:20 UTC by tamasvajk

2021-02-25 09:13 UTC, hvitved requested changes
Very nice, just one trivial comment.

2021-02-25 09:13 UTC, hvitved commented on csharp/ql/src/semmle/code/cil/ConsistencyChecks.qll
> +      count(c.(Opcodes::Calli).getTargetType()) != 1 and c instanceof Opcodes::Calli
Remove `and c instanceof Opcodes::Calli`

2021-03-02 12:38 UTC, hvitved commented on csharp/ql/src/semmle/code/cil/ConsistencyChecks.qll
> +      count(c.(Opcodes::Calli).getTargetType()) != 1 and c instanceof Opcodes::Calli
D'oh, I had not seen the `count`; you are right in reverting the change, the conjunct is actually needed.

2021-03-02 20:58 UTC, tamasvajk commented
@hvitved Could you approve this PR? We can ignore the failing tests here, as they are passing on the corresponding internal PR.

2021-03-03 07:51 UTC, hvitved approved these changes

2021-03-03 11:47 UTC, merged