Python: Improve pyyaml support
github/codeql pull request #5152
Opened 2021-02-12 11:30 UTC by RasmusWL

2021-02-12 11:49 UTC, yoff submitted a review, later dismissed
LGTM

2021-02-12 19:48 UTC, felicitymay reviewed
Once small text suggestion - otherwise LGTM to me.

2021-02-12 19:48 UTC, felicitymay commented on python/change-notes/2021-02-10-yaml-more-loading-functions.md
> +* Improved modeling for the `PyYAML` PyPI package (imported as `yaml`), now supporting `safe_load`, `unsafe_load`, and `full_load` (as well as the `..._load_all` functions). In the current version of
Would this change work, to simplify "known to not be safe from":

```suggestion
* Improved modeling for the `PyYAML` PyPI package (imported as `yaml`), now supporting `safe_load`, `unsafe_load`, and `full_load` (as well as the `..._load_all` functions). In the current version of PyYAML (5.4.1), only `safe_load` is known to be vulnerable to code execution exploits. Calls to the other functions are now modeled as sinks of the _Deserializing untrusted input_ (`py/unsafe-deserialization`) query.
```

2021-02-15 09:53 UTC, RasmusWL commented on python/change-notes/2021-02-10-yaml-more-loading-functions.md
> +* Improved modeling for the `PyYAML` PyPI package (imported as `yaml`), now supporting `safe_load`, `unsafe_load`, and `full_load` (as well as the `..._load_all` functions). In the current version of
Thanks, I must have rewritten that once too many, and ended up absolutely botching it :laughing: The only one that is safe is `safe_load`, which is hopefully what the change note also says now :laughing:

2021-02-15 12:50 UTC, felicitymay reviewed
Small suggestion for the change notes. Otherwise the text changes LGTM.

2021-02-15 12:50 UTC, felicitymay commented on python/change-notes/2021-02-10-yaml-more-loading-functions.md
> +* Improved modeling for the `PyYAML` PyPI package (imported as `yaml`), now supporting `safe_load`, `unsafe_load`, and `full_load` (as well as the `..._load_all` functions). In the current version of
Suggest:

```suggestion
* Improved modeling of the `PyYAML` PyPI package (imported as `yaml`) now includes `safe_load`, `unsafe_load`, and `full_load` (as well as the `..._load_all` functions). In the current version of PyYAML (5.4.1), only `safe_load` is known to be safe from code execution exploits. Consequently, calls to the other functions are modeled as sinks of the _Deserializing untrusted input_ (`py/unsafe-deserialization`) query.
```

2021-02-15 13:38 UTC, RasmusWL commented on python/change-notes/2021-02-10-yaml-more-loading-functions.md
> +* Improved modeling for the `PyYAML` PyPI package (imported as `yaml`), now supporting `safe_load`, `unsafe_load`, and `full_load` (as well as the `..._load_all` functions). In the current version of
Thanks :+1:

2021-02-16 12:00 UTC, felicitymay commented on python/change-notes/2021-02-10-yaml-more-loading-functions.md
> +* Improved modeling for the `PyYAML` PyPI package (imported as `yaml`), now supporting `safe_load`, `unsafe_load`, and `full_load` (as well as the `..._load_all` functions). In the current version of
Thanks for the update. Clearly I should also have been concentrating harder when I reviewed too.

Content all LGTM now 👍🏻

2021-02-23 09:03 UTC, yoff requested changes
We might as well be completely precise and un-misunderstandable here..

2021-02-23 09:03 UTC, yoff commented on python/change-notes/2021-02-10-yaml-more-loading-functions.md
> +* Improved modeling of the `PyYAML` PyPI package (imported as `yaml`) now includes `safe_load`, `unsafe_load`, and `full_load` (as well as the `..._load_all` functions). In the current version of PyY
```suggestion
lgtm,codescanning
* Improved modeling of the `PyYAML` PyPI package (imported as `yaml`) now includes `safe_load`, `unsafe_load`, and `full_load` (as well as the `..._load_all` functions). In the current version of PyYAML (5.4.1), only `safe_load` and `safe_load_all` are known to be safe from code execution exploits. Consequently, calls to the other functions are modeled as sinks of the _Deserializing untrusted input_ (`py/unsafe-deserialization`) query.
```

2021-02-23 14:19 UTC, RasmusWL commented on python/change-notes/2021-02-10-yaml-more-loading-functions.md
> +* Improved modeling of the `PyYAML` PyPI package (imported as `yaml`) now includes `safe_load`, `unsafe_load`, and `full_load` (as well as the `..._load_all` functions). In the current version of PyY
sure thign

2021-02-23 18:57 UTC, yoff approved these changes
LGTM

2021-02-23 18:58 UTC, merged