C#: Split 'Context' class between CIL and source extraction
github/codeql pull request #5189
Opened 2021-02-16 21:09 UTC by tamasvajk

2021-02-24 12:47 UTC, hvitved requested changes
Looks really great! I only had one trivial remark.

2021-02-24 12:47 UTC, hvitved commented on csharp/extractor/Semmle.Extraction/Context.cs
> +            var a = duplicationGuard && IsEntityDuplicationGuarded(entity, out var loc) //CreateLocation(entity.ReportingLocation) is NonGeneratedSourceLocation loc
Remove comment

2021-02-24 15:23 UTC, tamasvajk commented
@hvitved I rebases this PR, and fixed your finding.

2021-02-25 08:42 UTC, hvitved approved these changes

2021-02-25 13:28 UTC, merged