Python: Port bind to all interfaces query
github/codeql pull request #5243
Opened 2021-02-23 15:05 UTC by RasmusWL

Draft PR while validating whether the ported query can find all the interesting results.

2021-03-02 07:58 UTC, RasmusWL commented
Results looked OK.

Performance looked worrying, but now I realize it seems like the cost of type-tracking has moved from being "part of" path injection, and being moved to my new query.

Query | old | new | diff
-- | --: | --: | --:
Security/CVE-2018-1281/BindToAllInterfaces.ql | 18 | 427 | +409
Security/CWE-022/PathInjection.ql | 709 | 328 | -381

If we even out this bit, `409 - 381 = 28`, we're at 10 seconds more expensive (in total over all 6 projects) than the old query, and that does not seem too worrying. Opening up the PR to be merged :+1:

2021-03-05 12:26 UTC, tausbn requested changes
A few comments and suggestions. Apart from that this looks good. :+1:

2021-03-05 12:26 UTC, tausbn commented on python/ql/src/Security/CVE-2018-1281/BindToAllInterfaces.ql
> +  address = vulnerableAddressTuple(hostname)
Maybe just `bindCall.getArg(0) = vulnerableAddressTuple(hostname)`?
(Would have made it as a suggestion, but the interface did not let me. :cry:)

2021-03-05 12:26 UTC, tausbn commented on python/ql/src/experimental/Security-old-dataflow/CVE-2018-1281/BindToAllInterfaces.ql
> + * @id py/bind-socket-all-network-interfaces
```suggestion
```
To match the changes in #5279

2021-03-05 12:26 UTC, tausbn commented on python/ql/src/Security/CVE-2018-1281/BindToAllInterfaces.ql
> +/** Gets a reference to tuple containing a hostname as the first element, that cane be used to bind to all interfaces. */
```suggestion
/** Gets a reference to tuple containing a hostname as the first element, that can be used to bind to all interfaces. */
```

2021-03-05 16:09 UTC, RasmusWL commented on python/ql/src/experimental/Security-old-dataflow/CVE-2018-1281/BindToAllInterfaces.ql
> + * @id py/bind-socket-all-network-interfaces
thanks :+1:

2021-03-05 16:11 UTC, RasmusWL commented on python/ql/src/Security/CVE-2018-1281/BindToAllInterfaces.ql
> +  address = vulnerableAddressTuple(hostname)
I agree. I have a slight preference for this setup, since it more directly calls out the address argument... although it probably should have been called `addressArg` (goes off to update PR)

2021-03-05 16:16 UTC, RasmusWL commented on python/ql/src/Security/CVE-2018-1281/BindToAllInterfaces.ql
> +  address = vulnerableAddressTuple(hostname)
Ha! I had actually done this locally, but I just never pushed the commit :smile: (I didn't quite understand what was going on to be honest)

2021-03-07 07:11 UTC, yoff submitted a review, later dismissed
LGTM

2021-03-12 11:03 UTC, shati-patel reviewed
Regarding https://github.com/github/codeql/pull/5243#discussion_r588236183

> Also, I would put "which" instead of "that", but I know you disagree about this and I don't have the energy to argue this right now.
Perhaps @github/docs-content-codeql could weigh in on what's more appropriate?

There is technically a rule to use "that" when you're providing necessary information, and "which" when you're adding parenthetical information: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/t/that-vs-which

In practice, they're used interchangeably, so I won't worry about it too much (as long as the meaning is clear!



Overall, this PR looks good from a docs point of view (just gave the change note/code comments a quick look).

2021-03-12 12:21 UTC, tausbn commented
> There is technically a rule to use "that" when you're providing necessary information, and "which" when you're adding parenthetical information: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/t/that-vs-which

I note that that style guide indicates that there should never be a comma before `that`, so either way there's something that needs fixing. :slightly_smiling_face: 

In this case, I think a better way of rewriting it would be

"Gets a reference to a tuple for which the first element is a hostname that can be used to bind to all interfaces."

Does this sound okay to you?

2021-03-12 12:31 UTC, shati-patel commented
> In this case, I think a better way of rewriting it would be
> 
> "Gets a reference to a tuple for which the first element is a hostname that can be used to bind to all interfaces."
> 
> Does this sound okay to you?

Thanks @tausbn - that rewrite looks good! ✨

2021-03-12 13:28 UTC, tausbn commented on python/ql/src/Security/CVE-2018-1281/BindToAllInterfaces.ql
> +/** Gets a reference to a tuple containing a hostname as the first element, that can be used to bind to all interfaces. */
```suggestion
/** Gets a reference to a tuple for which the first element is a hostname that can be used to bind to all interfaces. */
```

2021-03-12 13:28 UTC, tausbn commented on python/ql/src/Security/CVE-2018-1281/BindToAllInterfaces.ql
> +/** Gets a reference to a tuple containing a hostname as the first element, that can be used to bind to all interfaces. */
```suggestion
/** Gets a reference to a tuple for which the first element is a hostname that can be used to bind to all interfaces. */
```

2021-03-12 13:29 UTC, tausbn approved these changes

2021-03-12 15:04 UTC, merged