[Java] CWE-094: Query to detect Groovy Code Injections
github/codeql pull request #5467
Opened 2021-03-21 14:35 UTC by p0wn4j

If a Groovy script is built using attacker-controlled data and then evaluated, then it may allow the attacker to achieve Remote Code Execution.
You can execute Groovy code in Java by using these classes:
GroovyShell
GroovyClassLoader
groovy.util.Eval

2021-03-22 15:27 UTC, JLLeitschuh commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +</qhelp>
Reference worth pointing to:
https://blog.orange.tw/2019/02/abusing-meta-programming-for-unauthenticated-rce.html

2021-03-22 22:54 UTC, intrigus-lgtm commented
Did you find any application that has this issue?
My (private) [run](https://lgtm.com/query/2058482093304276429/) on lgtm.com reveals nothing that looks like a true positive.
It look like you've got some false positives like in `apache/camel`:
Calling `Class.newInstance()` but not on a groovy created class.

2021-03-26 20:10 UTC, p0wn4j commented
I fixed false positive issue on GroovyClassLoader sink, also found some hits on these repositories:
https://github.com/yangshj/springboot-learn
https://github.com/doctording/springgroovytest
https://github.com/double-bin/groovy-script-example
https://github.com/plum-wine/spring-learn
https://github.com/EwingTsai/spring-boot-faster

2021-04-09 12:25 UTC, owen-mc requested changes
This review is almost entirely about documentation, style and formatting, I'm afraid. As well as the comments I've made, the formatting tests are failing for the `ql` and `qll` files - please run the autoformatter on them. Note that we use two space indentation in CodeQL.

2021-04-09 12:25 UTC, owen-mc commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +</example>
It would be good to include another sample with the problems fixed. See https://github.com/github/codeql/blob/5151a528ac6d7b4b54543a6c36bbc49d32a0e62b/java/ql/src/experimental/Security/CWE/CWE-489/devMode.qhelp for an example of this being done.

2021-04-14 10:06 UTC, owen-mc requested changes
Thanks, it's looking a lot better. A few more minor points.

2021-04-14 10:08 UTC, owen-mc commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.ql
> +import semmle.code.java.dataflow.FlowSources
I believe there is no need to import FlowSources as `GroovyInjectionLib` imports it.

2021-04-14 14:55 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +If it is not possible, use sandbox solution. Also you must take care about Groovy
```suggestion
If this is not possible, use a sandbox solution. Also you must take care about Groovy
```

2021-04-14 14:55 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +compile-time metaprogramming RCE case. It is possible to achieve to RCE by only compiling
```suggestion
compile-time metaprogramming leading to RCE. It is possible to achieve to RCE by only compiling
```

2021-04-14 14:55 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +The following example uses sandbox protection before running Groovy script.
```suggestion
The following example uses sandbox protection before running a Groovy script.
```

2021-04-14 14:55 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +  Scripting and sandboxing in JVM:
```suggestion
  Scripting and sandboxing in a JVM environment:
```

2021-04-14 14:55 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +  Safe run Groovy scripts (without metaprogramming protection):
All these citations should be of the form `Author: <a href=...>Title</a>`

2021-04-14 14:55 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionLib.qll
> +private class GroovyShellMethods extends Method {
```suggestion
private class GroovyShellMethod extends Method {
```

2021-04-14 14:55 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionLib.qll
> +    exists(GroovyShellMethodAccess ma, Argument first |
```suggestion
    exists(GroovyShellMethodAccess ma, Argument firstArg |
```

2021-04-14 14:55 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionLib.qll
> +    )
```suggestion
    result = this.getArgument(this.getNumArgument() - 1)
```

2021-04-14 14:55 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionLib.qll
> + * Groovy supports compile-time metaprogramming, only calling parseClass
```suggestion
 * Groovy supports compile-time metaprogramming, so just calling the `parseClass`
```

2021-04-14 14:55 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +Source code is used from https://melix.github.io/blog/2015/03/sandboxing.html.
This code is licenses CC-BY-NC-SA, where NC is for Non-Commercial. While this is an open repository, CodeQL is a commercial product, so I am unsure if this is allowed. Could you replace their code by either (a) excluding the sandboxing .groovy file and simply explaining that some sandboxing tool exists, or (b) replacing the code from that site for code that conveys the same idea but which is of your own devising.

2021-04-14 14:55 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovySandbox.java
> +        conf.addCompilationCustomizers(astcz);
This example is really quite long. Can you abbreviate it with `// ...` comments to keep just the essential parts for illustrating your point?

2021-04-15 21:29 UTC, p0wn4j commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +Source code is used from https://melix.github.io/blog/2015/03/sandboxing.html.
The whole sandbox logic is in that .groovy file. Can I only write explanation in qhelp file without java code example?
Also there is no a silver-bullet solution for Groovy code execution protection, the reader must do additional research besides qhelp file explanation.

2021-04-16 09:20 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +Source code is used from https://melix.github.io/blog/2015/03/sandboxing.html.
If the code required is long and complicated perhaps point to it as a reference rather than copy-paste it into our qhelp.

2021-04-19 10:43 UTC, smowton reviewed
Mostly looks good, just needs some tidying. Shoot for a 5-line bad / unsafe example and a corresponding 10-line good / safe example if possible; the current versions are signicantly too long.

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +compile-time metaprogramming leading to RCE case. It is possible to achieve to RCE by only compiling
```suggestion
If this is not possible, use a sandbox solution. Developers must also take care that Groovy
compile-time metaprogramming can also lead to RCE: it is possible to achieve to RCE by compiling
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +a Groovy script (see Abusing Meta Programming for Unauthenticated RCE!).
```suggestion
a Groovy script (see the article "Abusing Meta Programming for Unauthenticated RCE!" linked below).
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +Groovy SecureASTCustomizer customizer allows securing source code by controlling what code constructs are permitted.
```suggestion
Groovy's SecureASTCustomizer allows securing source code by controlling what code constructs are permitted. 
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +So it’s very easy for a malicious attacker, to bypass many of the checks
```suggestion
This makes it very easy for an attacker to bypass many of the intended checks
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +So besides SecureASTCustomizer, you must also make runtime checks before calling the Groovy methods
```suggestion
Therefore, besides SecureASTCustomizer, runtime checks are also necessary before calling Groovy methods
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +Also you can use blacklist method: exclude unwanted classes from being loaded into the JVM.
```suggestion
It is also possible to use a block-list method, excluding unwanted classes from being loaded by the JVM. 
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +This method is not always preferred, because blacklists can be bypassed by unexpected values.
```suggestion
This method is not always recommended, because block-lists can be bypassed by unexpected values.
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +The following example uses classloader blacklist approach for dangerous classes loading exclusion.
```suggestion
The following example uses classloader block-list approach to exclude loading dangerous classes.
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBad.java
> +        } catch (Exception e) {
You could make these examples briefer by removing the try/catch block and showing them in the context of a method that throws `Exception`.

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBad.java
> +    protected void doPost(HttpServletRequest request, HttpServletResponse response)
Name the test methods `injectionViaClassLoader`, `injectionViaEval` etc (they can still take an `HttpServletRequest` as a parameter to act as an untrusted source) -- the HTTP method is irrelevant here

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBlacklist.java
> +    }
```suggestion
```

Not needed in an example

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBlacklist.java
> +    static void runWithGroovyClassLoader() throws Exception {
These are strange examples in that they are inherently safe as they don't use any untrusted user input. Instead, your clean / safe examples should be as similar as possible to your unsafe examples, adding just what is necessary to avoid the risk of RCE.

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBlacklist.java
> +        Object result = scriptClass.getDeclaredMethod("hello_world", new Class[]{}).invoke(scriptInstance, new Object[]{});
Is this example actually safe? It reads like the one below without use of sandboxing? If so, omit it here and show only the good case (the file `GroovyInjectionBad.java` already shows the bad case)

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionLib.qll
> + * i.e. `new GroovyCodeSource(tainted, ...)`.
```suggestion
 * Holds if `fromNode` to `toNode` is a dataflow step from a tainted string to a `GroovyCodeSource` instance,
 * i.e. `new GroovyCodeSource(tainted, ...)`.
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionLib.qll
> + * A sink for Groovy Injection vulnerability via Eval class.
```suggestion
 * A sink for Groovy Injection via the `Eval` class.
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionLib.qll
> + * A sink for Groovy Injection vulnerability via GroovyClassLoader class.
```suggestion
 * A sink for Groovy Injection via the `GroovyClassLoader` class.
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBlacklist.java
> +    }
```suggestion
    /* override `loadClass` here to prevent loading sensitive classes, such as `java.lang.System` */
    /* Note we must also block `groovy.transform.ASTTest`, `groovy.lang.GrabConfig` and `org.buildobjects.process.ProcBuilder` to prevent compile-time RCE. */
    
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBlacklist.java
> +        System.out.println("End runWithGroovyClassLoader");
```suggestion
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBlacklist.java
> +        Class<?> scriptClass = groovyClassLoader.parseClass(code);
```suggestion
        GroovyClassLoader groovyClassLoader = new GroovyClassLoader();
        Class<?> scriptClass = groovyClassLoader.parseClass(untrusted.getHeader("foo"));
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBlacklist.java
> +    }
```suggestion
    static void runWithSandboxGroovyClassLoader() throws Exception {
        // GOOD: route all class-loading via sand-boxing classloader.
        SandboxGroovyClassLoader classLoader = new GroovyClassLoader(new SandboxGroovyClassLoader());
        Class<?> scriptClass = classLoader.parseClass(untrusted.getQueryString());
        Object scriptInstance = scriptClass.newInstance();
        Object result = scriptClass.getDeclaredMethod("bar", new Class[]{}).invoke(scriptInstance, new Object[]{});
        
        // GOOD: when using the GroovyShell class, ensure the thread's context classloader enforces a sandbox.
        Thread.currentThread().setContextClassLoader(classLoader);          
        (new GroovyShell()).parse(untrusted.getQueryString()).run();        
    }
```

2021-04-19 10:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBlacklist.java
> + */
```suggestion

```

2021-04-19 10:54 UTC, intrigus-lgtm commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +compile-time metaprogramming leading to RCE case. It is possible to achieve to RCE by only compiling
it is possible to achieve **to** RCE by compiling
Remove the second **to**?

2021-04-19 11:18 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +compile-time metaprogramming leading to RCE case. It is possible to achieve to RCE by only compiling
Oops, done

2021-04-20 10:49 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +<sample src="GroovyInjectionBlacklist.java" />
```suggestion
<sample src="GroovyInjectionBlocklist.java" />
```
(and rename the file)

2021-04-20 10:49 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +Groovy's SecureASTCustomizer allows securing source code by controlling what code constructs are permitted.
```suggestion
Groovy's <code>SecureASTCustomizer</code> allows securing source code by controlling what code constructs are permitted. 
```
(and similarly other uses)

2021-04-20 10:49 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBad.java
> +
```suggestion
```

2021-04-20 10:49 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBad.java
> +
```suggestion
```

2021-04-20 10:49 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBad.java
> +
```suggestion
```

2021-04-20 10:49 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjectionBad.java
> +
```suggestion
```

2021-04-20 11:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +Therefore, besides SecureASTCustomizer, runtime checks are also necessary before calling Groovy methods
```suggestion
Therefore, besides <code>SecureASTCustomizer</code>, runtime checks are also necessary before calling Groovy methods
```

2021-04-20 11:43 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-094/GroovyInjection.qhelp
> +The fundamental problem is that Groovy is a dynamic language, yet SecureASTCustomizer works by looking at Groovy AST statically.
```suggestion
The fundamental problem is that Groovy is a dynamic language, yet <code>SecureASTCustomizer</code> works by looking at Groovy AST statically.
```

2021-04-20 11:46 UTC, smowton submitted a review, later dismissed

2021-04-20 12:24 UTC, p0wn4j commented
Which of tests are failing? Locally my tests are runnning ok.

2021-04-20 13:00 UTC, smowton commented
Was QL autoformat. Pushed a fix.

2021-04-20 13:04 UTC, p0wn4j commented
Ok thanks :)

2021-04-20 13:48 UTC, smowton approved these changes

2021-04-20 13:49 UTC, merged