Python: Use API graphs in Fabric model
github/codeql pull request #5668
Opened 2021-04-13 15:00 UTC by tausbn

Because of the modelling of decorators, I wasn't able to get rid of all of the bespoke type trackers, but the ones that remain have been converted to use `LocalSourceNode` instead.

(And we should be able to get rid of them once we add defs to the API graph.)

No change note required -- behaviour should be unchanged.

2021-04-14 08:32 UTC, RasmusWL requested changes
To keep consistency with my review of https://github.com/github/codeql/pull/5669, I've requested similar changes here.

I think it's fair to say that the formatting of `classRef()` didn't bother me as much as in the other PR, but I think it will still be a good improvement once we unwrap helper predicates (so `connection().getMember("Connection")` becomes `API::moduleImport("fabric").getMember("connection").getMember("Connection")`

2021-04-14 08:32 UTC, RasmusWL commented on python/ql/src/semmle/python/frameworks/Fabric.qll
> +        DataFlow::LocalSourceNode instance() { result = instance(DataFlow::TypeTracker::end()) }
```suggestion
        DataFlow::Node instance() { instance(DataFlow::TypeTracker::end()).flowsTo(result) }
```

2021-04-14 08:32 UTC, RasmusWL commented on python/ql/src/semmle/python/frameworks/Fabric.qll
> +          result in [fabric().getMember("Connection"), connection().getMember("Connection")]
```suggestion
          result = fabric().getMember("Connection")
          or
          result = connection().getMember("Connection")
```

2021-04-14 08:32 UTC, RasmusWL commented on python/ql/src/semmle/python/frameworks/Fabric.qll
> +            this in [group().getMember("ThreadingGroup"), fabric().getMember("ThreadingGroup")]
```suggestion
            this = group().getMember("ThreadingGroup")
            or
            this = fabric().getMember("ThreadingGroup")
```

2021-04-14 08:32 UTC, RasmusWL commented on python/ql/src/semmle/python/frameworks/Fabric.qll
> +            this in [group().getMember("SerialGroup"), fabric().getMember("SerialGroup")]
```suggestion
            this = group().getMember("SerialGroup")
            or
            this = fabric().getMember("SerialGroup")
```

2021-04-16 09:37 UTC, tausbn commented
Thank you for your suggestions. I have applied them all. I think you're right that even though `instance` is an internally-used method only, it's useful for its interface to be consistent across our models.

2021-04-16 12:27 UTC, RasmusWL approved these changes
:+1:

2021-04-16 12:27 UTC, merged