[Java] CWE-094: Query to detect OS Command Injection by JSch library
github/codeql pull request #5710
Opened 2021-04-17 23:00 UTC by p0wn4j

JSch is a pure Java implementation of SSH2. JSch allows you to connect to a sshd server and use port forwarding, X11 forwarding, file transfer, command execution, etc. 
If an attacker can control the command that is going to be executed on a sshd server, it can lead an attacker to Remote Code Execution on that server.
Found hits on these repos:
https://github.com/KingLai23/Puzzle
https://github.com/manuelacalvo/DATATourisme

2021-04-21 14:05 UTC, owen-mc requested changes
You can simplify by making `setCommand` the sink. I can't think of any good reason why code would call `setCommand` apart from that they intend to call `connect` soon afterwards.

This shouldn't be a stand-alone query. It should be adding some sinks to `ExecTainted`, the existing command injection query. That query isn't very easy to extend at the moment, so I have [made a PR](https://github.com/github/codeql/pull/5746) to fix that.

2021-04-21 14:18 UTC, p0wn4j commented on java/ql/src/experimental/Security/CWE/CWE-094/JSchOSInjection.qhelp
> +Validating against a whitelist of permitted values.
Ok thanks :)
But in this PR https://github.com/github/codeql/pull/5746 classes are not from experemental queries, can I extend ExecTainted sink?

2021-04-21 14:24 UTC, p0wn4j commented on java/ql/src/experimental/Security/CWE/CWE-094/JSchOSInjectionSanitized.java
> +        //GOOD: Validate user the input.
I think there maybe cases where just validation with regexp is not enough, that's why both of checks will make more secure.

2021-04-21 15:18 UTC, owen-mc commented on java/ql/src/experimental/Security/CWE/CWE-094/JSchOSInjection.qhelp
> +Validating against a whitelist of permitted values.
I think you can put the classes extending `ExecCallable` into a separate `qll` file, then make a copy of `ExecTainted.ql` which also imports that `qll` file.

2021-04-22 09:16 UTC, owen-mc commented
@p0wn4j [My PR](https://github.com/github/codeql/pull/5746) has been merged now, so you can extend the `ExecTainted` query easily.

2021-04-26 09:22 UTC, owen-mc commented on java/ql/src/experimental/Security/CWE/CWE-094/JSchOSInjectionSanitized.java
> +        //GOOD: Validate user the input.
In that case I don't see the point in having the first check.

2021-04-26 09:48 UTC, owen-mc reviewed
That looks great. I've checked and the new version gets the same hits on LGTM as the old one. The other, more minor, comments from my previous review still stand.

2021-04-26 09:49 UTC, owen-mc commented
@p0wn4j Do you intend to make a bug bountry submission for this contribution?

2021-04-26 09:57 UTC, p0wn4j commented
Yes I want to make a bug bounty submission.

2021-04-26 10:31 UTC, owen-mc commented
@p0wn4j Great, that addresses all of the review comments. When you make a bug bountry submission this will be ready to pass to the next stage.

2021-04-26 10:33 UTC, p0wn4j commented
OK, thanks for the review  :)

2021-04-26 10:56 UTC, p0wn4j commented
> That looks great. I've checked and the new version gets the same hits on LGTM as the old one. The other, more minor, comments from my previous review still stand.

I have copied ExecTainted.ql, ExecCommon.qll from java/ql/src/Security/CWE/CWE-078/ path.

2021-04-26 16:12 UTC, owen-mc commented
https://lgtm.com/query/4250181641930060813/

2021-05-10 15:12 UTC, merged