Java: Unsafe RMI deserialization
github/codeql pull request #5818
Opened 2021-05-01 11:45 UTC by artem-smotrakov

RMI uses the default Java serialization mechanism (in other words, `ObjectInputStream`) to pass parameters in remote method invocations. If a remote method accepts complex parameters, then a remote attacker can send a malicious serialized object as one of the parameters. The malicious object gets deserialized without any check on the incoming data. In the worst case, it may let the attacker run arbitrary code remotely.

I'd like to propose a new experimental query that looks for deserialization vulnerabilities in remote objects registered in am RMI registry.

Here are several issue found by the query:
* [RMI deserialization vulnerability in PeerUnit/mock-dht](https://github.com/PeerUnit/mock-dht/issues/2)
* [Alerts on LGTM](https://lgtm.com/query/670635704339542643/)

2021-05-02 00:16 UTC, Marcono1234 commented on java/ql/src/experimental/Security/CWE/CWE-502/RmiUnsafeDeserialization.ql
> +  type.(RefType).getASupertype*() instanceof TypeRemote and
If I understand the documentation of [`Remote`](https://docs.oracle.com/en/java/javase/16/docs/api/java.rmi/java/rmi/Remote.html) correctly, only methods declared in an interface which directly extends `Remote` are remote methods.
Therefore the following would probably not be vulnerable (though I am not sure):
```java
interface RemoteInterface extends Remote {
  void doSomething(int);
}

class RemoteClass implements RemoteInterface {
  @Override
  public void doSomething(int) {}

  // Not vulnerable
  public void doSomething(Object o) {}
}
```

2021-05-02 00:16 UTC, Marcono1234 commented on java/ql/src/experimental/Security/CWE/CWE-502/RmiUnsafeDeserialization.ql
> +select call, "Unsafe deserialization with RMI in '" + call.getVulnerableMethod() + "' method"
Might be useful to include `getVulnerableMethod()` in the result set to allow the user to easily navigate to the method:
```suggestion
from UnsafeRmiBinding call, Method vulnerableMethod
where vulnerableMethod = call.getVulnerableMethod()
select call, "Unsafe deserialization with RMI in '$@' method", vulnerableMethod, vulnerableMethod.getStringSignature()
```

2021-05-02 00:20 UTC, Marcono1234 commented on java/ql/src/experimental/Security/CWE/CWE-502/RmiUnsafeDeserialization.ql
> +private class ObjectInputStream extends RefType {
Could use more specific type here:
```suggestion
private class ObjectInputStream extends Class {
```

2021-05-02 00:20 UTC, Marcono1234 commented on java/ql/src/experimental/Security/CWE/CWE-502/RmiUnsafeDeserialization.ql
> +  type.(RefType).getASupertype*() instanceof TypeRemote and
Could make the predicate parameter more specific:
```suggestion
private Method getVulnerableMethod(RefType type) {
  type.getASupertype*() instanceof TypeRemote and
```

2021-05-13 10:40 UTC, pwntester requested changes

2021-05-13 10:40 UTC, pwntester commented on java/ql/src/experimental/Security/CWE/CWE-502/RmiSafeRemoteObject.java
> +        registry.bind("unsafe", new RemoteObjectImpl());
seems like this should be "safe"

2021-05-17 09:35 UTC, artem-smotrakov commented on java/ql/src/experimental/Security/CWE/CWE-502/RmiUnsafeDeserialization.ql
> +  type.(RefType).getASupertype*() instanceof TypeRemote and
Good catch! I'll update the query. Thanks!

2021-05-17 09:35 UTC, artem-smotrakov commented on java/ql/src/experimental/Security/CWE/CWE-502/RmiUnsafeDeserialization.ql
> +select call, "Unsafe deserialization with RMI in '" + call.getVulnerableMethod() + "' method"
Makes sense to me. Thanks for the suggestion!

2021-05-17 09:38 UTC, artem-smotrakov commented on java/ql/src/experimental/Security/CWE/CWE-502/RmiUnsafeDeserialization.ql
> +private class ObjectInputStream extends RefType {
Sure, I can use `Class` here. Do you know whether it would make the query faster or not?

2021-05-17 09:44 UTC, artem-smotrakov commented
@Marcono1234 @pwntester Thanks for the review! I'll address your comments soon. I am currently checking if a couple of other sinks and sanitizers from `UnicastRemoteObject` and `Activatable`.

2021-05-17 16:27 UTC, Marcono1234 commented on java/ql/src/experimental/Security/CWE/CWE-502/RmiUnsafeDeserialization.ql
> +private class ObjectInputStream extends RefType {
Using the most specific types is one recommendation of the [CodeQL documentation](https://codeql.github.com/docs/writing-codeql-queries/troubleshooting-query-performance/#use-specific-types).
Though I am not sure if there is actually a notable performance improvement, or how big the improvement will be, might be best to start a [discussion](https://github.com/github/codeql/discussions) if you want to get more detailed information from the maintainers.

2021-05-23 11:29 UTC, artem-smotrakov commented
I found out that it is possible to set a deserialization filter by calling `UnicastRemoteObject.exportObject()`. I've updated the query to cover it. The query now use a taint-tracking config. The predicate `isAdditionalTaintStep()` breaks the data flow if `exportObject()` called without a filter.

The query is ready for review.

2021-05-27 13:53 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-502/UnsafeDeserializationRmi.ql
> +          .hasQualifiedName("java.io", "ObjectInputFilter") and
Simpler to check the parameter type than to walk the class hierarchy from the actual argument type

2021-05-27 13:53 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-502/UnsafeDeserializationRmi.qhelp
> +The filter can be set by with <code>ObjectInputFilter.Config.setSerialFilter(ObjectInputFilter)</code> method,
Note that this query doesn't check for either of these mitigations

2021-05-28 12:59 UTC, artem-smotrakov commented on java/ql/src/experimental/Security/CWE/CWE-502/UnsafeDeserializationRmi.qhelp
> +The filter can be set by with <code>ObjectInputFilter.Config.setSerialFilter(ObjectInputFilter)</code> method,
Correct, it doesn't. I thought about covering these mitigations in the query. To prevent deserialization attacks here, `ObjectInputFilter.Config.setSerialFilter()` should be called before actual RMI calls happen. I am not sure whether this check can be implemented with CodeQL or not. It is even more complicated with the `jdk.serialFilter` property. The property has to be set before the classes for deserialization mechanism (`ObjectInputStream` and others) are loaded because the property is read only once when the mechanism is accessed for the first time.

I'd prefer to keep these mitigations here because they are still valid if used correctly.

Please let me know if you have an idea how to reliably check there mitigations in the query.

2021-05-28 12:59 UTC, artem-smotrakov commented on java/ql/src/experimental/Security/CWE/CWE-502/UnsafeDeserializationRmi.ql
> +          .hasQualifiedName("java.io", "ObjectInputFilter") and
Good point. I'll update the query.

2021-05-28 14:12 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-502/UnsafeDeserializationRmi.qhelp
> +The filter can be set by with <code>ObjectInputFilter.Config.setSerialFilter(ObjectInputFilter)</code> method,
Just noting in the qhelp that these are valid mitigations but the query isn't sensitive to them is enough

2021-05-29 07:34 UTC, artem-smotrakov commented
Thanks for the comments @smowton ! I've addressed them and also fixed a few errors in the qhelp. `codeql generate query-help` now works fine.

2021-06-01 09:14 UTC, smowton approved these changes

2021-06-01 09:14 UTC, smowton commented on java/ql/src/experimental/Security/CWE/CWE-502/UnsafeDeserializationRmi.qhelp
> +Use only strings and primitive types in parameters of remote objects.
```suggestion
Use only strings and primitive types for parameters of remotely invokable methods.
```

2021-06-11 12:43 UTC, smowton approved these changes
Guh, sorry for the delay, didn't notice you apply that change.

2021-06-11 12:43 UTC, merged

2021-06-12 08:54 UTC, artem-smotrakov commented
> Guh, sorry for the delay, didn't notice you apply that change.

No problem. Thanks for the review!