C#: Migrate SQL sinks to CSV format
github/codeql pull request #6196
Opened 2021-07-01 11:22 UTC by tamasvajk

2021-09-14 12:57 UTC, hvitved requested changes
LGTM

2021-09-14 12:57 UTC, hvitved commented on csharp/ql/lib/semmle/code/csharp/frameworks/Sql.qll
> +/** A construction of an known `IDbCommand` object. */
a known

2021-09-16 07:56 UTC, hvitved submitted a review, later dismissed

2021-09-17 08:23 UTC, tamasvajk commented
@hvitved Thanks for the approval. I've rebased this PR to fix merge conflicts after the ServiceStack PR got merged.

2021-09-17 12:11 UTC, hvitved approved these changes

2021-09-17 12:36 UTC, merged