JS: enable unicode support in the Python ReDoS query
github/codeql pull request #6250
Opened 2021-07-11 19:31 UTC by erik-krogh

Version 2.5.7 of the CodeQL CLI has been released, which added support for the `toUnicode` method ([Changelog](https://github.com/github/codeql-cli-binaries/blob/main/CHANGELOG.md)).  

We can therefore safely enable the unicode parsing in the ReDoS query.

2021-07-12 12:18 UTC, RasmusWL requested changes
Besides these minor changes making it more obvious that we're using member-predicates, it looks good to me. Thanks for adding those test as well :+1:

2021-07-12 12:18 UTC, RasmusWL commented on python/ql/src/semmle/python/RegexTreeView.qll
> +    exists(int codepoint | codepoint = sum(getHexValueFromUnicode(_)) |
```suggestion
    exists(int codepoint | codepoint = sum(this.getHexValueFromUnicode(_)) |
```

2021-07-12 12:18 UTC, RasmusWL commented on python/ql/src/semmle/python/RegexTreeView.qll
> +    exists(string hex, string char | hex = getText().suffix(2) |
```suggestion
    this.isUnicode() and
    exists(string hex, string char | hex = this.getText().suffix(2) |
```

2021-07-12 16:28 UTC, RasmusWL approved these changes
Nice :+1:

Running performance test in https://github.com/dsp-testing/RasmusWL-dca/issues/27 , so let us not merge before that looks good :+1:

2021-07-12 16:36 UTC, tausbn commented
> Running performance test in [dsp-testing/RasmusWL-dca#27](https://github.com/dsp-testing/RasmusWL-dca/issues/27) , so let us not merge before that looks good

Good idea. :+1:
We also don't have an official tag for `codeql-cli/v2.5.7`, so it might cause fewer headaches if we wait until that has been created. (I know that in principle anything untagged just lives on the bleeding edge, but once the tag has been created, there's really nothing to discuss.)

2021-07-13 12:42 UTC, RasmusWL commented
No performance problems. I don't think we're in a hurry with this one, so we can wait for the new tag if that's better.

2021-07-14 08:08 UTC, erik-krogh commented
The [`codeql-cli/v2.5.7`](https://github.com/github/codeql/tree/codeql-cli/v2.5.7) tag has been created, so I'm merging.

2021-07-14 08:09 UTC, merged