C#: Remove type args/params from generic type names in extractor
github/codeql pull request #6268
Opened 2021-07-13 07:44 UTC by tamasvajk

2021-07-14 10:22 UTC, hvitved requested changes
We should also generate a DB upgrade script for adjusting the third column of the `types` relation.

2021-07-14 10:22 UTC, hvitved commented on csharp/extractor/Semmle.Extraction.CSharp/SymbolExtensions.cs
> +                cx.Extractor.Logger.Log(Util.Logging.Severity.Debug, $"Found generic type '{namedType.MetadataName}' with type arguments '{args}', skipping type arguments in type name.");
Is this debug statement really needed?

2021-07-14 10:22 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/Type.qll
> +  string getNameWithoutBrackets() { types(this, _, result) }
I suggest we deprecate `getNameWithoutBrackets`, and replace the body of `getUndecoratedName` with `types(this, _, result)`.

2021-07-14 10:22 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/Generics.qll
> +      types(this, _, undecorated) and
Use `GetUndecoratedName` instead.

2021-07-14 10:22 UTC, hvitved commented on csharp/ql/src/semmle/code/csharp/Generics.qll
> +      types(this, _, undecorated) and
Use `GetUndecoratedName` instead.

2021-07-14 21:19 UTC, tamasvajk commented
@hvitved I adjusted this PR based on your feedback. This is my first upgrade script, so please double check. I've ran the DB upgrade on a dummy DB, which was extracted with the previous version of the extractor, and I could query the generic types afterwards.

2021-07-15 13:33 UTC, hvitved submitted a review, later dismissed
The upgrade script looks correct to me. I have approved the PR, but please do not merge before the `rc/3.2` release branch has been created, as there is no need for this change to go into the release.

2021-08-04 10:40 UTC, tamasvajk commented
Diff job: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/1235/

2021-08-09 08:31 UTC, tamasvajk commented
Started a new diff job: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/1242/

2021-08-10 11:29 UTC, tamasvajk commented
new diff job to check useless upcast performance: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/1245/

2021-08-10 11:31 UTC, tamasvajk commented
diff job to check `getMember` inlining: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/1246/

2021-08-12 08:27 UTC, tamasvajk commented
@hvitved The diff jobs show better performance now. The first one shows some perf change in `DefaultToString` (+45s), and the second one with the `getMember` inlining improves it (-41s).

The failing test seems to be unrelated.

2021-08-16 07:40 UTC, hvitved approved these changes

2021-08-16 10:22 UTC, merged