C#: Add ServiceStack support
github/codeql pull request #6461
Opened 2021-08-10 13:26 UTC by tamasvajk

This PR is based on https://github.com/github/codeql/pull/5494.

The following changes were applied:
- [x] merge the latest main into the PR
- [ ] add tests
- [ ] cover more APIs
- [ ] migrate to the data-driven flow approach

2021-08-17 13:19 UTC, tamasvajk commented on csharp/ql/src/semmle/code/csharp/frameworks/ServiceStack.qll
> +        "ServiceStack.Redis;IRedisClientAsync;true;LoadLuaScriptAsync;(System.String,System.Threading.CancellationToken);;Argument[0];sql"
These should probably be part of the code injection sinks rather than the sql ones.

2021-09-14 13:18 UTC, hvitved requested changes
Great work!

2021-09-14 13:18 UTC, hvitved commented on csharp/ql/lib/semmle/code/csharp/dispatch/RuntimeCallable.qll
> +    (
Do you need to do another merge from `main` to get rid of this, now that https://github.com/github/codeql/pull/6630 has been merged?

2021-09-14 13:18 UTC, hvitved commented on csharp/ql/lib/semmle/code/csharp/frameworks/ServiceStack.qll
> +    this.getABaseInterface+().hasQualifiedName("ServiceStack", "IService")
Should this be `this.getABaseType*().getABaseInterface().hasQualifiedName("ServiceStack", "IService")`? That will then include sub classes of classes that implement the interface.

2021-09-14 13:18 UTC, hvitved commented on csharp/ql/lib/semmle/code/csharp/frameworks/ServiceStack.qll
> +  RequestDTO() { this.getABaseInterface+().hasQualifiedName("ServiceStack", "IReturn") }
same comment as above.

2021-09-14 13:18 UTC, hvitved commented on csharp/ql/lib/semmle/code/csharp/frameworks/ServiceStack.qll
> +        ) and
this can be simplified to `m.canReturn(e)`.

2021-09-16 07:55 UTC, hvitved approved these changes

2021-09-17 08:16 UTC, merged