Python: Promote modeling of SQLAlchemy
github/codeql pull request #6589
Opened 2021-09-02 08:52 UTC by RasmusWL

After creating elaborate tests for how you can use the ORM to construct queries, I realized it would be difficult to make our normal SQL injection query ever flag those, so did a 180 on how to handle it, and ended up adding a new query.

We could also extend our existing SQL-injection query to _also_ flag up TextClause injection. I felt that putting them together would end up being a bit confusing, but I'm very open to changing this if it is cause for concern.

2021-09-16 09:49 UTC, yoff requested changes
Quite impressive testing here and also the work to complete the modelling 💪 
I thought it over, and it does seem quite reasonable (as in not overly FP-prone) to always alert on text objects being user controlled. If such objects are not executed, the code can probably be simplified and the alert would have been still useful. So the two-query-approach seems fine here.

It might be nice to add an inline style test for the bonus query, but I am happy to merge without it. The requested changes only really comprise the one typo I spotted...

2021-09-16 09:49 UTC, yoff commented on python/ql/src/Security/CWE-089/SQLAlchemyTextClauseInjection.qhelp
> +user-supplied input will passed passed to the database using query parameters. The
```suggestion
user-supplied input will be passed to the database using query parameters. The
```

2021-09-16 09:49 UTC, yoff commented on python/ql/test/query-tests/Security/CWE-089-SQLAlchemyTextClauseInjection/test.py
> +    # All of these should be flagged by query
...and they are :-) I guess that would be more clear from an inline test.

2021-09-20 10:06 UTC, RasmusWL commented
> It might be nice to add an inline style test for the bonus query, but I am happy to merge without it. The requested changes only really comprise the one typo I spotted...

Yes. I think we have something to learn from JS here, since they have a standard test setup where they use something like `# $ OK` and `# $ NOT_OK` to ensure proper flow.

2021-09-20 15:33 UTC, yoff approved these changes
LGTM as soon as the subpaths are added to the test expectations.

2021-09-21 09:08 UTC, yoff approved these changes
LGTM

2021-09-21 09:08 UTC, merged