Python : Add sanitizers for Path Injection Query
github/codeql pull request #7009
Opened 2021-10-29 20:01 UTC by porcupineyhairs

This PR adds a few sanitizers to the exisitng Path injection query.

2021-10-31 21:15 UTC, intrigus-lgtm commented on python/ql/lib/semmle/python/security/dataflow/PathInjectionCustomizations.qll
> +      this = API::moduleImport("os").getMember("path").getMember("abspath").getACall().getArg(_)
I might be wrong, but isn't this saying that the **argument** to `abspath` has been sanitized?
Don't we instead want to say that the **result** of such a call has been sanitized?

So in this example:
```python
sanitizedPath = os.path.abspath(taintedPath)
dangerousUse(taintedPath)
```
`taintedPath` could not flow to `dangerousUse` because it is used once as an argument to `abspath` and therefore considered sanitized (which is not correct).

If I'm right you could add new tests that show the improvements of this PR.

2021-11-01 01:08 UTC, porcupineyhairs commented on python/ql/lib/semmle/python/security/dataflow/PathInjectionCustomizations.qll
> +      this = API::moduleImport("os").getMember("path").getMember("abspath").getACall().getArg(_)
I considered it when writing this PR. Yes, what you are saying is true. But consider the case here. https://github.com/kizniche/Mycodo/blob/6c0d710c8138aa06e6dcd909097854afe0d5cebe/mycodo/mycodo_flask/routes_general.py#L120-L121

In this case, since `file_path` is checked earlier, the code is not exploitable. So I thought it would be best to avoid multiple FPs and accept a reduced TP count instead.

2021-11-01 02:11 UTC, porcupineyhairs commented
@RasmusWL The query currently flags some sinks which shouldn't otherwise be there. For ex, a simple run of the query with the proposed changes included leads to 3 results. Of which 2 of them are calls to `os.path.getctime` and `os.path.exists`. I think these can be easily avoided if we were to use code from the `StdLibPrivate` module. This would reduce code duplication and let us reduce FP's. Should I mark it public?

2021-11-01 10:35 UTC, RasmusWL requested changes
This PR goes against how we deal with path injection. You should NOT change the query. 

`abspath` is already modeled, see https://github.com/github/codeql/blob/8b6baa250cd41300e5f5d3e8bab81b18c7705407/python/ql/lib/semmle/python/frameworks/Stdlib.qll#L303-L311

and `.startswith` is already modeled:

https://github.com/github/codeql/blob/8b6baa250cd41300e5f5d3e8bab81b18c7705407/python/ql/lib/semmle/python/frameworks/Stdlib.qll#L1757-L1768

So all in all, I'm surprised this isn't handled properly already.

As a first step, can you please update the query test file to include the new case (FP) that you want to handle better (remember to update the `.expected` files).

Then we will need to figure out why the current modeling doesn't work.

2021-11-01 10:36 UTC, RasmusWL commented
(I didn't notice this reply at first)

> @RasmusWL The query currently flags some sinks which shouldn't otherwise be there. For ex, a simple run of the query with the proposed changes included leads to 3 results. Of which 2 of them are calls to `os.path.getctime` and `os.path.exists`. I think these can be easily avoided if we were to use code from the `StdLibPrivate` module. This would reduce code duplication and let us reduce FP's. Should I mark it public?

@porcupineyhairs can you please add tests with these cases? I'm not able to imagine what these FPs looks like based on just that text :shrug:

2021-11-02 21:12 UTC, porcupineyhairs commented
@RasmusWL I have added the tests now. These are based on [kizniche/Mycodo](https://lgtm.com/projects/g/kizniche/Mycodo/)

Also, there are sinks which we are not detected by the query but which otherwise should have been included there eg. `os.mkdirs`. I can see when you modeled the `os` module, these were specifically left out. Was there a specific reason for the same? Do you want me to add them now?

2021-11-02 21:22 UTC, intrigus-lgtm commented on python/ql/test/query-tests/Security/CWE-022-PathInjection/path_injection.py
> +    if not os.path.exists(image_path): # OK as exposure of ctime of a particular file does not pose a security thread
Duplicate comment? Compare with line 136.

2021-11-04 13:17 UTC, RasmusWL requested changes
Please remove the commits that change the `.qll` files :pray: as highlighted in my previous review, I do not think this is the right approach.

I don't see any tests resembling https://github.com/kizniche/Mycodo/blob/6c0d710c8138aa06e6dcd909097854afe0d5cebe/mycodo/mycodo_flask/routes_general.py#L120-L121 -- I thought that was the FP you wanted to handle?

> Also, there are sinks which we are not detected by the query but which otherwise should have been included there eg. os.mkdirs. I can see when you modeled the os module, these were specifically left out. Was there a specific reason for the same? Do you want me to add them now?

That is not intentional. Please add this modeling in a separate PR :+1:

2021-11-04 13:20 UTC, RasmusWL commented on python/ql/test/query-tests/Security/CWE-022-PathInjection/path_injection.py
> +    timestamp = os.path.getctime(image_path) # OK as exposure of ctime of a particular file does not pose a security thread
Being able to determine file existence is an information leak, that is a known vulnerability. First results from a google search was https://www.acunetix.com/vulnerabilities/web/arbitrary-file-existence-disclosure-in-action-pack/ -- please change this test to say `NOT OK`

2021-11-09 13:54 UTC, RasmusWL commented
I've made a PR to add the interesting FP case here: https://github.com/github/codeql/pull/7087

2021-11-10 00:52 UTC, porcupineyhairs commented
I am closing this PR as this is rendered useless with #7087 landing. As for the new sinks, I will open a PR in a day or two.

2021-11-10 00:52 UTC, closed without merging