JS: Add insufficient key size query
github/codeql pull request #7021
Opened 2021-11-02 08:21 UTC by erik-krogh

2021-11-02 13:51 UTC, Misran28 approved these changes

2021-11-02 14:06 UTC, RasmusWL reviewed
I'm not 100% sure about the change to `python/ql/lib/semmle/python/concepts/CryptoAlgorithms.qll`. Treating AES-CBC as secure got me a little suspicious, and doing a bit of research revealed that indeed, CBC can be vulnerable to a _padding oracle attack_ (described in blogposts at [Microsoft](https://docs.microsoft.com/en-us/dotnet/standard/security/vulnerabilities-cbc-mode) and [Cloudflare](https://blog.cloudflare.com/padding-oracles-and-the-decline-of-cbc-mode-ciphersuites/)). I'm not 100% sure how we should deal with this, but very interested to hear if you had thought about this :blush: 

In regards to the new query, I can see a difference with the one we have in Python. This query covers symmetric and asymmetric algorithms, and the Python query covers asymmetric (specifically RSA/DSA) and elliptic curve cryptography (ECC). So maybe you should look at adding ECC for this query? (and maybe we should look at adding support for symmetric algorithms in the Python version)

2021-11-02 14:11 UTC, esbena reviewed
LGTM.

The qhelp lacks examples, but the language versions of this query also lack those, so I suppose that is alright.

2021-11-02 14:12 UTC, Misran28 approved these changes

2021-11-03 14:13 UTC, erik-krogh commented
> I'm not 100% sure about the change to `python/ql/lib/semmle/python/concepts/CryptoAlgorithms.qll`. Treating AES-CBC as secure got me a little suspicious, and doing a bit of research revealed that indeed, CBC can be vulnerable to a _padding oracle attack_ (described in blogposts at [Microsoft](https://docs.microsoft.com/en-us/dotnet/standard/security/vulnerabilities-cbc-mode) and [Cloudflare](https://blog.cloudflare.com/padding-oracles-and-the-decline-of-cbc-mode-ciphersuites/)). I'm not 100% sure how we should deal with this, but very interested to hear if you had thought about this blush

Yes, CBC is bad (TIL), but I don't think that's something we can handle in `CryptoAlgorithms.qll`.   
The encryption algorithm used (AES) is considered safe (with a strong enough key), and the attack against CBC seems to require a pretty stable timing side-channel. 

I think hardcoding some mode-of-operations and only adding them to a few of the algorithms was the wrong approach.  
I've instead changed the `matchesName` predicate such that it ignores everything after a dash. 
That way modes-of-operations can be included in the name, without us having to explicitly handle it. 

> In regards to the new query, I can see a difference with the one we have in Python. This query covers symmetric and asymmetric algorithms, and the Python query covers asymmetric (specifically RSA/DSA) and elliptic curve cryptography (ECC). So maybe you should look at adding ECC for this query? (and maybe we should look at adding support for symmetric algorithms in the Python version)

I just added the what I found to be relevant for the libraries I encountered.   
E.g. [the NodeJS crypto library method for creating an ECC object](https://nodejs.org/api/crypto.html#cryptocreateecdhcurvename) does not allow explicitly setting the length of the key, so I didn't see a need to model ECC.

2021-11-08 07:46 UTC, esbena approved these changes

2021-11-09 10:09 UTC, RasmusWL requested changes
Thanks for looking into the modes of operation. I think we could probably handle this better, but for now I guess it looks ok :+1:

I would like a small comment explaining _why_ we ignore everything after the dash, but otherwise LGTM :+1:

2021-11-09 10:09 UTC, RasmusWL commented on python/ql/lib/semmle/python/concepts/CryptoAlgorithms.qll
> +   * white space, dashes, underscores, and anything after a dash in the name.
```suggestion
   * white space, dashes, underscores, and anything after a dash in the name
   * (to ignore modes of operation, such as CBC or ECB).
```

2021-11-09 10:09 UTC, RasmusWL commented on javascript/ql/lib/semmle/javascript/security/CryptoAlgorithms.qll
> +   * white space, dashes, underscores, and anything after a dash in the name.
```suggestion
   * white space, dashes, underscores, and anything after a dash in the name
   * (to ignore modes of operation, such as CBC or ECB).
```

2021-11-09 11:00 UTC, RasmusWL approved these changes

2021-11-11 11:00 UTC, erik-krogh commented
@esbena are you OK with the changes? Can I get a re-approve?

2021-11-11 11:15 UTC, esbena approved these changes

2021-11-11 11:17 UTC, merged