Python: model aiomysql
github/codeql pull request #7104
Opened 2021-11-10 13:31 UTC by yoff

2021-11-10 14:52 UTC, RasmusWL requested changes
A few of the links doesn't work, but otherwise LGTM :+1:

2021-11-10 14:52 UTC, RasmusWL commented on python/ql/lib/semmle/python/frameworks/Aiomysql.qll
> +   * See https://aiomysql.readthedocs.io/en/stable/core.html#pool
This link does not work

2021-11-10 14:52 UTC, RasmusWL commented on python/ql/lib/semmle/python/frameworks/Aiomysql.qll
> +   * See https://aiomysql.readthedocs.io/en/stable/core.html#connection
neither does this one

2021-11-10 14:52 UTC, RasmusWL commented on python/ql/lib/semmle/python/frameworks/Aiomysql.qll
> +   * See https://aiomysql.readthedocs.io/en/stable/core.html#cursor
or this

2021-11-10 14:52 UTC, RasmusWL commented on python/ql/lib/semmle/python/frameworks/Aiomysql.qll
> +   * See https://aiomysql.readthedocs.io/en/stable/core.html#aiomysql.Cursor.execute
or this

2021-11-10 14:52 UTC, RasmusWL commented on python/ql/lib/semmle/python/frameworks/Aiomysql.qll
> +   * See https://aiomysql.readthedocs.io/en/stable/core.html#aiomysql.Cursor.execute
or this

2021-11-11 12:22 UTC, yoff commented
Good catch (I really should have checked this), they are probably the result of a search and replace, it is somewhat hilarious that any of them actually worked.. :-)

2021-11-11 15:57 UTC, RasmusWL approved these changes
Thanks, LGTM :+1:

2021-11-11 15:58 UTC, merged