C#: PrimaryQlClass
github/codeql pull request #7118
Opened 2021-11-12 09:08 UTC by michaelnebel

(1) Introduce a unit test that prints getAPrimaryQlClass on each element
(2) Add overrides for getAPrimaryQlClass for all elements, where "???" was printed as primary ql class (ie. missing overrides caught by the test introduced in (1)).

You can pinpoint and *only* execute the PrimaryQlClass tests by
```bash
csharp/ql/test>  find . -type f -name "PrimaryQlClass.qlref" -exec codeql test run {} \;
```

2022-01-13 14:28 UTC, hvitved requested changes

2022-01-13 15:36 UTC, michaelnebel commented on csharp/ql/consistency-queries/PrimaryQlClass.ql
> +  e.getAPrimaryQlClass() = "???" and
Ah yes.

2022-01-14 10:14 UTC, hvitved requested changes

2022-01-14 10:14 UTC, hvitved commented on csharp/ql/lib/semmle/code/csharp/Generics.qll
> +  /** Gets a textual representation of the class */
Remove

2022-01-14 12:32 UTC, hvitved approved these changes

2022-01-14 15:14 UTC, merged