python: Rewrite path injection query to use flow state
github/codeql pull request #7687
Opened 2022-01-21 08:28 UTC by yoff

This removes the FP caused by chaining.

This PR also removes `ChainedConfigs12.qll`, as we hope to solve future problems via flow states.

2022-01-25 17:01 UTC, RasmusWL requested changes
Very cool that you have porting these queries to use flow state :muscle: (also great to see that FP removed)

Is there an official doc for how to use flow state? (so I know if you made up the way to handle things, or if there is an established way already)

For `python/ql/lib/semmle/python/security/dataflow/PathInjection.qll`, I'm wondering how much deprecation we need to support. At least if someone has code that uses the old configurations (or old predicate), their code is going to stop working if this PR is merged as it is right now.

I also have a minor comment for the chained-config qll file, where I think we can mark even more things as deprecated.

2022-01-25 18:24 UTC, yoff commented on python/ql/lib/semmle/python/security/dataflow/ChainedConfigs12.qll
> +class CustomPathNode extends TCustomPathNode {
I have nothing against this, but I thought I had deprecated the whole file?

2022-01-25 18:26 UTC, yoff commented on python/ql/src/experimental/semmle/python/security/injection/NoSQLInjection.qll
> +    }
We are only blocking flow on the output, so I believe both instances of `user_input` will be `"RemoteInput"` while both `decoded_1` and `decoded_2` will be `"ConvertedToDict"`.

2022-01-25 18:28 UTC, yoff commented
> Is there an official doc for how to use flow state? (so I know if you made up the way to handle things, or if there is an established way already)

I am not aware of any official doc, so this is all made up, but it seemed pretty intuitive :-)
(I am happy for best practices to evolve, though. JavaScript has a fairly advanced flow-state based query for path injection that we should probably attempt to port at some point.)

2022-01-25 18:30 UTC, yoff commented
Good point about the old configuration being public. We may have to leave it deprecated instead of deleting it.

2022-01-31 07:34 UTC, yoff commented on python/ql/lib/semmle/python/security/dataflow/ChainedConfigs12.qll
> +class CustomPathNode extends TCustomPathNode {
I see, there is a formal `detracted` keyword. That will help discover the deprecation. I also deprecated the two predicates.

2022-01-31 10:57 UTC, RasmusWL commented on python/ql/src/experimental/semmle/python/security/injection/NoSQLInjection.qll
> +    }
yes, I overlooked the part about _flow on the output_. Thanks :+1:

2022-01-31 11:07 UTC, RasmusWL approved these changes
:+1: with the deprecations.

I'm still a bit surprised that the flow-state specific sanitizer is `isBarrier/2`, but :shrug: 

Out of interest, did you come up with the scheme of blocking flow for the old state when there is a state transition that occurs? (as with the barrier for NoSQL injection) I guess it helps with performance on the data-flow library, so I can see the benefit for sure :+1:

2022-02-01 08:16 UTC, yoff commented
> Out of interest, did you come up with the scheme of blocking flow for the old state when there is a state transition that occurs?

Yes. I guess we should get the conversation going about how to actually use flow states effectively, but in many cases it has to be blocked or it will reach the sink.

2022-02-01 08:18 UTC, yoff commented
> I'm still a bit surprised that the flow-state specific sanitizer is `isBarrier/2`, but

I think it is because it is implemented for the data flow configurations, and no taint-specific veneer has been added to taint configurations...

2022-02-01 10:33 UTC, merged