Python: Support Django FileField.upload_to
github/codeql pull request #7776
Opened 2022-01-27 17:31 UTC by RasmusWL

2022-02-25 11:13 UTC, yoff requested changes
Cool addition to our models.

2022-02-25 11:13 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Django.qll
> +        ) and
```suggestion
        uploadToArg in [call.getArg(2), call.getArgByName("upload_to")] and
```

2022-03-01 14:51 UTC, RasmusWL commented on python/ql/lib/semmle/python/frameworks/Django.qll
> +   * to construct a path, path injection is not possible.
No, I did not. I doubt this will work, but I'll do the due diligence and check it :+1:

2022-03-28 11:16 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Django.qll
> +   * to construct a path, path injection is not possible.
I am curious :-)

2022-03-28 11:17 UTC, yoff approved these changes
LGTM once the conflicts are resolved

2022-05-05 12:24 UTC, yoff approved these changes
Nice, thanks for the thorough test :-)

2022-05-05 12:25 UTC, merged