Python: promote xpath injection query
github/codeql pull request #7915
Opened 2022-02-09 13:51 UTC by yoff

Commits are structured in an attempt to preserve the original files before they get adapted.

Possible concerns:
 - should we model more of lxml? XPathEvaluator, soupparser
 - should we model more frameworks?
   - `stdlib` has `xml.etree.ElementTree`
   - [py-dom-xpath](https://github.com/neild/py-dom-xpath)
   - PyXML
   - [parsel](https://github.com/scrapy/parsel)

2022-02-28 14:24 UTC, RasmusWL requested changes
Very nice commit structure :muscle: 

To answer your questions:

> the precision was never tested and no sanitizers are implemented (but js and java also seem to not have sanitizers)

I looked back through the archives, and the precision was tested, but not determined since it didn't actually find any results. We should try running the final query against all of LGTM, to see what the status is now.

> should we model more of lxml? XPathEvaluator, soupparser

I had to look it up ([here](https://lxml.de/apidoc/lxml.etree.html#lxml.etree.XPathEvaluator)), and yes, that sounds like it's easy to extend with this functionality... let's do it :+1:

> should we model more frameworks?

Would be cool with support for standard library :+1:

From reading https://docs.python.org/3.10/library/xml.etree.elementtree.html#elementtree-xpath it should also be quite simple. I think we can utilize some of the modeling from the [XXE PR](https://github.com/github/codeql/pull/6112) as well, once that is promoted. So for now, I think it's ok for the "parsed document" to be fairly simple for stdlib etree :+1:

2022-02-28 14:30 UTC, yoff commented on python/ql/src/Security/CWE-643/XpathInjection.ql
> + * @problem.severity error
Thanks!

2022-03-01 09:22 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Lxml.qll
> +    override DataFlow::Node getTree() { none() }
Indeed, we can easily add it when the need arises. Then we just need to go through all supported frameworks and implement it, but the compiler will tell us where.

2022-03-01 09:28 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Lxml.qll
> +            .getMember(["parse", "fromstring", "fromstringlist", "HTML", "XML"])
Sounds good.

2022-03-01 15:48 UTC, RasmusWL commented
@yoff I would actually also recommend that we make a `XML` module in the Concepts file, since I know that we will get more XML stuff when we promote the XXE query, so otherwise we will flood the top-level namespace with XML stuff :grimacing:

2022-03-04 09:45 UTC, RasmusWL reviewed
Overall LGTM!

However, I did not see any comments about the precision. Did you confirm that `high` is the right choice?

2022-03-04 09:45 UTC, RasmusWL commented on python/ql/test/library-tests/frameworks/stdlib/XPathExecution.py
> +tree = ElementTree()
NIT

```suggestion
tree = ET.ElementTree()
```

2022-03-04 09:56 UTC, yoff commented
> However, I did not see any comments about the precision. Did you confirm that `high` is the right choice?
Yes, you should see a mention from an issue with a link to a full run. Looking through the results there, I found it to be fairly precise.

2022-03-04 09:57 UTC, yoff commented on python/ql/test/library-tests/frameworks/stdlib/XPathExecution.py
> +tree = ElementTree()
Thanks

2022-03-04 09:59 UTC, RasmusWL approved these changes
> Yes, you should see a mention from an issue with a link to a full run. Looking through the results there, I found it to be fairly precise.

great :+1:

2022-03-04 10:59 UTC, merged