Ruby: separate constant propagation of regexps from strings
github/codeql pull request #7985
Opened 2022-02-11 17:38 UTC by nickrolfe

This lets us distinguish constant regexp values from regular strings, which will be useful for a query I'm working on. It's similar to the way that symbols are already distinguished from strings.

As part of the change, I've deprecated the names `getStringOrSymbol` and `isStringOrSymbol`, and replaced them with `getStringlikeValue` and `isStringlikeValue`.

N.B. I checked that there were no changes to `ValueText.expected` besides the new column.

2022-02-15 13:36 UTC, nickrolfe commented
This needs some work, for example to track the regexp flag string alongside its value. I'll update the PR once I've validated the approach by finishing the query I'm working on.

2022-03-28 09:07 UTC, hvitved requested changes
Looks great! We should run a DCA job before merging.

2022-03-28 09:07 UTC, hvitved commented on ruby/ql/test/library-tests/ast/escape_sequences/EscapeSequences.ql
>    value = l.getConstantValue().getString() and kind = "string"
Can now be simplified to
```ql
exists(ConstantValue v | v = l.getValueType() and value = v.getString() and kind = v.getValueType())
```

2022-03-28 09:58 UTC, nickrolfe commented on ruby/ql/test/library-tests/ast/escape_sequences/EscapeSequences.ql
>    value = l.getConstantValue().getString() and kind = "string"
You mean
```ql
exists(ConstantValue v |
  v = l.getConstantValue() and value = v.getStringlikeValue() and kind = v.getValueType()
)
```
But yes, good point.

2022-03-28 11:30 UTC, hvitved commented on ruby/ql/test/library-tests/ast/escape_sequences/EscapeSequences.ql
>    value = l.getConstantValue().getString() and kind = "string"
Yes, indeed.

2022-03-28 12:06 UTC, nickrolfe commented
I merged in `main` to resolve the conflict with renamed `ParseRegExp.qll` (git was able to merge it cleanly).

2022-03-30 09:36 UTC, nickrolfe commented
DCA performance looks fine to me.

2022-03-30 10:37 UTC, merged