Python: Fix a bunch of QL warnings
github/codeql pull request #8336
Opened 2022-03-04 15:21 UTC by tausbn

2022-03-08 07:45 UTC, michaelnebel approved these changes
C#: LGTM

2022-03-08 08:22 UTC, atorralba approved these changes
Java 👍

2022-03-08 14:06 UTC, yoff requested changes
Thank you for doing this!

2022-03-08 14:06 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Aiomysql.qll
> +   * Gets the `ConnectionPool` that is created when the result of `aiomysql.create_pool()` is awaited.
```suggestion
   * Gets a `ConnectionPool` that is created when the result of `aiomysql.create_pool()` is awaited.
```
This being an API node, I think we should express that multiple results are likely.

2022-03-08 14:06 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Aiomysql.qll
> +   * Gets the `Connection` that is created when
```suggestion
   * Gets a `Connection` that is created when
```

2022-03-08 14:06 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Aiomysql.qll
> +   * Gets the `Cursor` that is created when
```suggestion
   * Gets a `Cursor` that is created when
```

2022-03-08 14:06 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Aiomysql.qll
> +   * Gets the `SAConnection` that is created when the result of calling `aquire` on an `Engine` is awaited.
```suggestion
   * Gets an `SAConnection` that is created when the result of calling `aquire` on an `Engine` is awaited.
```

2022-03-08 14:06 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Aiopg.qll
> +   * Gets the `ConnectionPool` that is created when the result of `aiopg.create_pool()` is awaited.
```suggestion
   * Gets a `ConnectionPool` that is created when the result of `aiopg.create_pool()` is awaited.
```

2022-03-08 14:06 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Aiopg.qll
> +   * Gets the `Connection` that is created when
```suggestion
   * Gets a `Connection` that is created when
```

2022-03-08 14:06 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Aiopg.qll
> +   * Gets the `Cursor` that is created when
```suggestion
   * Gets a `Cursor` that is created when
```

2022-03-08 14:06 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Aiopg.qll
> +   * Gets the `SAConnection` that is created when the result of calling `aquire` on an `Engine` is awaited.
```suggestion
   * Gets an `SAConnection` that is created when the result of calling `aquire` on an `Engine` is awaited.
```

2022-03-08 14:06 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Asyncpg.qll
> +  /** Gets the `ConnectionPool` that is created when the result of `asyncpg.create_pool()` is awaited. */
```suggestion
  /** Gets a `ConnectionPool` that is created when the result of `asyncpg.create_pool()` is awaited. */
```

2022-03-08 14:06 UTC, yoff commented on python/ql/lib/semmle/python/frameworks/Asyncpg.qll
> +   * Gets the `Connection` that is created when
```suggestion
   * Gets a `Connection` that is created when
```

2022-03-08 14:13 UTC, tausbn commented on python/ql/src/Imports/DeprecatedModule.ql
>   */
Ah, good catch.

2022-03-08 14:24 UTC, MathiasVP approved these changes
C++ 👍

2022-03-08 14:34 UTC, yoff approved these changes
Happy to merge this now.
The `Field only used in CharPred`-warnings are interesting, but can be tackled later.

2022-03-09 14:08 UTC, alexrford approved these changes
Ruby 👍

2022-03-09 15:31 UTC, merged