Gelişme
github/codeql pull request #8388
Opened 2022-03-09 16:04 UTC by ErcetinGuler

Güvenlik Güncelemeleri

2022-03-09 18:06 UTC, ErcetinGuler commented
neden kapattın

2022-03-09 18:28 UTC, aibaars commented
> neden kapattın

I closed it because the pull request looks like automatically generated spam. Apologies if it isn't. I see you have made contributions to other repositories. Could you please follow the advice in https://github.com/github/vscode-codeql/pull/1185#issuecomment-1059424858 .

2022-03-09 18:36 UTC, aibaars requested changes
Could you squash the commit history of your pull request and address the comments?

2022-03-09 18:36 UTC, aibaars commented on .github/workflows/codeql.yml
> +# For most projects, this workflow file will not need changing; you simply need
Please delete this file, we already run CodeQL, see https://github.com/github/codeql/blob/ef227a47219aef17c62bfe881b6459ef20ceb828/.github/workflows/codeql-analysis.yml .

2022-03-09 18:36 UTC, aibaars commented on SECURITY.md
> +# Security Policy
Please remove this file from the pull request.

2022-03-09 18:36 UTC, aibaars commented on ruby/extractor/Cargo.toml
> +clap = "3.0"
The two `Cargo.toml` files have conflicts, could you resolve these please. In addition, the [Cargo.lock](https://github.com/github/codeql/blob/ef227a47219aef17c62bfe881b6459ef20ceb828/ruby/Cargo.lock) file needs to be updated to reflect the dependency changes.

2022-03-15 02:42 UTC, ErcetinGuler commented
umarım olmuştur

2022-03-22 10:40 UTC, closed without merging