Python: Reduce duplicated alerts for flask sources
github/codeql pull request #8516
Opened 2022-03-21 21:27 UTC by RasmusWL

This should help remove "duplicate alerts" from referencing `from flask import request` multiple times within the same function. This should not be a very invasive change, since it will only remove some existing alerts (and should not remove all existing sources within a single function, so therefore also no alerts).

Draft PR to check whether any tests fails, before requesting review ;)

2022-03-23 13:02 UTC, yoff requested changes
This ends up saying: Give me all uses which are neither in an import nor downstream (by local flow) of another source. If one of these nodes has local flow to another, then they should have a common `LocalSourceNode`. I know that you have already shown that such a local source may not be in `potentialFlaskRequestSource` (because it is an import in a local scope) but perhaps it is the right source anyway?

2022-03-24 09:36 UTC, RasmusWL commented on python/ql/lib/semmle/python/frameworks/Flask.qll
> +      not DataFlow::localFlowStep(potentialFlaskRequestSource(), this)
good point. I think I did this due to some other attempts to solve this, where I wanted it to be a single step :shrug:

2022-03-24 09:58 UTC, RasmusWL commented
Started evaluation to check that we don't loose any taint based on this, but only the duplicated sources. (also checking perf of course)

2022-03-24 10:52 UTC, yoff submitted a review, later dismissed
Ok, I think this is a good patch for now, but I would like to understand the underlying problem, so we do not have to do this everywhere...

2022-04-22 08:46 UTC, RasmusWL commented
Evaluation needs a bit more investigation, so marking this as draft

2022-10-24 07:33 UTC, RasmusWL commented
closing in favor of https://github.com/github/codeql/pull/10629

2022-10-24 07:33 UTC, closed without merging