Dataflow: Revert support for flow-state based in-/out-barriers
github/codeql pull request #8703
Opened 2022-04-08 11:55 UTC by aschackmull

Resolves https://github.com/github/codeql/pull/8435#issuecomment-1087530306

2022-04-08 11:56 UTC, aschackmull commented
Depends on https://github.com/github/codeql/pull/8702

2022-04-08 11:58 UTC, jketema commented on cpp/ql/lib/change-notes/2022-03-14-flow-state-barriers.md
> +* The data flow and taint tracking libraries have been extended with versions of `isBarrierGuard`, respectively `isSanitizerGuard`, that support flow states.
I didn't keep track when the latest release was, but that might already have deleted this change note and the others like this..

2022-04-08 12:45 UTC, jketema requested changes
Per change note documentation

2022-04-08 12:45 UTC, jketema commented on cpp/ql/lib/change-notes/2022-04-08-flow-state-barriers.md
> +The recently added flow-state versions of `isBarrierIn`, `isBarrierOut`, `isSanitizerIn`, and `isSanitizerOut` in the data flow and taint tracking libraries have been removed.
```suggestion
* The recently added flow-state versions of `isBarrierIn`, `isBarrierOut`, `isSanitizerIn`, and `isSanitizerOut` in the data flow and taint tracking libraries have been removed.
```

2022-04-08 12:45 UTC, jketema commented on csharp/ql/lib/change-notes/2022-04-08-flow-state-barriers.md
> +The recently added flow-state versions of `isBarrierIn`, `isBarrierOut`, `isSanitizerIn`, and `isSanitizerOut` in the data flow and taint tracking libraries have been removed.
```suggestion
* The recently added flow-state versions of `isBarrierIn`, `isBarrierOut`, `isSanitizerIn`, and `isSanitizerOut` in the data flow and taint tracking libraries have been removed.
```

2022-04-08 12:45 UTC, jketema commented on java/ql/lib/change-notes/2022-04-08-flow-state-barriers.md
> +The recently added flow-state versions of `isBarrierIn`, `isBarrierOut`, `isSanitizerIn`, and `isSanitizerOut` in the data flow and taint tracking libraries have been removed.
```suggestion
* The recently added flow-state versions of `isBarrierIn`, `isBarrierOut`, `isSanitizerIn`, and `isSanitizerOut` in the data flow and taint tracking libraries have been removed.
```

2022-04-08 12:45 UTC, jketema commented on python/ql/lib/change-notes/2022-04-08-flow-state-barriers.md
> +The recently added flow-state versions of `isBarrierIn`, `isBarrierOut`, `isSanitizerIn`, and `isSanitizerOut` in the data flow and taint tracking libraries have been removed.
```suggestion
* The recently added flow-state versions of `isBarrierIn`, `isBarrierOut`, `isSanitizerIn`, and `isSanitizerOut` in the data flow and taint tracking libraries have been removed.
```

2022-04-08 12:45 UTC, jketema commented on ruby/ql/lib/change-notes/2022-04-08-flow-state-barriers.md
> +The recently added flow-state versions of `isBarrierIn`, `isBarrierOut`, `isSanitizerIn`, and `isSanitizerOut` in the data flow and taint tracking libraries have been removed.
```suggestion
* The recently added flow-state versions of `isBarrierIn`, `isBarrierOut`, `isSanitizerIn`, and `isSanitizerOut` in the data flow and taint tracking libraries have been removed.
```

2022-04-08 13:01 UTC, jketema approved these changes

2022-04-11 08:05 UTC, geoffw0 commented
What's the story here?  I'm using `isBarrierOut(DataFlow::Node node, string flowstate)` in an upcoming PR.

2022-04-11 09:18 UTC, MathiasVP commented
> What's the story here? I'm using `isBarrierOut(DataFlow::Node node, string flowstate)` in an upcoming PR.

It turns out that this is too difficult to implement correctly. See the conversation linked in the PR description: https://github.com/github/codeql/pull/8435#issuecomment-1087530306

2022-04-11 09:35 UTC, geoffw0 commented
I think I can get by using `isBarrier(Node node, FlowState state)`, with probably little or no loss of accuracy.  Is that the right approach?

2022-04-11 10:32 UTC, MathiasVP commented
> I think I can get by using `isBarrier(Node node, FlowState state)`, with probably little or no loss of accuracy. Is that the right approach?

`isBarrier(node, state)` isn't going anywhere, no. I can't tell whether it's the right approach (since I don't know what your use-case is!), but it's definitely an API that's supported by the dataflow library.

2022-04-14 07:51 UTC, jketema commented
@aschackmull https://github.com/github/codeql/pull/8702 has been merged. I'm not sure if you want to rebase this to get all the tests green or not, so I leave merging of this PR to you.

2022-04-19 13:30 UTC, aschackmull commented
> @aschackmull #8702 has been merged. I'm not sure if you want to rebase this to get all the tests green or not, so I leave merging of this PR to you.

Thanks, I've rebased the PR.

2022-04-20 12:40 UTC, jketema approved these changes

2022-04-20 12:54 UTC, merged