C#: Add an initial flow state to the model generator.
github/codeql pull request #8855
Opened 2022-04-25 11:29 UTC by michaelnebel

2022-04-26 06:49 UTC, michaelnebel commented
If we only allow a single read/write step there is a significant speedup in the generation.
<img width="836" alt="image" src="https://user-images.githubusercontent.com/6472811/165238952-2a4c0501-350c-40d3-a2ac-6794f7f6b140.png">

2022-05-05 12:55 UTC, hvitved requested changes

2022-05-05 12:55 UTC, hvitved commented on csharp/ql/src/utils/model-generator/internal/CaptureModels.qll
> + *  * We track at most two reads and at most two stores, meaning flow paths of the form
Actually, I would just remove this paragraph.

2022-05-09 05:32 UTC, michaelnebel commented on csharp/ql/src/utils/model-generator/internal/CaptureModels.qll
> + *  * We track at most two reads and at most two stores, meaning flow paths of the form
Alright. Will do so. It is probably self explainatory from the code.

2022-05-09 07:23 UTC, hvitved approved these changes

2022-05-09 08:05 UTC, merged