Make ActiveRecordInstanceMethodCall Public
github/codeql pull request #9641
Opened 2022-06-21 18:46 UTC by boveus

👋  Hi folks.  I am writing a [CodeQL query for dotcom](https://github.com/github/github/pull/221887) and it would be helpful to make use of the `ActiveRecordInstanceMethodCall` class in this query.  I currently have it copied in my query, but it seems like it would be easier to maintain if I could call the class directly.  Other folks may find this class useful in the future as well.

2022-06-23 12:59 UTC, alexrford requested changes
Yep, I'm fine with making this a public class.

2022-06-23 12:59 UTC, alexrford commented on ruby/ql/lib/codeql/ruby/frameworks/ActiveRecord.qll
> +class ActiveRecordInstanceMethodCall extends DataFlow::CallNode {
```suggestion
/**
 * A call whose receiver may be an `ActiveRecordInstance`.
 */
class ActiveRecordInstanceMethodCall extends DataFlow::CallNode {
```

2022-06-24 19:37 UTC, boveus commented
@hmac could you help me out with these failing CI checks?  Will this change require a change note?

It also looks like the qlformat check is failing, but it isn't clear why.

2022-06-27 14:13 UTC, boveus commented
@hmac - I just pushed up the formatting change, but unfortunately I don't have write access to the this repo.  Could you please add the `no-change-note-required` label for me?  Thanks.

2022-06-28 21:27 UTC, boveus commented
@alexrford does this look good to you?

2022-06-29 13:39 UTC, alexrford commented
Sorry, I didn't realize that you couldn't merge this - merging now.

2022-06-29 13:39 UTC, merged